/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewController.h>
#import "AWBottomViewDelegate.h"
#import "AWProfileRetrieverDelegate.h"

@class NSTimer, AWHUDView, UIColor, UIView, UINavigationItem, UIBarButtonItem, NSString, AWBottomView;
@protocol ActivationSuccessfulDelegate;

__attribute__((visibility("hidden")))
@interface ActivationSuccessfulViewController : UITableViewController <AWProfileRetrieverDelegate, AWBottomViewDelegate> {
	BOOL enrollmentInProgress;
	UIColor* backgroundColor;
	UIView* newTitleView;
	AWHUDView* loadingView;
	BOOL _webEnrollActivated;
	AWBottomView* _bottomView;
	NSString* _launchUrlString;
	UIBarButtonItem* _cancelBarButton;
	UINavigationItem* _ourNavigationItem;
	id<ActivationSuccessfulDelegate> _delegate;
	int _progress;
	NSString* _displayMessage;
	NSTimer* _timer;
}
@property(retain, nonatomic) NSTimer* timer;
@property(assign, nonatomic) BOOL webEnrollActivated;
@property(copy, nonatomic) NSString* displayMessage;
@property(assign, nonatomic) int progress;
@property(assign, nonatomic) id<ActivationSuccessfulDelegate> delegate;
@property(retain, nonatomic) UINavigationItem* ourNavigationItem;
@property(retain, nonatomic) UIBarButtonItem* cancelBarButton;
@property(retain, nonatomic) NSString* launchUrlString;
@property(retain, nonatomic) AWBottomView* bottomView;
-(void)profileRetriever:(id)retriever failedWithError:(id)error;
-(void)profileRetriever:(id)retriever succeededWithResponseData:(id)responseData;
-(void)saveProfileRetriverTimeStamp;
-(void)dealloc;
-(void)changeFrameBasedOnOrientation;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(unsigned)supportedInterfaceOrientations;
-(void)launchInstallUrl:(id)url;
-(void)sendRequest;
-(void)cancelPressed;
-(void)checkforUdid;
-(void)checkOnActive:(id)active;
-(void)bottomView:(id)view didSelectBotton:(int)botton;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(id)titleView;
-(void)timerExpired;
-(void)queryTime;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidUnload;
-(void)viewDidLoad;
-(id)initWithStyle:(int)style;
@end

