/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSDate;

__attribute__((visibility("hidden")))
@interface AgentTelecomUsageTracker : NSObject {
	NSDate* _startDate;
	NSDate* _endDate;
	NSDate* _lastDailyLocalNotificationFireDate;
	NSDate* _lastMonthlyLocalNotificationFireDate;
}
@property(retain, nonatomic) NSDate* lastMonthlyLocalNotificationFireDate;
@property(retain, nonatomic) NSDate* lastDailyLocalNotificationFireDate;
@property(retain, nonatomic) NSDate* endDate;
@property(retain, nonatomic) NSDate* startDate;
+(id)sharedInstance;
-(BOOL)isDateInBetweenFromDate:(id)date withBeginDate:(id)beginDate withEndDate:(id)endDate;
-(void)checkForMonthlyLocalNotificationFire;
-(void)checkForDailyLocalNotificationFire;
-(int)daysBetweenDate:(id)date toDate:(id)date2;
-(void)checkForAlerts;
-(void)checkForTelecomCycleReset;
-(BOOL)isDateWithinTelecomCycle:(id)cycle;
-(unsigned short)noOfDaysLeft;
-(void)trackTelecomUsage;
-(unsigned long long)currentTelecomCycleUsage;
-(void)setTelecomCycle;
-(void)setTelecomTrackingSettings;
@end

