/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

typedef struct _NSZone NSZone;

typedef struct CGPoint {
	float x;
	float y;
} CGPoint;

typedef struct {
	double latitude;
	double longitude;
} XXStruct_zYrK5D;

typedef struct _NSRange {
	unsigned location;
	unsigned length;
} NSRange;

typedef struct CGSize {
	float width;
	float height;
} CGSize;

typedef struct CGRect {
	CGPoint origin;
	CGSize size;
} CGRect;

typedef struct CGPDFPage* CGPDFPageRef;

typedef struct {
	unsigned long _field1;
	id* _field2;
	unsigned long* _field3;
	unsigned long _field4[5];
} XXStruct_kFm5bA;

typedef struct CGGradient* CGGradientRef;

typedef struct __CFReadStream* CFReadStreamRef;

typedef struct __CFWriteStream* CFWriteStreamRef;

typedef struct {
	int _field1;
	int _field2;
} XXStruct_K5nmsA;

typedef struct CGPDFArray* CGPDFArrayRef;

typedef struct CGPDFDictionary* CGPDFDictionaryRef;

typedef struct CGPDFDocument* CGPDFDocumentRef;

typedef struct CGPDFOperatorTable* CGPDFOperatorTableRef;

typedef struct CGPDFString* CGPDFStringRef;

typedef struct dispatch_queue_s dispatch_queue_s;

typedef struct CGPDFStream* CGPDFStreamRef;

typedef struct CGAffineTransform {
	float a;
	float b;
	float c;
	float d;
	float tx;
	float ty;
} CGAffineTransform;

typedef union CGPDFObject CGPDFObject;

typedef struct CGContext* CGContextRef;

typedef struct _AWDataSettings {
	unsigned algorithm;
	unsigned mode;
	unsigned modeOptions;
	unsigned blockSize;
	unsigned nonceSize;
	unsigned padding;
} AWDataSettings;

typedef struct __sbuf {
	char* _field1;
	int _field2;
} sbuf;

typedef struct __sFILEX sFILEX;

typedef struct __sFILE {
	char* _field1;
	int _field2;
	int _field3;
	short _field4;
	short _field5;
	sbuf _field6;
	int _field7;
	void* _field8;
	/*function-pointer*/ void* _field9;
	/*function-pointer*/ void* _field10;
	/*function-pointer*/ void* _field11;
	/*function-pointer*/ void* _field12;
	sbuf _field13;
	sFILEX* _field14;
	int _field15;
	unsigned char _field16[3];
	unsigned char _field17[1];
	sbuf _field18;
	int _field19;
	long long _field20;
} sFILE;

typedef struct _CCCryptor* CCCryptorRef;

typedef struct __CFHTTPMessage* CFHTTPMessageRef;

typedef struct __CFSocket* CFSocketRef;

typedef struct CGDataProvider* CGDataProviderRef;

typedef struct CGDataProviderSequentialCallbacks {
	unsigned version;
	/*function-pointer*/ void* getBytes;
	/*function-pointer*/ void* skipForward;
	/*function-pointer*/ void* rewind;
	/*function-pointer*/ void* releaseInfo;
} CGDataProviderSequentialCallbacks;

typedef struct {
	unsigned major;
	unsigned minor;
	unsigned release;
	unsigned hotfix;
} XXStruct_ASrbpA;

typedef struct __SCNetworkReachability* SCNetworkReachabilityRef;

typedef struct __SecKey SecKey;

typedef struct bio_method_st bio_method_st;

typedef struct bio_st {
	bio_method_st* _field1;
	/*function-pointer*/ void* _field2;
	char* _field3;
	int _field4;
	int _field5;
	int _field6;
	int _field7;
	int _field8;
	void* _field9;
	bio_st* _field10;
	bio_st* _field11;
	int _field12;
	unsigned long _field13;
	unsigned long _field14;
	crypto_ex_data_st _field15;
} bio_st;

typedef struct stack_st_void stack_st_void;

typedef struct crypto_ex_data_st {
	stack_st_void* _field1;
	int _field2;
} crypto_ex_data_st;

typedef struct sqlite3 sqlite3;

typedef struct ssl_st ssl_st;

typedef struct ssl_connection {
	ssl_st* _field1;
	bio_st* _field2;
	bio_st* _field3;
	unsigned char _field4[32000];
	int _field5;
	unsigned char _field6[32000];
	int _field7;
	int _field8;
	int _field9;
} ssl_connection;

typedef struct internal_state internal_state;

typedef struct z_stream_s {
	char* next_in;
	unsigned avail_in;
	unsigned total_in;
	char* next_out;
	unsigned avail_out;
	unsigned total_out;
	char* msg;
	internal_state* state;
	/*function-pointer*/ void* zalloc;
	/*function-pointer*/ void* zfree;
	void* opaque;
	int data_type;
	unsigned adler;
	unsigned reserved;
} z_stream_s;

typedef struct __CFDictionary* CFDictionaryRef;

typedef struct _CFHTTPAuthentication* CFHTTPAuthenticationRef;

typedef struct ntlm_info {
	char* _field1;
	char* _field2;
	char* _field3;
	char* _field4;
} ntlm_info;

typedef struct __SecTrust SecTrust;

typedef struct CGImage* CGImageRef;

typedef struct zbar_symbol_set_s zbar_symbol_set_s;

typedef struct zbar_symbol_s zbar_symbol_s;

typedef struct zbar_image_s zbar_image_s;

typedef struct zbar_image_scanner_s zbar_image_scanner_s;

typedef struct opaqueCMSampleBuffer opaqueCMSampleBuffer;

typedef struct __CVBuffer* CVBufferRef;

typedef struct __CFData* CFDataRef;


