/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIViewController.h>
#import "UIAlertViewDelegate.h"
#import "UITextFieldDelegate.h"
#import "AirWatch-Structs.h"
#import "UIGestureRecognizerDelegate.h"

@class UIButton, UIScrollView, UITapGestureRecognizer, UIImageView, UIView, AWAssetTracker, NSString, AWSession, UIActivityIndicatorView, UITextField, UILabel;

__attribute__((visibility("hidden")))
@interface AssetTrackerViewController : UIViewController <UITextFieldDelegate, UIAlertViewDelegate, UIGestureRecognizerDelegate> {
	BOOL isIPad;
	int state;
	UIActivityIndicatorView* spinner;
	AWSession* session;
	UILabel* retryMessageLabel;
	UILabel* retryTitleLabel;
	UIButton* retryButton;
	UIScrollView* retryView;
	id StatusCompletionHandlerForTracker;
	UITapGestureRecognizer* tapRecognizer;
	UILabel* checkedOutToUsernameLabel;
	UILabel* checkedOutToGroupLabel;
	UILabel* lastStatusUpdateLabel;
	BOOL keyboardIsVisible;
	CGRect keyboardRect;
	UIView* fadingView;
	BOOL showApplicableMessage;
	BOOL showDeviceImage;
	BOOL showLogo;
	BOOL showGroup;
	BOOL showContinue;
	UIImageView* deviceImageView;
	UIImageView* logoImageView;
	UIScrollView* formView;
	UIScrollView* checkinView;
	UIButton* submitButton;
	UIButton* checkinButton;
	UITextField* groupField;
	UITextField* usernameField;
	UITextField* passwordField;
	UIButton* settingsButton;
	UIView* settingsView;
	UILabel* statusLabel;
	UILabel* groupLabel;
	UILabel* usernameLabel;
	UILabel* passwordLabel;
	NSString* defaultStatusLabelText;
	AWAssetTracker* tracker;
	UIScrollView* loadingView;
	UILabel* loadingLabel;
	UIButton* continueButton;
}
@property(retain, nonatomic) UIButton* continueButton;
@property(retain, nonatomic) UILabel* passwordLabel;
@property(retain, nonatomic) UILabel* usernameLabel;
@property(retain, nonatomic) UILabel* groupLabel;
@property(retain, nonatomic) UILabel* statusLabel;
@property(retain, nonatomic) UIView* settingsView;
@property(retain, nonatomic) UIButton* settingsButton;
@property(retain, nonatomic) UITextField* passwordField;
@property(retain, nonatomic) UITextField* usernameField;
@property(retain, nonatomic) UITextField* groupField;
@property(retain, nonatomic) UIButton* checkinButton;
@property(retain, nonatomic) UIButton* submitButton;
@property(retain, nonatomic) UIScrollView* checkinView;
@property(retain, nonatomic) UIScrollView* formView;
@property(retain, nonatomic) UIImageView* logoImageView;
@property(retain, nonatomic) UIImageView* deviceImageView;
@property(retain, nonatomic) UILabel* loadingLabel;
@property(retain, nonatomic) UIScrollView* loadingView;
@property(retain, nonatomic) AWAssetTracker* tracker;
@property(retain, nonatomic) NSString* defaultStatusLabelText;
@property(assign, nonatomic) BOOL showContinue;
-(void)adjustView:(int)view;
-(void)setupCheckinButton;
-(void)adjustLoadingElements;
-(void)setupBranding;
-(void)continueButtonPressed:(id)pressed;
-(void)settingsDidDismiss:(id)dismiss;
-(void)checkDeviceServicesURL:(id)url;
-(void)scrollToTextField:(id)textField;
-(void)didTapAnywhere:(id)anywhere;
-(void)keyboardWillShow:(id)keyboard;
-(void)keyboardWillHide:(id)keyboard;
-(void)removeStoredAccount;
-(void)createSessionWithStoredAccount;
-(void)storeAccount:(id)account;
-(void)createSessionWithUsername:(id)username password:(id)password group:(id)group;
-(void)showAlertWithTitle:(id)title message:(id)message;
-(CGSize)makeSizeForLabel:(id)label;
-(void)layoutFormView;
-(void)layoutViewForOrientation:(int)orientation animated:(BOOL)animated;
-(void)applyFadingView;
-(void)applyButtonGradients;
-(void)getStatus;
-(void)updateViewRetry;
-(void)updateViewLoading;
-(void)updateViewCheckedOut;
-(void)updateViewCheckedIn;
-(void)setState:(int)state;
-(BOOL)gestureRecognizer:(id)recognizer shouldReceiveTouch:(id)touch;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)retryButtonPressed:(id)pressed;
-(void)checkinButtonPressed:(id)pressed;
-(void)settingsButtonPressed:(id)pressed;
-(void)submitButtonPressed:(id)pressed;
-(void)textFieldDidBeginEditing:(id)textField;
-(BOOL)textFieldShouldReturn:(id)textField;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewDidUnload;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
-(void)dealloc;
@end

