/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSessionDelegate.h"
#import "AirWatch-Structs.h"
#import <UIKit/UIViewController.h>

@class AWHUDView, AWLogoView, UIImageView, AWUsernamePasswordGroupIDView, AWEnrollmentAccount;

__attribute__((visibility("hidden")))
@interface AssetTrackerViewControllerNew : UIViewController <AWSessionDelegate> {
	AWHUDView* _loadingHUDView;
	BOOL showGroup;
	BOOL _keyboardVisible;
	AWLogoView* _logoView;
	AWUsernamePasswordGroupIDView* _usernamePasswordGroupIDView;
	UIImageView* _bgImageView;
	UIImageView* _logoImageView;
	int _assetTrackerState;
	AWEnrollmentAccount* _account;
}
@property(retain, nonatomic) AWEnrollmentAccount* account;
@property(assign, nonatomic) int assetTrackerState;
@property(retain, nonatomic) UIImageView* logoImageView;
@property(retain, nonatomic) UIImageView* bgImageView;
@property(retain, nonatomic) AWUsernamePasswordGroupIDView* usernamePasswordGroupIDView;
@property(retain, nonatomic) AWLogoView* logoView;
@property(assign, nonatomic) BOOL keyboardVisible;
-(void)AWSession:(id)session failedToInvalidateTokenWithError:(id)error;
-(void)AWSessionDidInvalidate:(id)awsession;
-(void)AWSession:(id)session didFailWithError:(id)error;
-(void)AWSession:(id)session didRecieveToken:(id)token;
-(void)getHmacToken;
-(void)redirectToCheckOutView;
-(void)scrollToTextField:(id)textField andIsUP:(BOOL)up;
-(void)storeAccount;
-(void)removeStoredAccount;
-(CGRect)authenticationFieldFrame;
-(void)dismissModalViewWithCompletionBlock:(id)completionBlock;
-(void)resignFromActive;
-(void)setUsernamePlaceholderText:(id)text;
-(void)setUsernameWith:(id)with;
-(void)setBackgroundColor:(id)color;
-(void)setBackgroundImage:(id)image;
-(void)setLogoImage:(id)image;
-(void)selectFirstResponder;
-(id)groupIDTextField;
-(id)passwordTextField;
-(id)usernameTextField;
-(void)hideAuthenticatingHUDViewAndEndIgnoringInteractionEvents;
-(id)loadingHUDView;
-(void)keyboardWillHide:(id)keyboard;
-(void)keyboardWillShow:(id)keyboard;
-(void)setupBranding;
-(void)showAlertWithTitle:(id)title message:(id)message;
-(void)updateView;
-(void)setState:(int)state;
-(void)checkoutButtonTapped:(id)tapped;
-(void)handleRotation:(int)rotation;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)checkinButtonTapped:(id)tapped;
-(void)continueButtonTapped:(id)tapped;
-(void)setupUsernamePasswordGroupIDView;
-(void)setupLogoViewWithImage:(id)image;
-(float)yPositionForView:(id)view ForOrientation:(int)orientation;
-(float)xPositionForView:(id)view ForOrientation:(int)orientation;
-(void)didReceiveMemoryWarning;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(unsigned)supportedInterfaceOrientations;
-(void)checkedInOrOut:(id)orOut;
-(void)viewDidUnload;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)dealloc;
-(void)viewDidLoad;
-(id)initWithAuthenticationType:(int)authenticationType groupID:(id)anId userName:(id)name logoImage:(id)image andBackgroundImage:(id)image5;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

