/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWBottomViewDelegate.h"
#import "AirWatch-Structs.h"
#import "UITextFieldDelegate.h"
#import <UIKit/UITableViewController.h>

@class AWBottomView, UIColor, AWHUDView, UITapGestureRecognizer, UITextField;

__attribute__((visibility("hidden")))
@interface AuthorizationTokenViewController : UITableViewController <AWBottomViewDelegate, UITextFieldDelegate> {
	UITapGestureRecognizer* _tapRecognizer;
	BOOL _showTokendRequiredMessage;
	UIColor* backGroundColor;
	AWHUDView* loadingView;
	AWBottomView* _buttonView;
	UITextField* _tokenField;
}
@property(retain, nonatomic) UITextField* tokenField;
@property(retain, nonatomic) AWBottomView* buttonView;
-(void)cancelPressed;
-(void)changeFrameBasedOnOrientation;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(unsigned)supportedInterfaceOrientations;
-(void)tappedOutside:(id)outside;
-(void)keyboardWillHide:(id)keyboard;
-(void)keyboardWillShow:(id)keyboard;
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;
-(BOOL)textFieldShouldReturn:(id)textField;
-(void)sendRequest;
-(void)bottomView:(id)view didSelectBotton:(int)botton;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForFooterInSection:(int)section;
-(id)tableView:(id)view viewForFooterInSection:(int)section;
-(id)tableView:(id)view titleForHeaderInSection:(int)section;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)didReceiveMemoryWarning;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)dealloc;
-(id)initWithStyle:(int)style;
@end

