/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface AW_ReverseGeocoder : NSObject {
	NSString* _countryCode;
	NSString* _country;
	NSString* _state;
	NSString* _postalCode;
	NSString* _city;
}
@property(retain, nonatomic) NSString* city;
@property(retain, nonatomic) NSString* postalCode;
@property(retain, nonatomic) NSString* state;
@property(retain, nonatomic) NSString* country;
@property(retain, nonatomic) NSString* countryCode;
+(id)sharedInstance;
-(void)dealloc;
-(void)updateReverseGeocodedData;
-(BOOL)isHomeCountry;
@end

