/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "AWSOAPControllerDelegate.h"

@class NSURL, NSString, AWSOAPController, AWActiveDirectoryAccount;
@protocol AWActiveDirectoryAuthenticatorDelegate;

@interface AWActiveDirectoryAuthenticator : NSObject <AWSOAPControllerDelegate> {
	AWSOAPController* _soapHandler;
	AWActiveDirectoryAccount* _account;
	id _completionBlock;
	id<AWActiveDirectoryAuthenticatorDelegate> _delegate;
	NSString* _hostName;
	NSString* _endpointPath;
	NSURL* _actionURL;
	NSURL* _namespaceURL;
}
@property(retain, nonatomic) NSURL* namespaceURL;
@property(retain, nonatomic) NSURL* actionURL;
@property(copy, nonatomic) NSString* endpointPath;
@property(copy, nonatomic) NSString* hostName;
@property(assign, nonatomic) id<AWActiveDirectoryAuthenticatorDelegate> delegate;
-(void)soapController:(id)controller failedWithError:(id)error;
-(void)soapController:(id)controller didReceieveResponseInfo:(id)info;
-(void)authenticateAccount:(id)account completionBlock:(id)block;
-(void)authenticateAccount:(id)account;
-(void)dealloc;
@end

