/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWRedirectValidatorDelegate.h"
#import "UIAlertViewDelegate.h"
#import <UIKit/UIViewController.h>
#import "AWPingerDelegate.h"

@class AWHUDView, NSString, AWURLRedirectValidator, AWPinger, NSDictionary, NSURL;

__attribute__((visibility("hidden")))
@interface AWAgentConfigurationViewController : UIViewController <AWPingerDelegate, UIAlertViewDelegate, AWRedirectValidatorDelegate> {
	AWPinger* _pinger;
	AWHUDView* _hudView;
	BOOL _isConfigured;
	NSURL* _customAppURL;
	NSDictionary* _queryComponents;
	AWURLRedirectValidator* _validator;
	NSString* groupID;
	BOOL urlRedirected;
}
-(void)saveDeviceServiceURL;
-(void)validator:(id)validator urlRedirectResult:(int)result;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)getBrandingSettings;
-(void)launchGeneralHandler:(id)handler;
-(void)pingSuccessful:(id)successful withHost:(id)host withScheme:(int)scheme;
-(void)pingFailed:(id)failed withHost:(id)host withScheme:(int)scheme withError:(id)error;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewDidUnload;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)dealloc;
-(id)initWithLaunchURL:(id)launchURL query:(id)query;
@end

