/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "AWNetworkConnectionDelegate.h"

@class AgentSecureChannelHandler, AWSecureRequestWrapper;

__attribute__((visibility("hidden")))
@interface AWAgentAuthTokenHandler : NSObject <AWNetworkConnectionDelegate> {
	AWSecureRequestWrapper* _networkConnection;
	AgentSecureChannelHandler* _securechannnelHandler;
}
@property(retain, nonatomic) AgentSecureChannelHandler* securechannnelHandler;
-(id)payloadData;
-(void)networkConnectionCanceled:(id)canceled;
-(void)networkConnection:(id)connection failedWithError:(id)error;
-(void)networkConnection:(id)connection receivedResponseData:(id)data;
-(void)fetchToKenFromAPNS;
-(void)dealloc;
-(id)init;
@end

