/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class AWBeacon;

__attribute__((visibility("hidden")))
@interface AWAgentSDKHandler : NSObject {
	AWBeacon* _beacon;
}
@property(retain, nonatomic) AWBeacon* beacon;
+(id)sharedInstance;
-(void)configureBeacon;
-(void)sendBeacon;
-(void)stopAirWatchSDK;
-(void)startAirWatchSDK;
-(void)configureAirWatchSDK;
@end

