/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class AWApplicationAuthenticate;

@interface AWAgentAuthenticatorController : NSObject {
	id _callback;
	AWApplicationAuthenticate* _appAuth;
}
@property(retain, nonatomic) AWApplicationAuthenticate* appAuth;
+(id)sharedInstance;
-(BOOL)canUseAgent;
-(id)serverURL;
-(id)getUDIDString;
-(id)getHMACData;
-(BOOL)processURL:(id)url;
-(void)renewWithScheme:(id)scheme callback:(id)callback;
-(void)authenticateWithScheme:(id)scheme callback:(id)callback;
-(id)init;
@end

