/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BaseCommandHandler.h"


__attribute__((visibility("hidden")))
@interface AWAgentInstallCommandHandler : BaseCommandHandler {
}
+(void)installProfile:(id)profile;
+(void)handleCustomSettings:(id)settings;
+(void)setSharedDeviceSettingFromProfile:(id)profile;
+(BOOL)containsAgentSettings:(id)settings;
+(void)setSettingsFromProfile:(id)profile;
+(void)installAgentSettingsFromProfile:(id)profile;
-(BOOL)handleCommand:(id)command;
@end

