/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


@interface AWAirwatchLocalizationBundle : NSObject {
}
+(id)getAWAirwatchLocalizedStringForKey:(id)key withComment:(id)comment;
+(id)AWAirwatchLocalizationBundle;
@end

