/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWDataSamplerTransmitterDelegate.h"
#import <Foundation/NSObject.h>

@class NSString;

@interface AWAnalytics : NSObject <AWDataSamplerTransmitterDelegate> {
	unsigned bgTask;
	BOOL _enabled;
	NSString* _sessionUUID;
	NSString* bundleVersion;
	NSString* bundleName;
}
@property(retain, nonatomic) NSString* sessionUUID;
@property(retain, nonatomic) NSString* bundleName;
@property(retain, nonatomic) NSString* bundleVersion;
@property(assign, nonatomic) BOOL enabled;
+(id)getUUID;
+(id)mAnalytics;
-(void)registerAppSessionEnd;
-(void)registerAppSessionStart;
-(void)applicationDidBecomeActiveNotification:(id)application;
-(void)applicationDidEnterBackgroundNotification:(id)application;
-(void)DataMessageSendFailed:(id)failed error:(id)error transmitter:(id)transmitter;
-(void)DataMessageSentSuccessfully:(id)successfully transmitter:(id)transmitter;
-(void)recordEvent:(int)event eventName:(id)name eventValue:(id)value valueType:(int)type;
-(id)init;
@end

