/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


@interface AWAnchorHelper : NSObject {
}
+(void)checkAgentEnrollmentWithCompletion:(id)completion;
+(void)checkWorkspaceEnrollmentWithCompletion:(id)completion;
+(void)checkEnrollmentWithCompletion:(id)completion;
@end

