/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIResponder.h>
#import "AirWatch-Structs.h"
#import "UIApplicationDelegate.h"

@class UIWindow, AWCrashLogReporter;
@protocol AWAuthenticationHandlerDelegate;

@interface AWApplicationDelegate : UIResponder <UIApplicationDelegate> {
	BOOL _shouldEnableAnalytics;
	id<AWAuthenticationHandlerDelegate> _authenticationHandlerDelegate;
	AWCrashLogReporter* _crashReporter;
}
@property(retain, nonatomic) UIWindow* window;
@property(retain, nonatomic) AWCrashLogReporter* crashReporter;
@property(assign, nonatomic) id<AWAuthenticationHandlerDelegate> authenticationHandlerDelegate;
@property(assign, nonatomic) BOOL shouldEnableAnalytics;
-(void)setupCrashReporter;
-(void)application:(id)application didReceiveRemoteNotification:(id)notification;
-(void)application:(id)application willChangeStatusBarOrientation:(int)orientation duration:(double)duration;
-(void)application:(id)application didChangeStatusBarOrientation:(int)orientation;
-(void)applicationProtectedDataDidBecomeAvailable:(id)applicationProtectedData;
-(void)applicationProtectedDataWillBecomeUnavailable:(id)applicationProtectedData;
-(void)applicationWillTerminate:(id)application;
-(void)applicationWillResignActive:(id)application;
-(void)applicationDidEnterBackground:(id)application;
-(void)applicationWillEnterForeground:(id)application;
-(void)applicationDidBecomeActive:(id)application;
-(BOOL)application:(id)application openURL:(id)url sourceApplication:(id)application3 annotation:(id)annotation;
-(BOOL)application:(id)application didFinishLaunchingWithOptions:(id)options;
-(BOOL)application:(id)application willFinishLaunchingWithOptions:(id)options;
-(void)dealloc;
@end

