/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSOperationQueue;

@interface AWAppCatalog : NSObject {
	NSOperationQueue* _networkingOperationQueue;
}
-(void)fetchIconForApplication:(id)application withCompletion:(id)completion;
-(void)fetchInfoForApplication:(id)application withCompletion:(id)completion;
-(void)fetchApplicationUpdatesWithCompletion:(id)completion;
-(void)fetchBlacklistedApplicationsWithCompletion:(id)completion;
-(void)fetchPublicApplicationsWithCompletion:(id)completion;
-(void)fetchInternalApplicationsWithCompletion:(id)completion;
-(void)mergeApplication:(id)application intoTarget:(id)target;
-(id)requestOperationForURL:(id)url method:(id)method;
-(id)appCatalogServiceMainUrlText:(id)text withAttributes:(id)attributes;
-(id)appCatalogDownloadIconUrlTextFor:(id)aFor;
-(id)init;
@end

