/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSessionDelegate.h"
#import <UIKit/UITableViewController.h>
#import "UIAlertViewDelegate.h"

@class NSTimer, AWHUDView, AWAgentAuthTokenHandler, AWAPPCommAuthenticate, NSString, NSError, NSURL;

__attribute__((visibility("hidden")))
@interface AWAppCommViewController : UITableViewController <AWSessionDelegate, UIAlertViewDelegate> {
	BOOL _retry;
	BOOL _enrolled;
	NSTimer* tokenFetchtimer;
	BOOL ignoreHMACNotification;
	id _handler;
	id _registerHandler;
	NSString* _requester;
	NSString* _requesterIdentifier;
	NSString* _username;
	NSString* _group;
	NSURL* _url;
	AWAPPCommAuthenticate* _appComm;
	AWHUDView* _loadingView;
	AWAgentAuthTokenHandler* _authtokenHandler;
	NSError* _currentError;
}
@property(retain, nonatomic) NSError* currentError;
@property(retain, nonatomic) AWAgentAuthTokenHandler* authtokenHandler;
@property(retain, nonatomic) AWHUDView* loadingView;
@property(assign, nonatomic) BOOL enrolled;
@property(retain, nonatomic) AWAPPCommAuthenticate* appComm;
@property(retain, nonatomic) NSURL* url;
@property(copy, nonatomic) NSString* group;
@property(copy, nonatomic) NSString* username;
@property(copy, nonatomic) NSString* requesterIdentifier;
@property(copy, nonatomic) NSString* requester;
@property(copy, nonatomic) id registerHandler;
@property(retain, nonatomic) id handler;
-(void)fetchTokenFromAPNS;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)showPushNotificationAlert;
-(void)dismiss:(id)dismiss;
-(void)AWSession:(id)session failedToInvalidateTokenWithError:(id)error;
-(void)AWSessionDidInvalidate:(id)awsession;
-(void)AWSession:(id)session didRecieveToken:(id)token;
-(void)showErrorAlert:(id)alert;
-(void)AWSession:(id)session didFailWithError:(id)error;
-(void)fetchToken;
-(void)fetchTokenWithHMAC:(id)hmac;
-(void)PresentPasscodeView;
-(void)checkAndFetchToken;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidUnload;
-(void)viewDidLoad;
-(void)dealloc;
-(id)initWithStyle:(int)style;
@end

