/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


@interface AWApplicationList : NSObject {
}
+(void)updateVersion:(id)version;
+(BOOL)updateAppImage:(id)image;
+(id)getListFromMemory;
+(void)cacheApplicationList;
+(void)saveListInMemory;
+(id)getWebApps;
+(id)getPurchasedApps;
+(id)getPublicApps;
+(id)getInternalApps;
+(id)getApplicationList;
+(BOOL)saveApplicationList:(id)list typeUpdate:(BOOL)update;
@end

