/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString;

@interface AWasymEncryptor : NSObject {
	NSString* _publicKeyID;
	NSString* _privateKeyID;
}
@property(copy, nonatomic) NSString* privateKeyID;
@property(copy, nonatomic) NSString* publicKeyID;
-(id)privateQueryDict;
-(id)publicQueryDict;
-(void)decryptWithPrivateKey;
-(void)encryptWithPublicKey;
-(void)KeysPlease;
-(id)decryptData:(id)data;
-(id)encryptData:(id)data;
-(id)initWithPublicIdentifier:(id)publicIdentifier PrivateIdentifier:(id)identifier;
-(id)init;
@end

