/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWProfilePayload.h"

@class NSDictionary, NSString, NSArray;

@interface AWAuthenticationPayload : AWProfilePayload {
	BOOL _enableSingleSignOn;
	BOOL _allowSingleSignOn;
	BOOL _allowSamePasscodeAllApp;
	BOOL _requirePasscode;
	BOOL _allowSimple;
	BOOL _enableIntegratedAuthentication;
	BOOL _isV2;
	int _authenticationMethod;
	int _passcodeComplexity;
	NSArray* _actionsTakenOnMaxFailedAttempt;
	int _minimumPasscodeLength;
	int _minimumComplexCharacters;
	int _passcodeHistory;
	int _maximumFailedAttempts;
	int _autoLockMinute;
	int _passcodeMode;
	int _passcodeTimeout;
	int _actionOnMaxFailedAttempts;
	NSString* _policyId;
	NSArray* _allowedSites;
	NSDictionary* _payloadDictionary;
	double _gracePeriod;
	double _maximumPasscodeAge;
}
@property(assign, nonatomic) BOOL isV2;
@property(readonly, assign, nonatomic) NSDictionary* payloadDictionary;
@property(readonly, assign, nonatomic) NSArray* allowedSites;
@property(readonly, assign, nonatomic) BOOL enableIntegratedAuthentication;
@property(readonly, assign, nonatomic) NSString* policyId;
@property(readonly, assign, nonatomic) int actionOnMaxFailedAttempts;
@property(readonly, assign, nonatomic) int passcodeTimeout;
@property(readonly, assign, nonatomic) BOOL allowSimple;
@property(readonly, assign, nonatomic) int passcodeMode;
@property(readonly, assign, nonatomic) BOOL enableSingleSignOn;
@property(readonly, assign, nonatomic) BOOL requirePasscode;
@property(readonly, assign, nonatomic) BOOL allowSamePasscodeAllApp;
@property(readonly, assign, nonatomic) int autoLockMinute;
@property(readonly, assign, nonatomic) NSArray* actionsTakenOnMaxFailedAttempt;
@property(readonly, assign, nonatomic) int maximumFailedAttempts;
@property(readonly, assign, nonatomic) BOOL allowSingleSignOn;
@property(readonly, assign, nonatomic) double gracePeriod;
@property(readonly, assign, nonatomic) int passcodeHistory;
@property(readonly, assign, nonatomic) double maximumPasscodeAge;
@property(readonly, assign, nonatomic) int minimumComplexCharacters;
@property(readonly, assign, nonatomic) int minimumPasscodeLength;
@property(readonly, assign, nonatomic) int passcodeComplexity;
@property(readonly, assign, nonatomic) int authenticationMethod;
+(id)payloadTypeV2;
+(id)payloadType;
-(id)parseActions:(id)actions;
-(id)initWithDictionary:(id)dictionary;
-(void)dealloc;
@end

