/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITextFieldDelegate.h"
#import "AirWatch-Structs.h"
#import <UIKit/UIViewController.h>

@class UILabel, UIButton, UIScrollView, UIView, NSURLAuthenticationChallenge, NSOperation, NSData, AWEnrollmentAccount, AWAuthenticationCredentialsView, AWLinearGradientView;

@interface AWAuthenticationChallengeViewController : UIViewController <UITextFieldDelegate> {
	UIButton* _dismissButton;
	UIButton* _submitButton;
	UILabel* _titleLabel;
	UILabel* _realmLabel;
	UILabel* _filenameLable;
	UIView* _buttonsContainer;
	UIScrollView* _scrollView;
	NSOperation* _networkOperation;
	BOOL _shouldPersistCredentialsInKeychain;
	AWAuthenticationCredentialsView* _authView;
	AWLinearGradientView* _linearGradientView;
	NSURLAuthenticationChallenge* _challenge;
	AWEnrollmentAccount* _authenticatedEnrollmentAccount;
	NSData* _encryptionKey;
	id _completionBlock;
}
@property(copy, nonatomic) id completionBlock;
@property(assign) BOOL shouldPersistCredentialsInKeychain;
@property(retain, nonatomic) NSData* encryptionKey;
@property(retain, nonatomic) AWEnrollmentAccount* authenticatedEnrollmentAccount;
@property(retain, nonatomic) NSURLAuthenticationChallenge* challenge;
@property(retain, nonatomic) NSOperation* networkOperation;
@property(retain, nonatomic) AWAuthenticationCredentialsView* authView;
@property(retain, nonatomic) AWLinearGradientView* linearGradientView;
@property(retain, nonatomic) UIScrollView* scrollView;
@property(retain, nonatomic) UIView* buttonsContainer;
@property(retain, nonatomic) UILabel* filenameLabel;
@property(retain, nonatomic) UILabel* realmLabel;
@property(retain, nonatomic) UILabel* titleLabel;
@property(retain, nonatomic) UIButton* submitButton;
@property(retain, nonatomic) UIButton* dismissButton;
-(void)saveCredentialsToKeychain:(id)keychain;
-(void)keyboardWillHideNotification:(id)keyboard;
-(void)keyboardWillShowNotification:(id)keyboard;
-(BOOL)textFieldShouldReturn:(id)textField;
-(void)submitCredentials:(id)credentials;
-(void)dismissModal:(id)modal;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewWillLayoutSubviews;
-(void)viewDidLoad;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
-(id)initWithNetworkOperation:(id)networkOperation authenticationChallenge:(id)challenge;
-(id)init;
-(void)dealloc;
@end

