/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString, NSURL, NSArray;

@interface AWAutoDiscover : NSObject {
	NSArray* _siteList;
	NSURL* autoDiscoverURL;
	NSString* autoDiscoverVersion;
	NSString* _deviceID;
}
@property(retain, nonatomic) NSString* deviceID;
@property(retain, nonatomic) NSArray* siteList;
@property(copy, nonatomic) NSString* autoDiscoverVersion;
@property(retain, nonatomic) NSURL* autoDiscoverURL;
-(BOOL)isResponseDataValid:(id)valid;
-(id)processedError:(id)error forResponse:(id)response;
-(id)discoverURLDomainLookup:(id)lookup domain:(id)domain error:(id*)error;
-(id)discoverURLV1:(id)a1 error:(id*)error;
-(id)discoverURLV2:(id)a2 error:(id*)error;
-(id)pathComponentForTypes:(id)types;
-(id)hmacKey;
-(id)hmac:(id)hmac forMessage:(id)message;
-(void)dealloc;
-(void)discoverURLUsingDomain:(id)domain withCompletionBlock:(id)completionBlock;
-(void)discoverURLSWithCompletion:(id)completion block:(id)block;
-(void)discoverURLWithCompletion:(id)completion;
@end

