/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIViewController.h>
#import "UIAlertViewDelegate.h"
#import "AirWatch-Structs.h"

@class AWCredentialView, UIImageView, AWSDK, AWHUDView, AWCredentialSelectionView, AWAuthorizeTokenView, AWLogoView, AWEnrollmentAccount, AWReachability, AWUsernamePasswordView;
@protocol AWAuthenticationViewControllerDelegate;

@interface AWAuthenticationViewController : UIViewController <UIAlertViewDelegate> {
	AWHUDView* _loadingHUDView;
	AWReachability* _reach;
	BOOL _keyboardVisible;
	BOOL _showOfflineButton;
	BOOL _shouldEnableAlternateLogin;
	BOOL _isSelectingCredential;
	id<AWAuthenticationViewControllerDelegate> _delegate;
	int _authenticationType;
	AWLogoView* _logoView;
	AWCredentialView* _credentialView;
	AWUsernamePasswordView* _usernamePasswordView;
	AWAuthorizeTokenView* _authorizeTokenView;
	UIImageView* _bgImageView;
	UIImageView* _logoImageView;
	AWEnrollmentAccount* _enrollmentAccount;
	AWCredentialSelectionView* _credentialSelectionView;
	AWSDK* _airwatchSDK;
}
@property(retain, nonatomic) UIImageView* logoImageView;
@property(retain, nonatomic) UIImageView* bgImageView;
@property(retain, nonatomic) AWSDK* airwatchSDK;
@property(retain, nonatomic) AWCredentialSelectionView* credentialSelectionView;
@property(retain, nonatomic) AWAuthorizeTokenView* authorizeTokenView;
@property(retain, nonatomic) AWUsernamePasswordView* usernamePasswordView;
@property(retain, nonatomic) AWCredentialView* credentialView;
@property(retain, nonatomic) AWLogoView* logoView;
@property(assign, nonatomic) int authenticationType;
@property(assign, nonatomic) BOOL shouldEnableAlternateLogin;
@property(assign, nonatomic) BOOL isSelectingCredential;
@property(assign, nonatomic) BOOL showOfflineButton;
@property(assign, nonatomic) BOOL keyboardVisible;
@property(assign, nonatomic) id<AWAuthenticationViewControllerDelegate> delegate;
@property(retain, nonatomic) AWEnrollmentAccount* enrollmentAccount;
-(CGRect)authenticationFieldFrame;
-(void)applyBrandingSettings;
-(void)setupBranding;
-(void)hideAuthenticatingHUDViewAndEndIgnoringInteractionEvents;
-(void)serverSetUpDone:(id)done;
-(void)selectAuthenticationView;
-(BOOL)requiredFieldsArePopulatedFor:(id)aFor;
-(void)dismissModalViewWithCompletionBlock:(id)completionBlock;
-(void)authenticateAccount:(id)account;
-(void)resignFromActive;
-(void)setBackgroundColor:(id)color;
-(void)setBackgroundImage:(id)image;
-(void)setLogoImage:(id)image;
-(void)selectFirstResponder;
-(void)setUsernamePlaceholderText:(id)text;
-(void)setUsernameWith:(id)with;
-(id)authorizationTokenTextField;
-(id)passwordTextField;
-(id)usernameTextField;
-(id)settingButton;
-(id)offlineButton;
-(id)loginButton;
-(id)loadingHUDView;
-(void)toggleCredentialSelection;
-(void)loginButtonTapped:(id)tapped;
-(void)settingButtonTapped:(id)tapped;
-(void)toggleOfflineButton;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)keyboardWillHide:(id)keyboard;
-(void)keyboardWillShow:(id)keyboard;
-(void)toggleWorkOflineButtonVisibility:(BOOL)visibility;
-(void)toggleCredentialSelectionButtonVisibility:(BOOL)visibility;
-(void)hideSettingsGear;
-(void)handleRotation:(int)rotation;
-(void)setupCredentialView;
-(void)setupLogoViewWithImage:(id)image;
-(void)setupViews;
-(float)yPositionForView:(id)view ForOrientation:(int)orientation;
-(float)xPositionForView:(id)view ForOrientation:(int)orientation;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(unsigned)supportedInterfaceOrientations;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(id)initWithAuthenticationType:(int)authenticationType groupID:(id)anId userName:(id)name withWorkOffLineButton:(BOOL)workOffLineButton logoImage:(id)image andBackgroundImage:(id)image6;
-(void)didReceiveMemoryWarning;
-(void)dealloc;
@end

