/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "AWNetworkConnectionDelegate.h"

@class NSMutableData, NSData, NSString, NSURL;
@protocol AWBaseMessageDelegate;

@interface AWBaseMessage : NSObject <AWNetworkConnectionDelegate> {
	NSMutableData* _responseDataBuffer;
	BOOL _isTransmitting;
	BOOL _requiresDecryption;
	NSURL* _url;
	NSString* _contentType;
	NSString* _method;
	NSData* _bodyData;
	id<AWBaseMessageDelegate> _delegate;
}
@property(assign, nonatomic) id<AWBaseMessageDelegate> delegate;
@property(retain, nonatomic) NSData* bodyData;
@property(copy, nonatomic) NSString* method;
@property(copy, nonatomic) NSString* contentType;
@property(retain, nonatomic) NSURL* url;
-(BOOL)isDecryptionRequired:(id)required;
-(id)decryptResponseData;
-(void)networkConnection:(id)connection receivedResponseData:(id)data;
-(void)networkConnection:(id)connection failedWithError:(id)error;
-(void)connectionDidFinishLoading:(id)connection;
-(void)connection:(id)connection didReceiveData:(id)data;
-(void)connection:(id)connection didReceiveResponse:(id)response;
-(void)connection:(id)connection didFailWithError:(id)error;
-(id)sendSynchronousRequestToURL:(id)url;
-(id)sendSynchronousRequest;
-(void)sendToURL:(id)url;
-(void)send;
-(void)dealloc;
-(id)init;
@end

