/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "AWBeaconTransmitterDelegate.h"

@class NSString, NSTimer;

@interface AWBeacon : NSObject <AWBeaconTransmitterDelegate> {
	NSString* _APNSToken;
	NSString* _bundleIdentifier;
	NSString* _checkInAction;
	NSString* _emailAddress;
	NSString* _groupCode;
	NSString* _phoneNumber;
	NSTimer* _transmitTimer;
	int _locationMode;
	double _transmitInterval;
	double _locationDistanceFilter;
	double _locationDesiredAccuracy;
}
@property(copy, nonatomic) NSString* checkInAction;
@property(retain, nonatomic) NSTimer* transmitTimer;
@property(assign, nonatomic) double locationDesiredAccuracy;
@property(assign, nonatomic) double locationDistanceFilter;
@property(assign, nonatomic) int locationMode;
@property(assign, nonatomic) double transmitInterval;
@property(copy, nonatomic) NSString* phoneNumber;
@property(copy, nonatomic) NSString* groupCode;
@property(copy, nonatomic) NSString* emailAddress;
@property(copy, nonatomic) NSString* bundleIdentifier;
@property(copy, nonatomic) NSString* APNSToken;
+(BOOL)send:(id*)send;
+(BOOL)shutDown:(id*)down;
+(BOOL)startUpWithConfiguration:(id)configuration error:(id*)error;
+(id)lastSuccessfulBeaconTimeStamp;
-(void)beaconTransmitter:(id)transmitter succeededWithRepsonseData:(id)repsonseData;
-(void)beaconTransmitter:(id)transmitter failedWithError:(id)error;
-(void)beaconTimeStamp:(BOOL)stamp;
-(void)beaconShouldSendGPS:(id)beacon;
-(void)locationServiceDidReceiveDeviceLocation:(id)locationService;
-(id)description;
-(void)send;
-(void)sendPayload:(id)payload;
-(void)beaconTimerTicked:(id)ticked;
-(void)stop;
-(void)start;
-(void)dealloc;
-(id)initWithAPNSToken:(id)apnstoken transmitInterval:(double)interval locationGroup:(id)group locationMode:(int)mode distance:(double)distance;
@end

