/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


@interface AWBinaryStorageHelper : NSObject {
}
+(id)getFilePathWithFileName:(id)fileName;
-(void)clearBinary:(id)binary;
-(void)clearAll;
-(void)storeBinary:(id)binary toFileName:(id)fileName;
-(id)getBinary:(id)binary;
@end

