/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "AWBrandingImageFetchDelegate.h"

@class NSDictionary, AWBrandingPayload, NSBundle, UIFont;

@interface AWBranding : NSObject <AWBrandingImageFetchDelegate> {
	BOOL _useCustomBrandingBundle;
	NSDictionary* _brandingInfo;
	NSBundle* _sourceBrandingBundle;
	UIFont* _font;
	AWBrandingPayload* _brandingPayload;
}
@property(assign) BOOL useCustomBrandingBundle;
@property(retain, nonatomic) AWBrandingPayload* brandingPayload;
@property(retain, nonatomic) NSDictionary* brandingInfo;
@property(retain, nonatomic) UIFont* font;
@property(retain, nonatomic) NSBundle* sourceBrandingBundle;
+(void)synchronizeBrandingFromPayload:(id)payload;
+(id)sharedBranding;
-(void)clearAllBrandingImages;
-(void)brandingImageFetch:(id)fetch succeededWithData:(id)data;
-(void)brandingImageFetch:(id)fetch failedWithError:(id)error;
-(void)writeUrlInfo:(id)info;
-(id)lastFetchedUrl;
-(void)handleNonColorSetting:(id)setting skinDictionary:(id)dictionary;
-(id)bundleSkinFilePath;
-(id)customSkinFilePath;
-(id)customBrandingFolderPath;
-(void)fetchV2Images:(id)images key:(id)key;
-(void)handleImageSettings:(id)settings skinDictionary:(id)dictionary;
-(void)synchronizeBrandingFormPayload:(id)payload;
-(void)parseBrandingInfoFromCommand:(id)command;
-(id)getSecondaryImage;
-(id)getPrimaryImage;
-(id)getLogoImage;
-(id)getBackgroundImage;
-(id)getColorForKey:(id)key;
-(id)getLoginTitleColor;
-(id)getSettingIconColor;
-(id)getSettingTitleBarColor;
-(id)getTertiaryText;
-(id)getSecondaryText;
-(id)getPrimaryText;
-(id)getTertiaryColor;
-(id)getSecondaryColor;
-(id)getPrimaryColor;
-(id)getTitle;
-(id)getBrandingDictionary;
-(BOOL)customBrandingEnabled;
-(BOOL)enablePoweredBy;
-(BOOL)useSecondaryImage;
-(BOOL)usePrimaryImage;
-(id)secondaryImage;
-(id)primaryImage;
-(id)textColor;
-(id)toolbarTextColor;
-(id)toolbarColor2;
-(id)backgroundColor;
-(id)settingsIconColor;
-(id)settingsTitleBarColor;
-(id)tertiaryTextColor;
-(id)secondaryTextColor;
-(id)primaryTextColor;
-(id)toolbarColor;
-(id)tertiaryColor;
-(id)secondaryColor;
-(id)primaryColor;
-(id)loginTitleColor;
-(id)organizationName;
-(id)title;
-(void)dealloc;
-(id)init;
@end

