/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWProfilePayload.h"

@class UIColor, NSString, NSURL, NSNumberFormatter;

@interface AWBrandingPayload : AWProfilePayload {
	BOOL isV2;
	BOOL _enableBranding;
	BOOL _customBranding;
	NSString* _organizationName;
	UIColor* _primaryHighlightColor;
	UIColor* _primaryColor;
	UIColor* _secondaryHighlightColor;
	UIColor* _secondaryColor;
	UIColor* _toolbarColor;
	UIColor* _primaryTextColor;
	UIColor* _secondaryTextColor;
	UIColor* _loginTitleTextColor;
	UIColor* _tertiaryTextColor;
	UIColor* _toolbarTextColor;
	NSURL* _iPhoneBackgroundImageURL;
	NSURL* _iPhone2xBackgroundImageURL;
	NSURL* _iPhone52xBackgroundImageURL;
	NSURL* _iPadBackgroundImageURL;
	NSURL* _iPad2xBackgroundImageURL;
	NSURL* _iPhoneCompanyLogoURL;
	NSURL* _iPhone2xCompanyLogoURL;
	NSURL* _iPadCompanyLogoURL;
	NSURL* _iPad2xCompanyLogoURL;
	NSNumberFormatter* _numFormatter;
}
@property(retain) NSNumberFormatter* numFormatter;
@property(readonly, assign, nonatomic) NSURL* iPad2xCompanyLogoURL;
@property(readonly, assign, nonatomic) NSURL* iPadCompanyLogoURL;
@property(readonly, assign, nonatomic) NSURL* iPhone2xCompanyLogoURL;
@property(readonly, assign, nonatomic) NSURL* iPhoneCompanyLogoURL;
@property(readonly, assign, nonatomic) NSURL* iPad2xBackgroundImageURL;
@property(readonly, assign, nonatomic) NSURL* iPadBackgroundImageURL;
@property(readonly, assign, nonatomic) NSURL* iPhone52xBackgroundImageURL;
@property(readonly, assign, nonatomic) NSURL* iPhone2xBackgroundImageURL;
@property(readonly, assign, nonatomic) NSURL* iPhoneBackgroundImageURL;
@property(readonly, assign, nonatomic) UIColor* toolbarTextColor;
@property(readonly, assign, nonatomic) UIColor* tertiaryTextColor;
@property(readonly, assign, nonatomic) UIColor* loginTitleTextColor;
@property(readonly, assign, nonatomic) UIColor* secondaryTextColor;
@property(readonly, assign, nonatomic) UIColor* primaryTextColor;
@property(readonly, assign, nonatomic) UIColor* toolbarColor;
@property(readonly, assign, nonatomic) UIColor* secondaryColor;
@property(readonly, assign, nonatomic) UIColor* secondaryHighlightColor;
@property(readonly, assign, nonatomic) UIColor* primaryColor;
@property(readonly, assign, nonatomic) UIColor* primaryHighlightColor;
@property(readonly, assign, nonatomic) NSString* organizationName;
@property(readonly, assign, nonatomic) BOOL customBranding;
@property(readonly, assign, nonatomic) BOOL enableBranding;
+(id)payloadTypeV2;
+(id)payloadType;
-(void)dealloc;
-(id)iphoneSecondaryImage2xKey;
-(id)iphoneSecondaryImageKey;
-(id)ipadSecondaryImage2xKey;
-(id)ipadSecondaryImageKey;
-(id)iphone5BackgroundImage2xKey;
-(id)iphoneBackgroundImage2xKey;
-(id)iphoneBackgroundImageKey;
-(id)ipadBackgroundImage2xKey;
-(id)ipadBackgroundImageKey;
-(id)toolBarTextColorKey;
-(id)loginTitleTextColorKey;
-(id)tertiaryTextColorKey;
-(id)secondaryTextColorKey;
-(id)primaryTextColorKey;
-(id)toolbarColorKey;
-(id)secondaryColorKey;
-(id)primaryColorKey;
-(void)parseSecondaryImages:(id)images;
-(void)parseBackgroundImages:(id)images;
-(void)parseTextColors:(id)colors;
-(void)parseColors:(id)colors;
-(id)colorFromDictionary:(id)dictionary forKey:(id)key;
-(id)initWithDictionary:(id)dictionary;
@end

