/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSData, NSString, AWEncryptedFileHeader;
@protocol AWBufferedEncryptorDelegate;

@interface AWBufferedEncryptor : NSObject {
	BOOL isValid;
	unsigned long long progress;
	BOOL _isRunning;
	BOOL _decryptInMemory;
	unsigned short _algorithm;
	id<AWBufferedEncryptorDelegate> _delegate;
	id _context;
	NSString* _source;
	NSString* _destination;
	NSData* _initializationVector;
	AWEncryptedFileHeader* _header;
	NSData* _key;
}
@property(assign, nonatomic) BOOL decryptInMemory;
@property(retain, nonatomic) AWEncryptedFileHeader* header;
@property(assign) BOOL isRunning;
@property(copy, nonatomic) NSData* key;
@property(copy, nonatomic) NSString* destination;
@property(copy, nonatomic) NSString* source;
@property(retain, nonatomic) id context;
@property(retain, nonatomic) NSData* initializationVector;
@property(assign, nonatomic) unsigned short algorithm;
@property(assign) id<AWBufferedEncryptorDelegate> delegate;
+(BOOL)isValidKey:(id)key toDecryptFileAtPath:(id)path;
-(void)dealloc;
-(BOOL)cancelTasks;
-(void)startCryptoOperation:(unsigned short)operation;
-(void)decryptFileAtPath:(id)path toPath:(id)path2 withKey:(id)key;
-(void)encryptFileAtPath:(id)path toPath:(id)path2 withKey:(id)key;
-(id)initWithSourcePath:(id)sourcePath destinationPath:(id)path key:(id)key;
@end

