/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSMutableData;

@interface AWBuffer : NSObject {
	unsigned long _offset;
	unsigned long _chunkOffset;
	unsigned long _size;
	NSMutableData* _data;
}
@property(retain, nonatomic) NSMutableData* data;
@property(assign, nonatomic) unsigned long size;
@property(assign, nonatomic) unsigned long chunkOffset;
@property(assign, nonatomic) unsigned long offset;
-(void)clear;
-(void)initWithData:(id)data;
-(void)resetToOffset;
-(void)appendBytes:(const void*)bytes length:(unsigned long)length;
-(void)appendData:(id)data;
-(unsigned long)transferBytesWithLength:(unsigned long)length toBuffer:(void*)buffer;
-(id)dataWithLength:(unsigned)length;
-(void)setBytes:(char*)bytes length:(unsigned long)length;
-(void)dealloc;
-(id)init;
@end

