/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSMutableDictionary;

@interface AWCallLogManager : NSObject {
	NSMutableDictionary* _currentCallDetails;
	NSMutableDictionary* _currentCall;
	int _sampleInterval;
	int _transmitLimit;
}
+(id)sharedInstance;
-(id)callLogList;
-(void)transmitSuccess:(id)success;
-(id)transmitData;
-(void)addMinutesToLog:(id)log;
-(void)addLogToList:(id)list;
-(void)checkCurrentCall:(id)call;
-(void)checkCall;
-(void)dealloc;
-(void)stopCallCenterHandler;
-(void)initializeCallCenterHandler;
-(id)init;
@end

