/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import <Foundation/NSObject.h>

@class NSURLCredential, NSURLProtectionSpace;

@interface AWCachedURLCredentials : NSObject <NSCoding> {
	NSURLCredential* _credential;
	NSURLProtectionSpace* _protectionSpace;
}
@property(retain, nonatomic) NSURLProtectionSpace* protectionSpace;
@property(retain, nonatomic) NSURLCredential* credential;
-(id)init;
-(id)initWithCredential:(id)credential forProtectionSpace:(id)protectionSpace;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)dealloc;
@end

