/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWTableViewController.h"

@class UISegmentedControl, NSDictionary, NSArray, UIToolbar;

__attribute__((visibility("hidden")))
@interface AWCallsViewController : AWTableViewController {
	UIToolbar* _toolBar;
	NSArray* _filterToolBarButtons;
	UISegmentedControl* _callTypeFilterControl;
	NSArray* _recentAllCallLogs;
	NSArray* _recentInboundCallLogs;
	NSArray* _recentOutboundCallLogs;
	BOOL _isConfigured;
	NSDictionary* _recentCallLogs;
}
@property(retain, nonatomic) NSDictionary* recentCallLogs;
-(void)setupBranding;
-(id)cellImageForCallLog:(id)callLog;
-(id)callLogForIndexPath:(id)indexPath;
-(void)callTypeFilterValueChanged:(id)changed;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(id)tableView:(id)view titleForHeaderInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidUnload;
-(void)viewDidLoad;
-(void)didReceiveMemoryWarning;
-(void)dealloc;
-(id)initWithStyle:(int)style;
@end

