/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import "AWDataSamplerSample.h"

@class NSString;

@interface AWCallLog : AWDataSamplerSample <NSCoding> {
	NSString* _startTime;
	unsigned short _callStartyear;
	unsigned short _callStartmonth;
	unsigned short _callStartday;
	unsigned short _callStarthour;
	unsigned short _callStartminute;
	unsigned short _callStartsecond;
	unsigned short _callStartmillisecond;
	unsigned short _callDuration;
	unsigned short _callBits;
}
@property(assign, nonatomic) unsigned short callBits;
@property(assign, nonatomic) unsigned short callDuration;
@property(assign, nonatomic) unsigned short callStartmillisecond;
@property(assign, nonatomic) unsigned short callStartsecond;
@property(assign, nonatomic) unsigned short callStartminute;
@property(assign, nonatomic) unsigned short callStarthour;
@property(assign, nonatomic) unsigned short callStartday;
@property(assign, nonatomic) unsigned short callStartmonth;
@property(assign, nonatomic) unsigned short callStartyear;
@property(copy, nonatomic) NSString* startTime;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(id)data;
-(void)dealloc;
-(id)init;
@end

