/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWProfilePayload.h"

@class NSString, NSData;

@interface AWCertificatePayload : AWProfilePayload {
	NSData* _certificateData;
	NSString* _certificateName;
	NSString* _certificatePassword;
	NSString* _certificateThumbprint;
	NSString* _certificateType;
}
@property(readonly, assign, nonatomic) NSString* certificateType;
@property(readonly, assign, nonatomic) NSString* certificateThumbprint;
@property(readonly, assign, nonatomic) NSString* certificatePassword;
@property(readonly, assign, nonatomic) NSString* certificateName;
@property(readonly, assign, nonatomic) NSData* certificateData;
+(id)payloadTypeV2;
+(id)payloadType;
-(void)dealloc;
-(id)initWithDictionary:(id)dictionary;
@end

