/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>
#import "AirWatch-Structs.h"

@class UIScrollView;

@interface AWClipView : UIView {
	UIScrollView* _scrollView;
}
@property(retain, nonatomic) UIScrollView* scrollView;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
-(void)dealloc;
@end

