/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIWebViewDelegate.h"
#import <UIKit/UIViewController.h>

@class NSURL, NSMutableDictionary;

@interface AWClaimedAuthenticationViewController : UIViewController <UIWebViewDelegate> {
	NSURL* _o365Url;
	id _completionBlock;
	NSMutableDictionary* _cookieDict;
}
@property(retain, nonatomic) NSMutableDictionary* cookieDict;
@property(copy, nonatomic) id completionBlock;
@property(retain, nonatomic) NSURL* o365Url;
+(void)logOutOffice365;
+(void)removeOffice365Cookies;
+(BOOL)hasCookies;
-(void)webView:(id)view didFailLoadWithError:(id)error;
-(void)webViewDidFinishLoad:(id)webView;
-(BOOL)webView:(id)view shouldStartLoadWithRequest:(id)request navigationType:(int)type;
-(void)setupBranding;
-(unsigned)supportedInterfaceOrientations;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)dismissLogin;
-(void)cancelAuthentication;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)dealloc;
-(id)initWithOffice365Url:(id)office365Url andCompletion:(id)completion;
@end

