/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString, NSDate;

@interface AWConsoleLog : NSObject {
	NSDate* _logDate;
	NSString* _logDescription;
	NSString* _logLevel;
}
@property(copy, nonatomic) NSString* logLevel;
@property(copy, nonatomic) NSString* logDescription;
@property(retain, nonatomic) NSDate* logDate;
-(void)dealloc;
@end

