/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString;

@interface AWCommandResponse : NSObject {
	int _status;
	NSString* _payloadIdentifier;
	id _responseContent;
	unsigned _contentType;
	NSString* _commandTarget;
}
@property(assign, nonatomic) unsigned contentType;
@property(retain, nonatomic) id responseContent;
@property(copy, nonatomic) NSString* commandTarget;
@property(copy, nonatomic) NSString* payloadIdentifier;
@property(assign, nonatomic) int status;
+(id)unknownResponseForCommand:(id)command;
+(id)notnowResponseForCommand:(id)command;
+(id)idleResponseForCommand:(id)command;
+(id)commandFormatErrorResponseForCommand:(id)command;
+(id)errorResponseForCommand:(id)command;
+(id)acknowledgeResponseForCommand:(id)command contentType:(unsigned)type responseContent:(id)content;
+(id)acknowledgeResponseForCommand:(id)command;
-(id)keyForContentType:(unsigned)contentType;
-(id)payload;
-(void)dealloc;
-(id)init;
@end

