/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSDate, NSURL, NSString;

@interface AWContentFolder : NSObject {
	unsigned long permissionsBitMask;
	BOOL _isPrivate;
	BOOL _isShared;
	int _identifier;
	NSString* _name;
	int _parent;
	NSURL* _href;
	int _type;
	NSString* _createdBy;
	NSString* _modifiedBy;
	NSDate* _createdOn;
	NSDate* _modifiedOn;
	int _ownerUserID;
}
@property(assign, nonatomic) int ownerUserID;
@property(assign, nonatomic) BOOL isShared;
@property(readonly, assign, nonatomic) BOOL hasShareWritePermission;
@property(readonly, assign, nonatomic) BOOL hasShareReadPermission;
@property(readonly, assign, nonatomic) BOOL hasDeletePermission;
@property(readonly, assign, nonatomic) BOOL hasWritePermission;
@property(readonly, assign, nonatomic) BOOL hasReadPermission;
@property(copy, nonatomic) NSDate* modifiedOn;
@property(copy, nonatomic) NSDate* createdOn;
@property(copy, nonatomic) NSString* modifiedBy;
@property(copy, nonatomic) NSString* createdBy;
@property(assign, nonatomic) int type;
@property(assign, nonatomic) BOOL isPrivate;
@property(copy, nonatomic) NSURL* href;
@property(assign, nonatomic) int parent;
@property(copy, nonatomic) NSString* name;
@property(assign, nonatomic) int identifier;
-(id)init;
-(void)dealloc;
-(unsigned long)permissionsBitMask;
-(void)setPermissionsBitMask:(unsigned long)mask;
@end

