/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITableViewDelegate.h"
#import "AWBottomViewDelegate.h"
#import "AirWatch-Structs.h"
#import <UIKit/UITableViewController.h>
#import "UITableViewDataSource.h"

@class AWUserAccount, AWBottomView, NSDateFormatter;

__attribute__((visibility("hidden")))
@interface AWComplianceAlertViewController : UITableViewController <UITableViewDelegate, UITableViewDataSource, AWBottomViewDelegate> {
	AWBottomView* buttonView;
	AWUserAccount* _userAccount;
	id _complianceAlertBlock;
	NSDateFormatter* _dateFormatter;
}
@property(retain, nonatomic) NSDateFormatter* dateFormatter;
@property(copy, nonatomic) id complianceAlertBlock;
@property(retain, nonatomic) AWUserAccount* userAccount;
-(void)bottomView:(id)view didSelectBotton:(int)botton;
-(id)reasonText;
-(id)detailText;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(float)tableView:(id)view heightForFooterInSection:(int)section;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)dealloc;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

