/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString;
@protocol AWCompromiseDetectionDelegate;

@interface AWCompromiseDetection : NSObject {
	NSString* _deviceServicesPath;
	id<AWCompromiseDetectionDelegate> _delegate;
}
@property(copy, nonatomic) NSString* deviceServicesPath;
@property(retain, nonatomic) id<AWCompromiseDetectionDelegate> delegate;
+(int)jailBrokenStatus;
-(int)deviceConnectionStatus;
-(void)detectCompromiseStatus;
-(id)initWithDeviceServicesPath:(id)deviceServicesPath;
-(void)dealloc;
@end

