/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSDictionary, NSString;

@interface AWCommand : NSObject {
	NSString* _UUID;
	NSDictionary* _commandInfo;
	int _type;
}
@property(assign, nonatomic) int type;
@property(readonly, assign, nonatomic) NSDictionary* payload;
@property(readonly, assign, nonatomic) NSDictionary* commandInfo;
@property(readonly, assign, nonatomic) NSString* UUID;
-(void)dealloc;
-(id)initWithDictionary:(id)dictionary;
@end

