/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString;

@interface AWContentCategory : NSObject {
	BOOL _hasSubCategories;
	int _identifier;
	int _parentIdentifier;
	NSString* _name;
}
@property(assign, nonatomic) BOOL hasSubCategories;
@property(copy, nonatomic) NSString* name;
@property(assign, nonatomic) int parentIdentifier;
@property(assign, nonatomic) int identifier;
-(void)dealloc;
@end

