/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString, NSDate, AWContentVersion, NSSet;

@interface AWContentEntity : NSObject {
	unsigned long permissionsBitMask;
	BOOL _requireOnlineRead;
	BOOL _required;
	BOOL _canExport;
	BOOL _canEmail;
	BOOL _canPrint;
	BOOL _canAnnotate;
	BOOL _requireWatermark;
	BOOL _allowDocumentModification;
	int _identifier;
	int _folderIdentifier;
	int _repositoryIdentifier;
	NSString* _name;
	NSString* _extension;
	NSString* _comments;
	NSString* _MIMEType;
	NSString* _createdBy;
	NSDate* _createdDate;
	NSDate* _modifiedDate;
	NSString* _type;
	AWContentVersion* _version;
	NSDate* _expirationDate;
	NSDate* _effectiveDate;
	int _allowedDownloadNetwork;
	int _downloadPriority;
	int _contentPriority;
	NSSet* _categories;
	NSString* _checkedOutUser;
}
@property(copy, nonatomic) NSString* checkedOutUser;
@property(readonly, assign, nonatomic) BOOL hasShareWritePermission;
@property(readonly, assign, nonatomic) BOOL hasShareReadPermission;
@property(readonly, assign, nonatomic) BOOL hasDeletePermission;
@property(readonly, assign, nonatomic) BOOL hasWritePermission;
@property(readonly, assign, nonatomic) BOOL hasReadPermission;
@property(assign, nonatomic) BOOL requireWatermark;
@property(assign, nonatomic) BOOL allowDocumentModification;
@property(assign, nonatomic) BOOL canAnnotate;
@property(assign, nonatomic) BOOL canPrint;
@property(assign, nonatomic) BOOL canEmail;
@property(retain, nonatomic) NSSet* categories;
@property(assign, nonatomic) int contentPriority;
@property(assign, nonatomic) int downloadPriority;
@property(assign, nonatomic) int allowedDownloadNetwork;
@property(assign, nonatomic) BOOL canExport;
@property(assign, nonatomic) BOOL required;
@property(assign, nonatomic) BOOL requireOnlineRead;
@property(retain, nonatomic) NSDate* effectiveDate;
@property(retain, nonatomic) NSDate* expirationDate;
@property(retain, nonatomic) AWContentVersion* version;
@property(copy, nonatomic) NSString* type;
@property(retain, nonatomic) NSDate* modifiedDate;
@property(retain, nonatomic) NSDate* createdDate;
@property(copy, nonatomic) NSString* createdBy;
@property(copy, nonatomic) NSString* MIMEType;
@property(copy, nonatomic) NSString* comments;
@property(copy, nonatomic) NSString* extension;
@property(copy, nonatomic) NSString* name;
@property(assign, nonatomic) int repositoryIdentifier;
@property(assign, nonatomic) int folderIdentifier;
@property(assign, nonatomic) int identifier;
-(id)description;
-(id)init;
-(void)dealloc;
-(unsigned long)permissionsBitMask;
-(void)setPermissionsBitMask:(unsigned long)mask;
@end

