/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWProfilePayload.h"

@class NSString, NSArray;

@interface AWCompliancePayload : AWProfilePayload {
	BOOL _preventCompromisedDevices;
	BOOL _preventRestoringBackupDevices;
	BOOL _enableCompromisedProtection;
	BOOL _isV2;
	NSArray* _preventCompromisedDevicesActions;
	NSString* _compromisedPolicyID;
}
@property(assign, nonatomic) BOOL isV2;
@property(readonly, assign, nonatomic) NSString* compromisedPolicyID;
@property(readonly, assign, nonatomic) BOOL enableCompromisedProtection;
@property(readonly, assign, nonatomic) NSArray* preventCompromisedDevicesActions;
@property(readonly, assign, nonatomic) BOOL preventRestoringBackupDevices;
@property(readonly, assign, nonatomic) BOOL preventCompromisedDevices;
+(id)payloadTypeV2;
+(id)payloadType;
-(id)parseActions:(id)actions;
-(id)initWithDictionary:(id)dictionary;
@end

