/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import <Foundation/NSObject.h>

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface AWCompliancePolicyRule : NSObject <NSCoding> {
	NSString* _ruleType;
	NSString* _ruleOperator;
	NSArray* _ruleValue;
}
@property(retain, nonatomic) NSArray* ruleValue;
@property(copy, nonatomic) NSString* ruleOperator;
@property(copy, nonatomic) NSString* ruleType;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(void)dealloc;
-(id)initWithDictionary:(id)dictionary;
@end

