/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "AWInterApplicationCommunicationProtocol.h"

@class AWSSOCommunication, NSMutableDictionary;
@protocol AWPasscodeValidateProtocol, AWPasscodeCreateProtocol, AWPasscodeProtocol;

@interface AWCommunication : NSObject <AWInterApplicationCommunicationProtocol> {
	NSMutableDictionary* _callbackDictionary;
	AWSSOCommunication* _communication;
	int _currentType;
	id<AWPasscodeProtocol, AWPasscodeValidateProtocol, AWPasscodeCreateProtocol> _passcodeDelegate;
}
@property(assign, nonatomic) id<AWPasscodeProtocol, AWPasscodeValidateProtocol, AWPasscodeCreateProtocol> passcodeDelegate;
+(int)typeFromURL:(id)url;
+(id)methodFromType:(int)type;
+(int)responseForRequest:(int)request;
+(int)typeFromMethod:(id)method;
-(id)referenceViewController;
-(int)defaultErrorCodeForType:(int)type;
-(BOOL)supportsType:(int)type;
-(void)enrollmentAccountCouldNotAuthenticate:(id)authenticate Error:(id)error;
-(void)enrollmentAccountAuthenticted:(id)authenticted;
-(void)presentAuthentication;
-(void)presentViewController:(id)controller fromViewController:(id)viewController;
-(BOOL)presentRequestForType:(int)type;
-(BOOL)sendClearPasscodeRequestWithTime:(id)time withCompletion:(id)completion;
-(BOOL)sendLockRequestWithTime:(id)time withCompletion:(id)completion;
-(BOOL)sendRequest:(int)request withCompletion:(id)completion;
-(id)init;
@end

