/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AirWatch-Structs.h"
#import <Foundation/NSData.h>

@class AWFileHandle, NSString, AWBuffer;

@interface AWCryptData : NSData {
	int _operation;
	unsigned long _filesize;
	unsigned long _chunkSize;
	unsigned long _chunkOffset;
	unsigned long _blockFactor;
	unsigned long _cryptBlockSize;
	unsigned long _ivsize;
	unsigned long _offset;
	unsigned long _offsetBlock;
	unsigned long _offsetCorrection;
	unsigned long _actualSize;
	void* _buffer;
	void* _outBuffer;
	void* _ivBuffer;
	BOOL _isOldFormat;
	unsigned _fileStart;
	CCCryptorRef _cryptor;
	BOOL _usePaddingBlock;
	NSString* _inputPath;
	NSString* _outputPath;
	NSData* _key;
	AWFileHandle* _infileHandle;
	AWFileHandle* _outfileHandle;
	AWBuffer* _bufferData;
	NSData* _data;
	int _cipher;
	NSData* _defaultIV;
}
@property(retain, nonatomic) NSData* defaultIV;
@property(assign, nonatomic) int cipher;
@property(retain, nonatomic) NSData* data;
@property(retain, nonatomic) AWBuffer* bufferData;
@property(retain, nonatomic) AWFileHandle* outfileHandle;
@property(retain, nonatomic) AWFileHandle* infileHandle;
@property(assign, nonatomic) BOOL usePaddingBlock;
@property(copy, nonatomic) NSData* key;
@property(copy, nonatomic) NSString* outputPath;
@property(copy, nonatomic) NSString* inputPath;
+(void)setDelegate:(id)delegate;
-(void)setOldFormat;
-(id)headerData;
-(BOOL)loadHeader;
-(unsigned)seektoEnd;
-(BOOL)close;
-(BOOL)appendData:(id)data;
-(id)cipher:(id)cipher initializationVector:(id)vector;
-(unsigned long)cipher:(const void*)cipher length:(unsigned long)length initializationVector:(const void*)vector outputBuffer:(void*)buffer final:(BOOL)final;
-(void)resetCrypt:(void*)crypt;
-(void)encrypt:(id)encrypt;
-(unsigned)forward:(unsigned)forward;
-(BOOL)rewind;
-(BOOL)isEOF;
-(void)actualSize;
-(id)readBytes:(unsigned)bytes;
-(unsigned long)readBytes:(unsigned)bytes buffer:(char*)buffer;
-(unsigned)seekToOffSet:(unsigned)offSet;
-(BOOL)read:(unsigned)read;
-(void)writeToOutput;
-(BOOL)open;
-(void)randomBytes:(void*)bytes length:(unsigned long)length;
-(void)initCrypt;
-(id)initWithOperation:(int)operation;
-(void)dealloc;
@end

