/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>
#import "AirWatch-Structs.h"

@class UILabel, UIButton, UIImageView;

@interface AWCredentialView : UIView {
	BOOL _offlineButtonExist;
	UIButton* _settingButton;
	UIButton* _loginButton;
	UIImageView* _bgImageView;
	UIButton* _offLineButton;
	UIButton* _credentialSelectionButton;
	UILabel* _offlineLabel;
	id _loginButtonTappedBlock;
	id _toggleOfflineBlock;
	id _settingButtonTappedBlock;
	id _toggleCredentialSelectionBlock;
	UIView* _visibleAuthenticationView;
}
@property(retain, nonatomic) UIView* visibleAuthenticationView;
@property(retain, nonatomic) UILabel* offlineLabel;
@property(copy, nonatomic) id toggleCredentialSelectionBlock;
@property(copy, nonatomic) id settingButtonTappedBlock;
@property(copy, nonatomic) id loginButtonTappedBlock;
@property(copy, nonatomic) id toggleOfflineBlock;
@property(retain, nonatomic) UIButton* credentialSelectionButton;
@property(retain, nonatomic) UIButton* offLineButton;
@property(retain, nonatomic) UIImageView* bgImageView;
@property(retain, nonatomic) UIButton* loginButton;
@property(retain, nonatomic) UIButton* settingButton;
-(void)credentialToggleButtonTapped:(id)tapped;
-(void)loginButtonTapped:(id)tapped;
-(void)settingButtonTapped:(id)tapped;
-(void)toggleOfflineButton;
-(void)loginKeyboardTapped;
-(void)toggleOfflineButtonVisibility:(BOOL)visibility;
-(void)toggleStandardLoginItemsVisibility:(BOOL)visibility;
-(void)showAuthenticationTypeView:(id)view;
-(void)addAuthenticationTypeView:(id)view;
-(void)createOfflineButtonWithImage:(id)image;
-(void)createLoginButtonWithImage:(id)image;
-(void)createCredentialSelectionButtonWithImage:(id)image;
-(void)createSettingButtonWithImage:(id)image;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

