/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>
#import "AirWatch-Structs.h"

@class UIButton, NSMutableArray;

@interface AWCredentialSelectionView : UIView {
	NSMutableArray* _credentialViews;
	int _authenticationType;
	id _credentialTypeSelectedBlock;
	UIButton* _usernamePasswordButton;
	UIButton* _accessTokenButton;
}
@property(retain, nonatomic) UIButton* accessTokenButton;
@property(retain, nonatomic) UIButton* usernamePasswordButton;
@property(retain, nonatomic) NSMutableArray* credentialViews;
@property(copy, nonatomic) id credentialTypeSelectedBlock;
@property(assign, nonatomic) int authenticationType;
-(void)credentialButtonTapped:(id)tapped;
-(id)credentialViewForButton:(id)button;
-(float)spacing;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
@end

