/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>

@class UIImage, NSString, UIColor;

__attribute__((visibility("hidden")))
@interface AWCustomTableViewCellTypeValue1 : UITableViewCell {
	UIColor* _titleColor;
	BOOL _showImage;
	UIImage* _cellImage;
	NSString* _cellTitle;
	NSString* _cellDetailTitle;
}
@property(assign, nonatomic) BOOL showImage;
@property(retain, nonatomic) UIColor* titleColor;
@property(copy, nonatomic) NSString* cellDetailTitle;
@property(copy, nonatomic) NSString* cellTitle;
@property(retain, nonatomic) UIImage* cellImage;
-(void)dealloc;
@end

