/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWProfilePayload.h"

@class NSString;

@interface AWCustomPayload : AWProfilePayload {
	NSString* _settings;
}
@property(readonly, assign, nonatomic) NSString* settings;
+(id)payloadTypeV2;
+(id)payloadType;
-(void)dealloc;
-(id)initWithDictionary:(id)dictionary;
@end

