/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import "AWDataSamplerSample.h"

@class NSString;

@interface AWDataLog : AWDataSamplerSample <NSCoding> {
	NSString* _startTime;
	NSString* _endTime;
	NSString* _networkAdapter;
	int _networkAdapterType;
	unsigned long long _sentBytes;
	unsigned long long _receivedBytes;
	unsigned long long _sentPackets;
	unsigned long long _receivedPackets;
	BOOL _open;
	int _usageType;
	BOOL _isRoaming;
}
@property(assign, nonatomic) int usageType;
@property(assign, nonatomic) BOOL open;
@property(assign, nonatomic) BOOL isRoaming;
@property(assign, nonatomic) unsigned long long receivedPackets;
@property(assign, nonatomic) unsigned long long sentPackets;
@property(assign, nonatomic) unsigned long long receivedBytes;
@property(assign, nonatomic) unsigned long long sentBytes;
@property(assign, nonatomic) int networkAdapterType;
@property(copy, nonatomic) NSString* networkAdapter;
@property(copy, nonatomic) NSString* endTime;
@property(copy, nonatomic) NSString* startTime;
-(id)entryData;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(id)data;
-(void)dealloc;
-(id)init;
@end

