/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


@interface AWDataUsageConfiguration : NSObject {
	BOOL _persistAfterSend;
	int _samplingInterval;
	int _transmitInterval;
}
@property(assign, nonatomic) int transmitInterval;
@property(assign, nonatomic) int samplingInterval;
@property(assign, nonatomic) BOOL persistAfterSend;
@end

