/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWDataSamplerModule.h"


@interface AWDataSamplerAnalyticsModule : AWDataSamplerModule {
}
-(void)sampleWithName:(id)name value:(id)value eventType:(int)type eventValueType:(int)type4 bundleVersion:(id)version bundleName:(id)name6 sessionUUID:(id)uuid;
-(id)getData;
-(void)sample;
-(void)tick;
@end

