/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWDataSamplerSample.h"


@interface AWDataSamplerMemorySample : AWDataSamplerSample {
	unsigned _memoryLoad;
	unsigned _totalPhysical;
	unsigned _availablePhysical;
	unsigned _totalPageFile;
	unsigned _availablePageFile;
	unsigned _totalVirtual;
	unsigned _availableVirtual;
}
@property(assign, nonatomic) unsigned availableVirtual;
@property(assign, nonatomic) unsigned totalVirtual;
@property(assign, nonatomic) unsigned availablePageFile;
@property(assign, nonatomic) unsigned totalPageFile;
@property(assign, nonatomic) unsigned availablePhysical;
@property(assign, nonatomic) unsigned totalPhysical;
@property(assign, nonatomic) unsigned memoryLoad;
-(id)data;
-(void)sample;
-(id)init;
@end

