/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIViewController.h>

@class NSString, UIView, AWLoadingLabel, UIActivityIndicatorView, UILabel;

@interface AWDataViewController : UIViewController {
	UIActivityIndicatorView* _loadingActivityIndicatorView;
	BOOL _isLoading;
	BOOL _isOffline;
	BOOL _hasContent;
	UIView* _contentView;
	AWLoadingLabel* _loadingLabel;
	UILabel* _contentLabel;
	NSString* _offlineMessage;
	NSString* _noContentMessage;
}
@property(assign, nonatomic) BOOL hasContent;
@property(copy, nonatomic) NSString* noContentMessage;
@property(assign, nonatomic) BOOL isOffline;
@property(copy, nonatomic) NSString* offlineMessage;
@property(assign, nonatomic) UILabel* contentLabel;
@property(assign, nonatomic) BOOL isLoading;
@property(readonly, assign, nonatomic) AWLoadingLabel* loadingLabel;
@property(readonly, assign, nonatomic) UIView* contentView;
-(void)hideSubview:(id)subview andDisplaySubview:(id)subview2;
-(void)alignLoadingLabel;
-(id)loadingActivityIndicatorView;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)dealloc;
@end

