/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWDataSamplerSample.h"

@class NSString;

@interface AWDataSamplerGPSSample : AWDataSamplerSample {
	unsigned short _facility;
	unsigned short _eventcode;
	unsigned short _noteLength;
	float _speed;
	float _heading;
	float _altitude;
	NSString* _note;
	double _latitude;
	double _longitude;
	double _magneticVariation;
}
@property(assign, nonatomic) NSString* note;
@property(assign, nonatomic) unsigned short noteLength;
@property(assign, nonatomic) unsigned short eventcode;
@property(assign, nonatomic) unsigned short facility;
@property(assign, nonatomic) float altitude;
@property(assign, nonatomic) double magneticVariation;
@property(assign, nonatomic) float heading;
@property(assign, nonatomic) float speed;
@property(assign, nonatomic) double longitude;
@property(assign, nonatomic) double latitude;
-(id)data;
-(void)sample;
-(id)init;
@end

