/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


@interface AWDataSamplerSample : NSObject {
	double _sampleFrequency;
	unsigned short _messageId;
	unsigned short _messageSize;
	unsigned short _year;
	unsigned short _month;
	unsigned short _day;
	unsigned short _hour;
	unsigned short _minute;
	unsigned short _second;
	unsigned short _millisecond;
}
@property(assign, nonatomic) unsigned short millisecond;
@property(assign, nonatomic) unsigned short second;
@property(assign, nonatomic) unsigned short minute;
@property(assign, nonatomic) unsigned short hour;
@property(assign, nonatomic) unsigned short day;
@property(assign, nonatomic) unsigned short month;
@property(assign, nonatomic) unsigned short year;
@property(assign, nonatomic) unsigned short messageSize;
@property(assign, nonatomic) unsigned short messageId;
@property(assign, nonatomic) double sampleFrequency;
-(id)data;
-(void)sample;
@end

