/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString, AWDataSamplerConnection;

@interface AWDataSamplerConfiguration : NSObject {
	AWDataSamplerConnection* dataSamplerConnection;
	unsigned sampleModules;
	double defaultSampleInterval;
	double transmitInterval;
	int traceLevel;
	NSString* urlScheme;
}
@property(retain, nonatomic) NSString* urlScheme;
@property(assign) int traceLevel;
@property(assign, nonatomic) double transmitInterval;
@property(assign, nonatomic) double defaultSampleInterval;
@property(assign, nonatomic) unsigned sampleModules;
@property(retain, nonatomic) AWDataSamplerConnection* dataSamplerConnection;
-(void)dealloc;
-(id)initWithSampleModules:(unsigned)sampleModules defaultSampleInterval:(double)interval defaultTransmitInterval:(double)interval3 traceLevel:(int)level;
-(id)initWithHost:(id)host port:(int)port sampleModules:(unsigned)modules defaultSampleInterval:(double)interval defaultTransmitInterval:(double)interval5 traceLevel:(int)level;
@end

