/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWDataSamplerSample.h"

@class NSString;

@interface AWDataSamplerNetworkAdapterInfoSample : AWDataSamplerSample {
	unsigned short _ipAddressCount;
	unsigned short _gatewayCount;
	unsigned short _haveWINS;
	unsigned short _MacAddressSize;
	unsigned short _DHCPEnabled;
	unsigned short _adapterNameSize;
	unsigned short _adapterDescriptionSize;
	unsigned _type;
	NSString* _MacAddress;
	NSString* _currentIPAddress;
	NSString* _currentIPMask;
	unsigned _currentNTEContext;
	NSString* _DHCPIPAddress;
	NSString* _DHCPIPMask;
	unsigned _DHCPNTEContext;
	NSString* _adapterName;
	NSString* _adapterDescription;
}
@property(assign, nonatomic) unsigned short adapterDescriptionSize;
@property(copy, nonatomic) NSString* adapterDescription;
@property(assign, nonatomic) unsigned short adapterNameSize;
@property(copy, nonatomic) NSString* adapterName;
@property(assign, nonatomic) unsigned DHCPNTEContext;
@property(copy, nonatomic) NSString* DHCPIPMask;
@property(copy, nonatomic) NSString* DHCPIPAddress;
@property(assign, nonatomic) unsigned short DHCPEnabled;
@property(assign, nonatomic) unsigned currentNTEContext;
@property(copy, nonatomic) NSString* currentIPMask;
@property(copy, nonatomic) NSString* currentIPAddress;
@property(assign, nonatomic) unsigned short MacAddressSize;
@property(copy, nonatomic) NSString* MacAddress;
@property(assign, nonatomic) unsigned short haveWINS;
@property(assign, nonatomic) unsigned short gatewayCount;
@property(assign, nonatomic) unsigned short ipAddressCount;
@property(assign, nonatomic) unsigned type;
-(void)dealloc;
-(id)getMACAddressBytes;
-(id)data;
-(void)sample;
-(id)initWithNetworkAdapter:(id)networkAdapter;
-(id)init;
@end

