/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "AWDataSamplerHTTPTransmitterDelegate.h"
#import "AWDataSamplerTransmitterDelegate.h"

@class AWDataSamplerHTTPTransmitter, NSDictionary, AWDataSamplerTransmitter, NSTimer, AWDataSamplerConfiguration, NSMutableArray;

@interface AWDataSampler : NSObject <AWDataSamplerTransmitterDelegate, AWDataSamplerHTTPTransmitterDelegate> {
	BOOL g_AWDataSamplerIsInitialized;
	BOOL g_AWDataSamplerIsStarted;
	int _transmitType;
	BOOL sendGPSImmediate;
	NSDictionary* dataUsageObject;
	NSDictionary* callLogObject;
	AWDataSamplerConfiguration* dataSamplerConfig;
	NSMutableArray* sampleModulesArray;
	NSTimer* dataSamplerTimer;
	double dataSamplerTimeInterval;
	AWDataSamplerTransmitter* _xmitter;
	AWDataSamplerHTTPTransmitter* _httpxmitter;
	BOOL _transmitAtStartUp;
	id completionHandler;
}
@property(copy, nonatomic) id completionHandler;
@property(assign, nonatomic) BOOL transmitAtStartUp;
@property(assign, nonatomic) BOOL sendGPSImmediate;
@property(assign, nonatomic) BOOL g_AWDataSamplerIsStarted;
@property(assign, nonatomic) BOOL g_AWDataSamplerIsInitialized;
+(void)sendGPSImmediate;
+(id)alloc;
+(id)mDataSamplerModule;
-(void)receivedGPSUpdate:(id)update;
-(void)dealloc;
-(void)SampleModules;
-(void)DataMessageSendFailed:(id)failed error:(id)error transmitter:(id)transmitter;
-(void)DataMessageSentSuccessfully:(id)successfully transmitter:(id)transmitter;
-(void)tick;
-(BOOL)TransmitGPS:(id*)gps delegate:(id)delegate;
-(BOOL)Transmit:(id*)transmit withCompletionHandler:(id)completionHandler;
-(BOOL)Transmit:(id*)transmit delegate:(id)delegate;
-(BOOL)shutDown:(id*)down;
-(BOOL)startUp:(id*)up;
-(void)setConfig:(id)config;
-(id)initWithConfig:(id)config;
@end

