/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSTimeZone, AWDataLog;

@interface AWDataUsageManager : NSObject {
	AWDataLog* _currentDataLog;
	AWDataLog* _currentCellularDataLog;
	int _sampleInterval;
	int _transmitLimit;
	BOOL _deviceIsRoaming;
	NSTimeZone* timeZone;
}
@property(retain, nonatomic) NSTimeZone* timeZone;
+(id)sharedInstance;
-(id)aggregateEntryForLogs:(id)logs forAdapter:(id)adapter;
-(id)getISOCountryCodeByCarrier;
-(void)checkForDeviceRoaming;
-(id)cellularNetworkAdapter;
-(int)daysBetweenDate:(id)date toDate:(id)date2;
-(id)cellularRoamingDataUsage;
-(id)cellularDataUsageLogs;
-(id)dataUsageLogs;
-(unsigned long long)logCellSentPackets;
-(unsigned long long)logCellReceivedPackets;
-(unsigned long long)logCellSentBytes;
-(unsigned long long)logCellReceivedBytes;
-(unsigned long long)logSentPackets;
-(unsigned long long)logReceivedPackets;
-(unsigned long long)logSentBytes;
-(unsigned long long)logReceivedBytes;
-(void)transmitSuccess:(id)success;
-(id)transmitData;
-(void)addLogToList:(id)list;
-(void)sampleData:(int)data;
-(void)dealloc;
@end

