/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AirWatch-Structs.h"
#import <Foundation/NSData.h>


@interface AWData : NSData {
	AWDataSettings _settings;
}
@property(readonly, assign, nonatomic) AWDataSettings settings;
+(id)errorWithCode:(int)code localizedDescription:(id)description underlyingError:(id)error;
+(id)randomDataOfLength:(unsigned long)length;
+(id)dataWithData:(id)data;
+(id)dataWithContentsOfURL:(id)url options:(unsigned)options error:(id*)error;
+(id)dataWithContentsOfURL:(id)url;
+(id)dataWithContentsOfMappedFile:(id)mappedFile;
+(id)dataWithContentsOfFile:(id)file options:(unsigned)options error:(id*)error;
+(id)dataWithContentsOfFile:(id)file;
+(id)dataWithBytesNoCopy:(void*)bytesNoCopy length:(unsigned)length freeWhenDone:(BOOL)done;
+(id)dataWithBytesNoCopy:(void*)bytesNoCopy length:(unsigned)length;
+(id)dataWithBytes:(const void*)bytes length:(unsigned)length;
+(id)data;
-(BOOL)processResult:(int)result data:(id)data length:(unsigned long)length output:(id)output error:(id*)error;
-(id)readStream:(id)stream length:(unsigned)length;
-(BOOL)decryptFromStream:(id)stream toStream:(id)stream2 encryptionKey:(id)key error:(id*)error;
-(BOOL)encryptFromStream:(id)stream toStream:(id)stream2 encryptionKey:(id)key error:(id*)error;
-(BOOL)performOperation:(unsigned)operation fromStream:(id)stream toStream:(id)stream3 encryptionKey:(id)key nonce:(id)nonce error:(id*)error;
-(BOOL)writeToURL:(id)url options:(unsigned)options error:(id*)error;
-(BOOL)writeToURL:(id)url atomically:(BOOL)atomically;
-(BOOL)writeToFile:(id)file options:(unsigned)options error:(id*)error;
-(BOOL)writeToFile:(id)file atomically:(BOOL)atomically;
-(NSRange)rangeOfData:(id)data options:(unsigned)options range:(NSRange)range;
-(id)subdataWithRange:(NSRange)range;
-(void)getBytes:(void*)bytes range:(NSRange)range;
-(void)getBytes:(void*)bytes length:(unsigned)length;
-(void)getBytes:(void*)bytes;
-(id)description;
-(const void*)bytes;
-(id)initWithData:(id)data;
-(id)initWithContentsOfURL:(id)url options:(unsigned)options error:(id*)error;
-(id)initWithContentsOfURL:(id)url;
-(id)initWithContentsOfMappedFile:(id)mappedFile;
-(id)initWithContentsOfFile:(id)file options:(unsigned)options error:(id*)error;
-(id)initWithContentsOfFile:(id)file;
-(id)initWithCoder:(id)coder;
-(id)initWithBytesNoCopy:(void*)bytesNoCopy length:(unsigned)length freeWhenDone:(BOOL)done;
-(id)initWithBytesNoCopy:(void*)bytesNoCopy length:(unsigned)length;
-(id)initWithBytes:(const void*)bytes length:(unsigned)length;
-(id)init;
@end

