/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWDataSamplerPayload.h"

@class NSMutableData;

@interface AWDataPayload : AWDataSamplerPayload {
	NSMutableData* _sampleData;
}
-(id)data;
-(void)addSample:(id)sample;
-(void)dealloc;
-(id)initWithData:(id)data;
-(id)init;
@end

