/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWDataSamplerSample.h"

@class NSString;

@interface AWDataSamplerApplicationSample : AWDataSamplerSample {
	unsigned short _entrySize;
	unsigned short _appNameLength;
	unsigned short _appVerLength;
	unsigned short _appIdLength;
	NSString* _appName;
	NSString* _appVersion;
	NSString* _appIdentifier;
}
@property(assign, nonatomic) unsigned short appIdLength;
@property(retain, nonatomic) NSString* appIdentifier;
@property(assign, nonatomic) unsigned short appVerLength;
@property(retain, nonatomic) NSString* appVersion;
@property(assign, nonatomic) unsigned short entrySize;
@property(assign, nonatomic) unsigned short appNameLength;
@property(retain, nonatomic) NSString* appName;
-(void)dealloc;
-(id)data;
-(void)sample;
-(id)init;
@end

