/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "AWNetworkConnectionDelegate.h"

@class NSMutableData;
@protocol AWDeviceInfoNetworkControllerDelegate;

__attribute__((visibility("hidden")))
@interface AWDeviceInfoNetworkController : NSObject <AWNetworkConnectionDelegate> {
	int _currentRequestType;
	NSMutableData* _responseDataBuffer;
	id<AWDeviceInfoNetworkControllerDelegate> _delegate;
	BOOL _isRequestingData;
}
@property(readonly, assign, nonatomic) int requestType;
@property(assign, nonatomic) id<AWDeviceInfoNetworkControllerDelegate> delegate;
-(void)networkConnection:(id)connection receivedResponseData:(id)data;
-(void)networkConnection:(id)connection failedWithError:(id)error;
-(void)connectionDidFinishLoading:(id)connection;
-(void)connection:(id)connection didReceiveResponse:(id)response;
-(void)connection:(id)connection didReceiveData:(id)data;
-(void)connection:(id)connection didFailWithError:(id)error;
-(void)startRequestWithType:(int)type baseUrl:(id)url;
-(void)dealloc;
-(id)init;
@end

