/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class AWDeviceStatusConfiguration;

@interface AWDeviceStatusController : NSObject {
	AWDeviceStatusConfiguration* _configuration;
}
@property(retain, nonatomic) AWDeviceStatusConfiguration* configuration;
+(void)queryDeviceEnrollmentStatus:(id)status;
-(void)queryDeviceRoamingStatus:(id)status;
-(void)queryDeviceEnrollmentStatus:(id)status;
-(id)initWithConfiguration:(id)configuration;
@end

