/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString;

@interface AWDeviceInfo : NSObject {
	int _mode;
	NSString* _applicationIdentifier;
	NSString* _applicationUDID;
	NSString* _APNSToken;
}
@property(copy, nonatomic) NSString* APNSToken;
@property(copy, nonatomic) NSString* applicationUDID;
@property(retain, nonatomic) NSString* applicationIdentifier;
@property(assign, nonatomic) int mode;
+(id)sharedInstance;
-(id)productname;
-(BOOL)hasMAMUniqueIdentifier;
-(id)defaultContainerID;
-(BOOL)canSendEmail;
-(BOOL)canPlaceCall;
-(BOOL)isWideScreen;
-(BOOL)isIPad;
-(id)model;
-(id)nextGenUniqueIdentifier:(id)identifier error:(id*)error;
-(id)nextGenUniqueIdentifier:(id*)identifier;
-(id)systemVersion;
-(id)osBuildString;
-(unsigned short)osVersionBuild;
-(unsigned short)osVersionMinor;
-(unsigned short)osVersionMajor;
-(id)macaddress;
-(id)platformCode;
-(id)platformString;
-(int)platformType;
-(id)freeDiskSpace;
-(id)totalDiskSpace;
-(unsigned)maxSocketBufferSize;
-(unsigned)busFrequency;
-(unsigned)cpuFrequency;
-(id)hwmodel;
-(id)platform;
-(unsigned)getSysInfo:(unsigned)info;
-(id)getSysInfoByName:(char*)name;
-(id)name;
-(id)networkAdapters;
-(int)availableMemory;
-(int)inactiveMemory;
-(int)activeMemory;
-(int)wiredMemory;
-(int)totalMemory;
-(int)availableVirtualMemory;
-(int)totalVirtualMemory;
-(int)availablePageFile;
-(int)totalPageFile;
-(int)availablePhysicalMemory;
-(unsigned long long)totalPhysicalMemory;
-(id)deviceUDID;
-(id)formattedUniqueIdentifier;
-(id)formattedUniqueIdentifier:(id*)identifier;
-(id)idFromDefaults;
-(id)randomUniqueIdentifier;
-(void)saveMAMUniqueIdentifier:(id)identifier;
-(void)saveContainerUniqueIdentifier:(id)identifier;
-(void)saveFormattedUniqueIdentifier:(id)identifier;
-(void)udidLookupWithContainerID:(id)containerID completion:(id)completion;
-(void)awuidWithCompletion:(id)completion;
-(int)awDeviceTypeIdentifier;
-(void)dealloc;
-(id)init;
@end

