/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWNetworkConnectionDelegate.h"
#import <Foundation/NSObject.h>

@class AWNetworkConnection;

@interface AWDeviceInfoController : NSObject <AWNetworkConnectionDelegate> {
	AWNetworkConnection* _deviceInfoConnection;
	AWNetworkConnection* _supportInfoConnection;
	id _deviceInfoCompletion;
	id _supportInfoCompletion;
	unsigned _deviceInfoStatusCode;
	unsigned _supportInfoStatusCode;
}
@property(assign, nonatomic) unsigned supportInfoStatusCode;
@property(assign, nonatomic) unsigned deviceInfoStatusCode;
@property(copy, nonatomic) id supportInfoCompletion;
@property(copy, nonatomic) id deviceInfoCompletion;
@property(retain, nonatomic) AWNetworkConnection* supportInfoConnection;
@property(retain, nonatomic) AWNetworkConnection* deviceInfoConnection;
-(void)networkConnection:(id)connection didReceiveResponse:(id)response;
-(void)networkConnection:(id)connection receivedResponseData:(id)data;
-(void)networkConnection:(id)connection failedWithError:(id)error;
-(void)fetchDeviceInfoForType:(unsigned)type withCompletion:(id)completion;
-(void)fetchSupportInfo:(id)info;
-(void)fetchDeviceInfo:(id)info;
-(void)dealloc;
@end

