/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AirWatch-Structs.h"
#import <UIKit/UIView.h>

@class UIColor, CALayer, UISearchBar, UITableView, LayerDelegate, AWDocumentSearchViewController;

@interface AWDocumentSearchView : UIView {
	CALayer* backgroundLayer;
	LayerDelegate* _layerDelegate;
	BOOL _isDisplayingTable;
	UITableView* _tableView;
	UISearchBar* _searchBar;
	UIColor* _tint;
	AWDocumentSearchViewController* _controller;
}
@property(assign, nonatomic) BOOL isDisplayingTable;
@property(retain, nonatomic) UISearchBar* searchBar;
@property(retain, nonatomic) UITableView* tableView;
@property(assign, nonatomic) AWDocumentSearchViewController* controller;
@property(retain, nonatomic) UIColor* tint;
-(void)searchBarSearchButtonClicked:(id)clicked;
-(void)hideTableResults;
-(void)showTableResults;
-(CGRect)calculateLayerBoundsShowingTable:(BOOL)table;
-(void)drawBackgroundLayer:(id)layer inContext:(CGContextRef)context;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame Controller:(id)controller;
-(id)initWithFrame:(CGRect)frame;
@end

