/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>

@class AWOutlineThumbnailButton, NSArray;

@interface AWDocumentOutlineCell : UITableViewCell {
	BOOL _enableThumbnailDescription;
	NSArray* _thumbnails;
	AWOutlineThumbnailButton* _leftThumbnailButton;
	AWOutlineThumbnailButton* _centerThumbnailButton;
	AWOutlineThumbnailButton* _rightThumbnailButton;
}
@property(assign, nonatomic) BOOL enableThumbnailDescription;
@property(retain, nonatomic) NSArray* thumbnails;
@property(readonly, assign, nonatomic) AWOutlineThumbnailButton* rightThumbnailButton;
@property(readonly, assign, nonatomic) AWOutlineThumbnailButton* centerThumbnailButton;
@property(readonly, assign, nonatomic) AWOutlineThumbnailButton* leftThumbnailButton;
-(void)resetBookmarks;
-(void)resetThumbnails;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

