/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>
#import "AirWatch-Structs.h"

@class NSOperationQueue, UIButton, UIImageView, NSMutableArray;
@protocol AWDocumentScrubViewDataSource, AWDocumentScrubbingViewDelegate;

@interface AWDocumentScrubbingView : UIView {
	NSMutableArray* _thumbnails;
	UIView* _thumbnailContentView;
	CGRect _cachedThumbnailRect;
	int _previousOrientation;
	unsigned _correctedPageCount;
	BOOL _isRightBarButtonItemVisible;
	BOOL _isLeftBarButtonItemVisible;
	id<AWDocumentScrubbingViewDelegate> _delegate;
	id<AWDocumentScrubViewDataSource> _dataSource;
	unsigned _pageCount;
	unsigned _currentPage;
	NSOperationQueue* _thumbnailQueue;
	UIImageView* _cursorImageView;
	UIButton* _leftBarButtonItem;
	UIButton* _rightBarButtonItem;
}
@property(assign, nonatomic) unsigned correctedPageCount;
@property(assign, nonatomic) int previousOrientation;
@property(readonly, assign, nonatomic) UIImageView* cursorImageView;
@property(readonly, assign, nonatomic) NSOperationQueue* thumbnailQueue;
@property(assign, nonatomic) BOOL isRightBarButtonItemVisible;
@property(assign, nonatomic) BOOL isLeftBarButtonItemVisible;
@property(retain, nonatomic) UIButton* rightBarButtonItem;
@property(retain, nonatomic) UIButton* leftBarButtonItem;
@property(assign, nonatomic) unsigned currentPage;
@property(readonly, assign, nonatomic) unsigned pageCount;
@property(assign, nonatomic) id<AWDocumentScrubViewDataSource> dataSource;
@property(assign, nonatomic) id<AWDocumentScrubbingViewDelegate> delegate;
-(void)addRightBarButton;
-(void)addLeftBarButton;
-(void)scrollToPage:(unsigned)page;
-(void)accommodateThubmnailDrawerCapacity:(unsigned)capacity;
-(void)positionThumbnailContentView;
-(unsigned)maximumPageCountForWidth:(float)width;
-(void)handleTouch:(id)touch isDragging:(BOOL)dragging;
-(void)reloadData;
-(void)deviceOrientationDidChangeNotification:(id)deviceOrientation;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)repositionThumbnails;
-(void)removeThumbnailAtIndex:(unsigned)index;
-(void)setThumbnail:(id)thumbnail AtIndex:(unsigned)index;
-(CGRect)rectForViewAtIndex:(unsigned)index;
-(BOOL)canBecomeFirstResponder;
-(CGRect)resizeCursorImageView;
-(void)stopRendering;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

