/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>
#import "AirWatch-Structs.h"

@class AWCursorTriangle, UILabel;

@interface AWDocumentHUDView : UIView {
	UILabel* _textLabel;
	UIView* _hudView;
	AWCursorTriangle* _hudViewArrow;
}
@property(readonly, assign, nonatomic) AWCursorTriangle* hudViewArrow;
@property(readonly, assign, nonatomic) UIView* hudView;
@property(readonly, assign, nonatomic) UILabel* textLabel;
-(void)updateHUDView:(int)view pageCount:(int)count;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

