/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"
#import "AWTreeNode.h"

@class NSNumber, NSURL, NSString;

@interface AWDocumentTOCNode : AWTreeNode <NSObject> {
	BOOL _isURL;
	int _level;
	NSString* _title;
	NSNumber* _page;
	NSURL* _url;
}
@property(retain, nonatomic) NSURL* url;
@property(assign, nonatomic) BOOL isURL;
@property(retain, nonatomic) NSNumber* page;
@property(retain, nonatomic) NSString* title;
@property(assign, nonatomic) int level;
+(id)nodeWithTitle:(id)title page:(id)page level:(int)level;
-(void)dealloc;
-(id)description;
-(id)initWithTitle:(id)title page:(id)page level:(int)level;
@end

