/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface AWEmailAutodiscover : NSObject {
}
+(void)fetchEmailAutoDiscoveryInfoWithUrl:(id)url forDomain:(id)domain withCompletionBlock:(id)completionBlock;
@end

