/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITextFieldDelegate.h"
#import "AWPasscodeCompletionProtocol.h"
#import "AWBaseEnrollmentViewController.h"
#import "AirWatch-Structs.h"
#import "UIAlertViewDelegate.h"

@class UILabel, UIButton, UITextField, UIToolbar;
@protocol AWPasscodeProtocol, AWPasscodeCreateProtocol;

@interface AWEnrollmentCreatePINViewController : AWBaseEnrollmentViewController <UIAlertViewDelegate, UITextFieldDelegate, AWPasscodeCompletionProtocol> {
	id _completionBlock;
	int passwordAttemptCount;
	UIToolbar* dismissBar;
	BOOL _confirmPassword;
	id<AWPasscodeProtocol, AWPasscodeCreateProtocol> _passcodeHandler;
	UITextField* _pinField;
	UITextField* _pinConfirmField;
	UILabel* _statusLabel;
	UIButton* _nextButton;
	UIButton* _backButton;
}
@property(retain, nonatomic) UIButton* backButton;
@property(retain, nonatomic) UIButton* nextButton;
@property(retain, nonatomic) UILabel* statusLabel;
@property(retain, nonatomic) UITextField* pinConfirmField;
@property(retain, nonatomic) UITextField* pinField;
@property(assign, nonatomic) id<AWPasscodeProtocol, AWPasscodeCreateProtocol> passcodeHandler;
@property(assign, nonatomic) BOOL confirmPassword;
-(unsigned)supportedInterfaceOrientations;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)dismissPressed;
-(BOOL)textFieldShouldReturn:(id)textField;
-(void)arrangeButtons;
-(void)configureButtons;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)nextButtonTapped:(id)tapped;
-(void)backButtonTapped:(id)tapped;
-(void)setPasscodeCompletionBlock:(id)block;
-(void)keyboardWillHide:(id)keyboard;
-(void)keyboardWillShow:(id)keyboard;
-(void)setPropertiesForTextField:(id)textField;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)dealloc;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

