/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class AWDeviceInfoNetworkController;

__attribute__((visibility("hidden")))
@interface AWEnrollmentStatusRetriver : NSObject {
	id _completionBlock;
	AWDeviceInfoNetworkController* networkController;
}
+(BOOL)isMdmSdkEndpointAvailable;
+(void)fetchEnrollmentStatus:(id)status;
@end

