/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class AWEnrollmentAccount;

@interface AWEnrollmentAccountAuthenticator : NSObject {
	AWEnrollmentAccount* _account;
	id _callbackBlock;
	int _endpointType;
}
@property(copy) id callbackBlock;
@property(retain, nonatomic) AWEnrollmentAccount* account;
@property(assign, nonatomic) int endpointType;
-(id)deviceMistmatchError;
-(id)deviceNotEnrolledError;
-(id)deviceNotFoundError;
-(id)internalServerError;
-(id)invalidActivationCodeError;
-(id)genericLoginFailedError;
-(id)invalidCredentialError;
-(id)unknownErrorWithErrorCode:(int)errorCode;
-(id)unknownError;
-(void)validateResponseFromAuthenticationEndpoint:(id)authenticationEndpoint;
-(void)validateResponseFromAssetManagementEndpoint:(id)assetManagementEndpoint;
-(void)validateAuthenticationResponse:(id)response;
-(void)parseData:(id)data fromResponse:(id)response error:(id)error;
-(id)authenticationEndpointRequestBodyText;
-(id)assetManagementEndpointRequestBodyText;
-(void)authenticateViaAccessManagementEndpoint;
-(void)authenticateViaAuthenticationEndpoint;
-(void)authenticateAccount:(id)account callBackBlock:(id)block;
-(void)dealloc;
@end

