/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString, NSData;

@interface AWEncryptedFileHeader : NSObject {
	unsigned short _version;
	unsigned short _size;
	unsigned short _algorithm;
	unsigned short _keySize;
	unsigned short _hashAlgorithm;
	unsigned short _paddingType;
	NSString* _mimeType;
	int _optionFlags;
	NSData* _optionMask;
	NSData* _iv;
	NSData* _keyHash;
	unsigned long long _fileSize;
}
@property(copy, nonatomic) NSData* keyHash;
@property(copy, nonatomic) NSData* iv;
@property(copy, nonatomic) NSData* optionMask;
@property(assign, nonatomic) int optionFlags;
@property(assign, nonatomic) unsigned short paddingType;
@property(assign, nonatomic) unsigned short hashAlgorithm;
@property(assign, nonatomic) unsigned short keySize;
@property(assign, nonatomic) unsigned short algorithm;
@property(copy, nonatomic) NSString* mimeType;
@property(assign, nonatomic) unsigned long long fileSize;
@property(readonly, assign, nonatomic) unsigned short size;
@property(assign, nonatomic) unsigned short version;
-(void)retrieveOptionFlags;
-(id)paddingString:(unsigned short)string;
-(id)hashMethodString:(unsigned short)string;
-(id)keySizeString:(unsigned short)string;
-(id)algorithmString:(unsigned short)string;
-(id)description;
-(id)dataRepresentation;
-(void)dealloc;
-(BOOL)initializeWithData:(id)data;
-(id)initWithFileAtPath:(id)path;
-(id)init;
@end

