/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "EmailAuthenticationDelegate.h"
#import <UIKit/UITableViewController.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface AWEnrollmentStatusViewController : UITableViewController <EmailAuthenticationDelegate> {
	BOOL _isConfigured;
	NSString* _groupID;
	NSString* _userName;
}
@property(copy, nonatomic) NSString* userName;
@property(copy, nonatomic) NSString* groupID;
-(void)emailAuthenticationDidSelectContinueButton:(id)emailAuthentication;
-(void)getAirwatchAuthenticateInfo;
-(void)updateMDMStatus:(id)status;
-(void)refresh;
-(void)sendData;
-(void)unEnroll;
-(void)launchDeviceEnrollment;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view titleForHeaderInSection:(int)section;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidUnload;
-(void)viewDidLoad;
-(void)didReceiveMemoryWarning;
-(void)dealloc;
-(id)initWithStyle:(int)style;
@end

