/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AirWatch-Structs.h"
#import <UIKit/UIView.h>


__attribute__((visibility("hidden")))
@interface AWEnrollmentCompleteView : UIView {
	id _block;
}
@property(copy, nonatomic) id block;
-(void)dismissView:(id)view;
-(id)initWithFrame:(CGRect)frame withCompletion:(id)completion;
@end

