/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIViewController.h>

@class AWLinearGradientView, NSString, AWWebView;

@interface AWEULAViewController : UIViewController {
	AWLinearGradientView* _linearGradientView;
	AWWebView* eulaWebView;
	id _EULABlock;
	id _DeclineEULABlock;
	NSString* _filePath;
	NSString* _eulaContent;
}
@property(retain, nonatomic) NSString* eulaContent;
@property(retain, nonatomic) NSString* filePath;
@property(copy, nonatomic) id DeclineEULABlock;
@property(copy, nonatomic) id EULABlock;
-(void)dealloc;
-(void)didDeclineEULA;
-(void)didAcceptEULA;
-(unsigned)supportedInterfaceOrientations;
-(BOOL)shouldAutorotate;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
@end

