/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


@interface AWExternalAuthenticatorController : NSObject {
	int _state;
	int _source;
	id _callback;
}
@property(copy, nonatomic) id callback;
@property(assign, nonatomic) int source;
@property(assign, nonatomic) int state;
+(id)sharedInstance;
-(id)brokerAppScheme;
-(BOOL)canUseAgent;
-(BOOL)canUseWorkspace;
-(BOOL)processLaunchURL:(id)url;
-(int)authenticateWithURL:(id)url callbackScheme:(id)scheme callback:(id)callback;
@end

