/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSTimer;

@interface AWF5ProxyController : NSObject {
	NSTimer* f5SessionCheckTimer;
	int f5SessionInvalidAttempts;
	BOOL _isEnabled;
	BOOL _authenticated;
}
@property(readonly, assign, nonatomic) BOOL authenticated;
@property(readonly, assign, nonatomic) BOOL isEnabled;
+(id)sharedInstance;
-(void)setDeviceF5SessionKey:(id)key error:(id*)error;
-(id)deviceF5SessionKey:(id*)key;
-(int)socketHandleForRequest:(id)request withError:(id*)error;
-(id)userAgent;
-(BOOL)checkAndRenewF5SessionInNeededWithError:(id*)error ifRecheck:(BOOL)recheck;
-(BOOL)userNamePasswordAuthenticationWithError:(id*)error;
-(BOOL)clientCertificateAuthenticationWithError:(id*)error;
-(void)initializeF5proxy;
-(void)handleF5SessionExpiry;
-(void)stopF5proxy;
-(void)f5SessionTimerFired;
-(BOOL)authenticateF5SessionWithError:(id*)error;
-(void)setupF5SesssionCheckTimer;
-(BOOL)startF5ProxyWithError:(id*)error;
-(void)dealloc;
-(id)init;
@end

