/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AirWatch-Structs.h"
#import <Foundation/NSObject.h>

@class NSString, NSMutableData;

@interface AWFileHandle : NSObject {
	NSMutableData* _buffer;
	sFILE* _fp;
	NSString* _path;
	NSString* _mode;
}
@property(copy, nonatomic) NSString* mode;
@property(copy, nonatomic) NSString* path;
+(id)fileHandleForWritingAtPath:(id)path;
+(id)fileHandleForReadingAtPath:(id)path;
-(void)closeFile;
-(unsigned long)seekToEndOfFile;
-(unsigned long)readDataOfLength:(unsigned long)length buffer:(void*)buffer;
-(unsigned long)writeData:(void*)data length:(unsigned long)length;
-(unsigned long)offsetInFile;
-(void)seekToFileOffset:(unsigned long)fileOffset;
-(BOOL)open;
@end

