/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSFileManager.h>

@class NSString;

@interface AWFileManager : NSFileManager {
	NSString* _documentsPath;
}
@property(retain, nonatomic) NSString* documentsPath;
+(id)defaultManager;
-(id)fileExtensionFromMIMEType:(id)mimetype;
-(BOOL)deleteDirectoryContents:(id)contents error:(id*)error;
-(id)tempDirectoryPath;
-(id)loggingDirectoryPath;
-(id)cachesDirectoryPath;
-(id)libraryDirectoryPath;
-(id)documentsDirectoryPath;
-(void)dealloc;
@end

