/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AirWatch-Structs.h"
#import "AWProfilePayload.h"

@class NSArray, NSString;

@interface AWGeofencePayload : AWProfilePayload {
	BOOL _isEnabled;
	NSString* _name;
	NSArray* _innerFenceEnterActions;
	NSArray* _innerFenceExitActions;
	NSArray* _middleFenceEnterActions;
	NSArray* _middleFenceExitActions;
	NSArray* _outerFenceEnterActions;
	NSArray* _outerFenceExitActions;
	NSArray* _geofenceAreas;
	double _innerFenceRadius;
	double _middleFenceRadius;
	double _outerFenceRadius;
	XXStruct_zYrK5D _centerCoordinate;
}
@property(readonly, assign, nonatomic) NSArray* geofenceAreas;
@property(readonly, assign, nonatomic) BOOL isEnabled;
@property(readonly, assign, nonatomic) NSArray* outerFenceExitActions;
@property(readonly, assign, nonatomic) NSArray* outerFenceEnterActions;
@property(readonly, assign, nonatomic) NSArray* middleFenceExitActions;
@property(readonly, assign, nonatomic) NSArray* middleFenceEnterActions;
@property(readonly, assign, nonatomic) NSArray* innerFenceExitActions;
@property(readonly, assign, nonatomic) NSArray* innerFenceEnterActions;
@property(readonly, assign, nonatomic) double outerFenceRadius;
@property(readonly, assign, nonatomic) double middleFenceRadius;
@property(readonly, assign, nonatomic) double innerFenceRadius;
@property(readonly, assign, nonatomic) XXStruct_zYrK5D centerCoordinate;
@property(readonly, assign, nonatomic) NSString* name;
+(id)payloadTypeV2;
+(id)payloadType;
-(id)parseActions:(id)actions;
-(void)dealloc;
-(id)initWithDictionary:(id)dictionary;
@end

