/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "GeofenceAreaChangeTransmissionDelegate.h"
#import <Foundation/NSObject.h>

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface AWGeofenceCommandProcessor : NSObject <GeofenceAreaChangeTransmissionDelegate> {
	BOOL _areaIsPresent;
	BOOL _transmissionisPending;
	NSMutableArray* _allGeofenceAreas;
}
@property(retain, nonatomic) NSMutableArray* allGeofenceAreas;
+(id)sharedInstance;
-(void)geofenceTransmission:(id)transmission failedWithError:(id)error;
-(void)geofenceTransmission:(id)transmission succeededWithRepsonseData:(id)repsonseData;
-(void)dealloc;
-(void)stopMonitoringGeofenceAreas;
-(id)createGeofenceTranmissionPayload:(id)payload;
-(void)sendEnterExitInfo:(id)info;
-(void)startMonitoringForGeofenceAreas;
-(void)getGeofenceProfileFromCommand:(id)command startMonitoringImmediately:(BOOL)immediately;
@end

