/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "CLLocationManagerDelegate.h"

@class AWGeofence, CLLocationManager;

@interface AWGeofenceService : NSObject <CLLocationManagerDelegate> {
	BOOL _hasGeneratedNotification;
	BOOL _isInsideGeofence;
	BOOL _isRunning;
	AWGeofence* _geofence;
	CLLocationManager* _locationManager;
	int _deviceGeofenceSection;
}
@property(readonly, assign, nonatomic) CLLocationManager* locationManager;
@property(assign, nonatomic) BOOL isRunning;
@property(assign, nonatomic) BOOL isInsideGeofence;
@property(assign, nonatomic) BOOL hasGeneratedNotification;
@property(readonly, assign, nonatomic) int deviceGeofenceSection;
@property(retain, nonatomic) AWGeofence* geofence;
+(id)sharedInstance;
-(id)actionsForExitingFence:(int)exitingFence;
-(id)actionsForEnteringFence:(int)enteringFence;
-(id)notificationUserInfoWithActions:(id)actions;
-(void)locationManager:(id)manager didUpdateToLocation:(id)location fromLocation:(id)location3;
-(void)setLocationManagerPurposeText:(id)text;
-(void)stop;
-(BOOL)start:(id*)start;
-(void)dealloc;
-(id)init;
@end

