/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AirWatch-Structs.h"
#import <Foundation/NSObject.h>

@class NSString;

@interface AWGeofenceArea : NSObject {
	NSString* _uniqueID;
	NSString* _name;
	double _radius;
	XXStruct_zYrK5D _center;
}
@property(readonly, assign, nonatomic) NSString* name;
@property(readonly, assign, nonatomic) NSString* uniqueID;
@property(readonly, assign, nonatomic) double radius;
@property(readonly, assign, nonatomic) XXStruct_zYrK5D center;
-(void)dealloc;
-(id)initWithInfo:(id)info;
@end

