/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class AWApplicationCommunication, AWCommunication, NSURL;
@protocol AWCommunicationDelegate, AWHandlerDelegate, AWPasscodeProtocol, AWPasscodeCreateProtocol, AWSessionCheckProtocol, AWSharedCommandProtocol, AWSSOStoreProtocol, AWHMACStoreProtocol, AWAccountStoreProtocol;

@interface AWHandler : NSObject {
	id _registrationCompletionHandler;
	id _sessionCompletionHandler;
	id<AWSharedCommandProtocol> _sharedCommandDelegate;
	id<AWCommunicationDelegate> _communicationDelegate;
	id<AWHandlerDelegate> _delegate;
	id<AWPasscodeCreateProtocol, AWSessionCheckProtocol> _sessionCheckDelegate;
	id<AWSSOStoreProtocol, AWHMACStoreProtocol, AWAccountStoreProtocol, AWPasscodeProtocol> _storeDelegate;
	NSURL* _requestURL;
	id _requestCompletionHandler;
	id _externaRequestCompletionHandler;
	id _appRegistrationCompletionHandler;
	AWApplicationCommunication* _appCommunication;
	AWCommunication* _communication;
}
@property(retain, nonatomic) AWCommunication* communication;
@property(retain, nonatomic) AWApplicationCommunication* appCommunication;
@property(copy, nonatomic) id appRegistrationCompletionHandler;
@property(copy, nonatomic) id externaRequestCompletionHandler;
@property(copy, nonatomic) id requestCompletionHandler;
@property(copy, nonatomic) NSURL* requestURL;
@property(assign, nonatomic) id<AWSSOStoreProtocol, AWHMACStoreProtocol, AWAccountStoreProtocol, AWPasscodeProtocol> storeDelegate;
@property(assign, nonatomic) id<AWPasscodeCreateProtocol, AWSessionCheckProtocol> sessionCheckDelegate;
@property(assign, nonatomic) id<AWHandlerDelegate> delegate;
@property(assign, nonatomic) id<AWCommunicationDelegate> communicationDelegate;
@property(assign, nonatomic) id<AWSharedCommandProtocol> sharedCommandDelegate;
+(void)registerGeneralHandler:(id)handler;
+(id)sharedInstance;
-(void)shouldLock;
-(void)registerWithCompletion:(id)completion;
-(BOOL)isSDKInitializedWithCompletion:(id)completion;
-(void)authenticateWithCompletion:(id)completion;
-(void)sendSessionResponse:(id)response forURL:(id)url;
-(BOOL)handleOpenURL:(id)url fromApplication:(id)application;
-(BOOL)canHandleURL:(id)url;
-(BOOL)clearPasscodeWithTime:(id)time WithCompletion:(id)completion;
-(BOOL)lockSessionWithTime:(id)time WithCompletion:(id)completion;
-(BOOL)checkSessionWithCompletion:(id)completion;
-(void)registerApplication:(id)application internalIdentifier:(id)identifier withCompletion:(id)completion;
-(void)registerThroughAnchorWithCompletion:(id)completion;
-(void)setUPCallBack;
-(void)dealloc;
@end

