/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


@interface AWHMACHelper : NSObject {
}
+(void)registerHMACStoreHandler:(id)handler;
+(void)setApplicationHMACKey:(id)key;
+(id)applicationHMACKey;
+(void)setUseSharedKey:(BOOL)key;
+(void)useHMACToSignRequest:(id)signRequest;
+(void)removeAllStoredHMAC;
+(void)setApplicationHMACKey:(id)key forAccount:(id)account;
+(id)applicationHMACKeyForAccount:(id)account;
+(void)setApplicationNonsharedHMACKey:(id)key;
+(id)applicationNonsharedHMACKey;
@end

