/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWURLConnectionOperation.h"
#import "AirWatch-Structs.h"

@class NSError, NSHTTPURLResponse;

@interface AWHTTPRequestOperation : AWURLConnectionOperation {
	BOOL _shouldIgnoreError;
	id _context;
	dispatch_queue_s* _failureCallbackQueue;
	dispatch_queue_s* _successCallbackQueue;
	NSHTTPURLResponse* _response;
	NSError* _HTTPError;
}
@property(assign, nonatomic) BOOL shouldIgnoreError;
@property(retain, nonatomic) NSError* HTTPError;
@property(assign, nonatomic) dispatch_queue_s* successCallbackQueue;
@property(assign, nonatomic) dispatch_queue_s* failureCallbackQueue;
@property(readonly, assign, nonatomic) NSHTTPURLResponse* response;
@property(retain, nonatomic) id context;
+(BOOL)canProcessRequest;
+(id)acceptableContentTypes;
+(id)acceptableStatusCodes;
-(void)terminateConnectionWithoutError;
-(void)setCompletionBlockWithSuccess:(id)success failure:(id)failure;
-(id)error;
-(BOOL)hasAcceptableContentType;
-(BOOL)hasAcceptableStatusCode;
-(void)URLConnection:(id)connection didReceiveResponse:(id)response;
@end

