/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AirWatch-Structs.h"
#import <Foundation/NSObject.h>

@class NSMutableDictionary, NSFileHandle;

@interface AWHTTPServer : NSObject {
	NSFileHandle* _listener;
	CFSocketRef _sharedSocket;
	unsigned _port;
	int _state;
	NSMutableDictionary* _requests;
}
@property(retain, nonatomic) NSMutableDictionary* requests;
@property(assign, nonatomic) int state;
@property(assign, nonatomic) unsigned port;
-(void)stop;
-(void)removeRequestHandle:(id)handle andClose:(BOOL)close;
-(void)readDataFromRequest:(id)request;
-(void)connectionReceivedNotfication:(id)notfication;
-(void)start;
-(void)dealloc;
-(id)init;
@end

