/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>
#import "AirWatch-Structs.h"

@class UIActivityIndicatorView, UILabel, NSTimer;

@interface AWHUDView : UIView {
	double dislpayTimeLimit;
	id _completionBlock;
	UIActivityIndicatorView* _activityIndicatorView;
	UILabel* _messageLabel;
	NSTimer* _dislpayTimer;
}
@property(retain, nonatomic) NSTimer* dislpayTimer;
@property(readonly, assign, nonatomic) UILabel* messageLabel;
@property(readonly, assign, nonatomic) UIActivityIndicatorView* activityIndicatorView;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)pulseAnimationDidComplete:(id)pulseAnimation finished:(id)finished context:(void*)context;
-(void)pulseShrinkAnimationDidStop:(id)pulseShrinkAnimation finished:(id)finished context:(void*)context;
-(void)pulseGrowAnimationDidStop:(id)pulseGrowAnimation finished:(id)finished context:(void*)context;
-(void)pulse;
-(void)showFromView:(id)view animated:(BOOL)animated completionBlock:(id)block;
-(void)hide;
-(void)updateLabel:(id)label;
-(void)showFromView:(id)view animated:(BOOL)animated displaTimerWithTime:(double)time;
-(void)showFromWindow:(id)window animated:(BOOL)animated;
-(void)showFromViewController:(id)viewController animated:(BOOL)animated centeredInView:(BOOL)view;
-(void)showFromView:(id)view animated:(BOOL)animated;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

