/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString;

@interface AWInterrogatorConnection : NSObject {
	NSString* _host;
	int _port;
}
@property(assign, nonatomic) int port;
@property(copy, nonatomic) NSString* host;
+(id)interrogatorConncetionWithHost:(id)host port:(int)port;
-(id)initWithHost:(id)host port:(int)port;
@end

