/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "AWDataSamplerHTTPTransmitterDelegate.h"
#import "AWDataSamplerTransmitterDelegate.h"

@class AWDataSamplerHTTPTransmitter, NSDictionary, AWDataSamplerTransmitter, NSTimer, AWDataSamplerConfiguration, NSMutableArray;

@interface AWInterrogator : NSObject <AWDataSamplerTransmitterDelegate, AWDataSamplerHTTPTransmitterDelegate> {
	BOOL g_AWInterrogatorIsInitialized;
	BOOL g_AWInterrogatorIsStarted;
	int _transmitType;
	BOOL sendGPSImmediate;
	NSDictionary* dataUsageObject;
	NSDictionary* callLogObject;
	AWDataSamplerConfiguration* dataSamplerConfig;
	NSMutableArray* sampleModulesArray;
	NSTimer* interrogatorTimer;
	double interrogatorTimeInterval;
	AWDataSamplerTransmitter* _xmitter;
	AWDataSamplerHTTPTransmitter* _httpxmitter;
}
@property(assign, nonatomic) BOOL sendGPSImmediate;
@property(assign, nonatomic) BOOL g_AWInterrogatorIsStarted;
@property(assign, nonatomic) BOOL g_AWInterrogatorIsInitialized;
+(void)sendGPSImmediate;
+(id)alloc;
+(id)mInterrogatorModule;
-(void)receivedGPSUpdate:(id)update;
-(void)dealloc;
-(void)SampleModules;
-(void)DataMessageSendFailed:(id)failed error:(id)error transmitter:(id)transmitter;
-(void)DataMessageSentSuccessfully:(id)successfully transmitter:(id)transmitter;
-(void)tick;
-(BOOL)TransmitGPS:(id*)gps delegate:(id)delegate;
-(BOOL)Transmit:(id*)transmit delegate:(id)delegate;
-(BOOL)shutDown:(id*)down;
-(BOOL)startUp:(id*)up;
-(id)initWithConfig:(id)config;
@end

