/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWDataSamplerSample.h"

@class NSString;

@interface AWInterrogatorWLan2Sample : AWDataSamplerSample {
	unsigned short SSIDLength;
	unsigned short adapterLength;
	NSString* MacAddress;
	unsigned short* RSSI;
	NSString* SSID;
	NSString* adapterName;
}
@property(assign, nonatomic) unsigned short adapterLength;
@property(retain, nonatomic) NSString* adapterName;
@property(assign, nonatomic) unsigned short SSIDLength;
@property(retain, nonatomic) NSString* SSID;
@property(assign, nonatomic) unsigned short* RSSI;
@property(retain, nonatomic) NSString* MacAddress;
-(void)dealloc;
-(id)getMACAddressBytes;
-(id)data;
-(void)sample;
-(id)init;
@end

