/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITableViewDelegate.h"
#import <UIKit/UIView.h>
#import "AirWatch-Structs.h"
#import "UITableViewDataSource.h"

@class UITableView;

@interface AWInitialView : UIView <UITableViewDataSource, UITableViewDelegate> {
	UITableView* _tableView;
}
@property(readonly, assign, nonatomic) UITableView* tableView;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)keyboardWillShowNotification:(id)keyboard;
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

