/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class AWDataSamplerPayload, NSData;

@interface AWInterrogatorPacket : NSObject {
	int _flags;
	NSData* _token;
	AWDataSamplerPayload* _payload;
	NSData* _payloadData;
}
@property(retain, nonatomic) NSData* payloadData;
@property(retain, nonatomic) AWDataSamplerPayload* payload;
@property(retain, nonatomic) NSData* token;
@property(assign, nonatomic) int flags;
-(id)data;
-(void)dealloc;
-(id)initWithData:(id)data;
-(id)initWithFlags:(int)flags token:(id)token payloadData:(id)data;
-(id)initWithFlags:(int)flags token:(id)token payload:(id)payload;
@end

