/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWScanner.h"


@interface AWJSONScanner : AWScanner {
}
-(BOOL)scanJSONNull:(id*)null;
-(BOOL)scanJSONBoolean:(id*)boolean;
-(BOOL)scanJSONNumber:(id*)number;
-(BOOL)scanJSONString:(id*)string;
-(BOOL)scanJSONArray:(id*)array;
-(BOOL)scanJSONDictionary:(id*)dictionary;
-(BOOL)scanJSONObject:(id*)object;
@end

