/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWButton.h"
#import "AirWatch-Structs.h"


@interface AWLargeButton : AWButton {
}
-(id)initWithFrame:(CGRect)frame;
@end

