/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>
#import "AirWatch-Structs.h"

@class UIColor;

@interface AWLinearGradientView : UIView {
	CGGradientRef _gradient;
	UIColor* _topColor;
	UIColor* _bottomColor;
}
@property(retain, nonatomic) UIColor* bottomColor;
@property(retain, nonatomic) UIColor* topColor;
-(void)drawRect:(CGRect)rect;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

