/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWProfilePayload.h"


@interface AWLoggingPayload : AWProfilePayload {
	BOOL _sendLogsOverWifiOnly;
	int _loggingLevel;
}
@property(readonly, assign, nonatomic) BOOL sendLogsOverWifiOnly;
@property(readonly, assign, nonatomic) int loggingLevel;
+(id)payloadTypeV2;
+(id)payloadType;
-(int)getLogTraceLevelFrom:(id)from;
-(int)getLogTraceLevel:(id)level;
-(id)initWithDictionary:(id)dictionary;
@end

