/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>

@class UILabel;

__attribute__((visibility("hidden")))
@interface AWLogDetailCell : UITableViewCell {
	UILabel* _logTypeLabel;
}
@property(retain, nonatomic) UILabel* logTypeLabel;
-(void)dealloc;
-(void)layoutSubviews;
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

