/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface AWLocalNotificationsScheduler : NSObject {
	int _localNotificationBadgeCount;
}
@property(assign) int localNotificationBadgeCount;
+(id)sharedInstance;
-(void)handleReceivedNotification:(id)notification;
-(void)decreaseBadgeCountBy:(int)by;
-(void)clearBadgeCount;
-(void)scheduleNotificationOn:(id)on text:(id)text action:(id)action sound:(id)sound launchImage:(id)image andInfo:(id)info;
@end

