/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>
#import "AirWatch-Structs.h"

@class UIImageView;

@interface AWLogoView : UIView {
	UIImageView* _logoImageView;
}
@property(retain, nonatomic) UIImageView* logoImageView;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame andLogoImage:(id)image;
@end

