/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface AWMailProfileManager : NSObject {
}
+(void)addCertifcateInfo:(id)info settings:(id)settings;
+(void)updateSettings:(id)settings;
+(void)launchClient;
+(void)preprocessSettings:(id)settings;
+(id)touchDownObjectForSettings:(id)settings;
@end

