/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "AWEncryptionKeyProtocol.h"

@class AWEnrollmentAccount, NSData, NSString;

@interface AWMasterKeyStore : NSObject <AWEncryptionKeyProtocol> {
	NSString* _context;
	unsigned _size;
	NSData* _key;
	AWEnrollmentAccount* _defaultAccount;
	BOOL _isOpen;
	BOOL _isRandom;
	NSString* _random;
	int _userID;
	NSData* _cryptKey;
	NSString* _pin;
}
@property(retain, nonatomic) NSString* pin;
@property(readonly, assign, nonatomic) NSString* random;
@property(retain, nonatomic) NSData* cryptKey;
@property(assign, nonatomic) int userID;
+(id)appInstance;
+(id)sharedInstance;
-(id)context;
-(void)moveDataFromContext:(id)context;
-(BOOL)removePin;
-(BOOL)loadWithPin:(id)pin;
-(BOOL)changeToPin:(id)pin handler:(id)handler;
-(BOOL)isStoredPinEqualToPin:(id)pin;
-(void)reset;
-(id)key;
-(id)idFor:(id)aFor service:(id)service;
-(id)randomKey;
-(void)setRandomKey:(id)key;
-(void)clear;
-(id)valueBasedKeyForLabel:(id)label label:(id)label2 salt:(id)salt;
-(void)createKeyForPin:(id)pin callback:(id)callback;
-(void)syncPinWithKey:(id)key key:(id)key2 cryptKey:(id)key3;
-(void)setUpWithPin:(id)pin handler:(id)handler;
-(id)generateKey;
-(id)initWithContext:(id)context;
-(void)dealloc;
@end

