/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <CoreData/NSManagedObject.h>

@class NSNumber, NSDate, NSString;

@interface AWMessageLog : NSManagedObject {
}
@property(retain, nonatomic) NSNumber* category;
@property(retain, nonatomic) NSNumber* sensitivity;
@property(retain, nonatomic) NSNumber* importance;
@property(retain, nonatomic) NSNumber* consoleMessageId;
@property(retain, nonatomic) NSDate* dateNotifiedToServer;
@property(retain, nonatomic) NSDate* dateRead;
@property(retain, nonatomic) NSDate* dateReceived;
@property(retain, nonatomic) NSNumber* status;
@property(retain, nonatomic) NSString* replyTo;
@property(retain, nonatomic) NSString* from;
@property(retain, nonatomic) NSString* messageText;
@property(retain, nonatomic) NSString* subject;
@property(retain, nonatomic) NSNumber* type;
@end

