/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIActionSheetDelegate.h"
#import "AWTableViewController.h"
#import "AWMessageLogDelete.h"
#import "NSFetchedResultsControllerDelegate.h"

@class NSArray, UILabel, NSString, UIBarButtonItem, NSFetchedResultsController, NSPredicate, NSManagedObjectContext, UIToolbar, UISegmentedControl, AWMessageLog, AWMessageDetailViewController;

@interface AWMessageViewController : AWTableViewController <AWMessageLogDelete, NSFetchedResultsControllerDelegate, UIActionSheetDelegate> {
	int _filter;
	BOOL _editMode;
	AWMessageDetailViewController* _messageDetailViewController;
	UISegmentedControl* _messageFilterControl;
	AWMessageLog* _selectedLog;
	NSArray* _toolBarButtons;
	UIBarButtonItem* _rightToolBarItem;
	NSArray* _filterToolBarButtons;
	UIToolbar* _toolBar;
	UIBarButtonItem* _editBarButtonItem;
	UIBarButtonItem* _doneBarButtonItem;
	NSFetchedResultsController* _fetchedResultsController;
	BOOL _goToDetailView;
	int _messageLogType;
	UILabel* _textLabel;
	NSString* _entityDescriptionString;
	NSPredicate* _entityPredicate;
	NSArray* _sortDescriptors;
	NSManagedObjectContext* _managedObjectContext;
	NSFetchedResultsController* _fetchedResultsControllerDefault;
	id _navBarDelegate;
	id _delegate;
	int _subMenuSelectIndex;
}
@property(assign, nonatomic) int subMenuSelectIndex;
@property(assign, nonatomic) int messageLogType;
@property(assign, nonatomic) id delegate;
@property(assign, nonatomic) id navBarDelegate;
@property(assign, nonatomic) BOOL goToDetailView;
@property(retain, nonatomic) NSManagedObjectContext* managedObjectContext;
@property(retain, nonatomic) NSPredicate* entityPredicate;
@property(retain, nonatomic) NSArray* sortDescriptors;
@property(retain, nonatomic) NSString* entityDescriptionString;
@property(retain, nonatomic) NSFetchedResultsController* fetchedResultsControllerDefault;
@property(retain, nonatomic) NSFetchedResultsController* fetchedResultsController;
-(id)textLabel;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)resetFetchedResultsController;
-(void)adjustTitle;
-(void)selectRowAtIndexPath:(id)indexPath animated:(BOOL)animated;
-(void)toggleEmptyView;
-(void)managedContextSaved:(id)saved;
-(void)markButtonTapped:(id)tapped;
-(void)deleteButtonTapped:(id)tapped;
-(void)messageFilterValueChanged:(id)changed;
-(void)editButtonTapped:(id)tapped;
-(void)configureToolBar;
-(void)updateTabItem;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)markMessage:(id)message;
-(void)previousMessage:(id)message;
-(void)nextMessage:(id)message;
-(void)deleteMessageLog:(id)log;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
-(BOOL)tableView:(id)view canEditRowAtIndexPath:(id)indexPath;
-(id)configureCell:(id)cell atIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(void)setBrandingColor:(id)color;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)dealloc;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidUnload;
-(void)viewDidLoad;
-(id)initWithStyle:(int)style;
@end

