/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSManagedObjectModel, NSPersistentStoreCoordinator, NSManagedObjectContext;

@interface AWMessageLogManager : NSObject {
	NSManagedObjectContext* _managedObjectContext;
	NSManagedObjectModel* _managedObjectModel;
	NSPersistentStoreCoordinator* _persistentStoreCoordinator;
	unsigned _messageHistoryLogDays;
}
@property(retain, nonatomic) NSPersistentStoreCoordinator* persistentStoreCoordinator;
@property(retain, nonatomic) NSManagedObjectModel* managedObjectModel;
@property(assign, nonatomic) unsigned messageHistoryLogDays;
@property(retain, nonatomic) NSManagedObjectContext* managedObjectContext;
+(id)sharedInstance;
-(void)resetManagedObjectContext;
-(int)unreadMessageCountForType:(int)type;
-(id)messageWithObjectID:(id)objectID;
-(void)setNotifiedDate:(id)date message:(id)message;
-(void)saveContext;
-(int)unreadMessageCount;
-(void)addInboundMessage:(id)message;
-(id)messageLogList;
-(void)deleteAllMessages;
-(void)deleteOldMessages;
-(void)deleteMessage:(id)message;
-(id)addMessage;
@end

