/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class AWHTTPServer;

@interface AWMediaHelper : NSObject {
	AWHTTPServer* _server;
}
@property(retain, nonatomic) AWHTTPServer* server;
-(id)modifiedURLForResourceURL:(id)resourceURL andMIMEType:(id)type;
-(id)init;
-(void)dealloc;
@end

