/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWTableViewController.h"

@class AWMessageViewController;

@interface AWMessageTypesViewController : AWTableViewController {
	BOOL _goToDetailView;
	AWMessageViewController* _messageViewController;
	int selectedRow;
	id _navBarDelegate;
}
@property(assign, nonatomic) BOOL goToDetailView;
@property(assign, nonatomic) id navBarDelegate;
-(void)managedContextSaved:(id)saved;
-(void)selectRowAtIndexPath:(id)indexPath animated:(BOOL)animated;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidUnload;
-(void)viewDidLoad;
-(void)didReceiveMemoryWarning;
-(id)initWithStyle:(int)style;
@end

