/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSMutableURLRequest.h>

@class NSData;

@interface AWMutableURLRequest : NSMutableURLRequest {
	BOOL _usePredeterminedToken;
	int _method;
	NSData* _signingKey;
}
@property(assign, nonatomic) BOOL usePredeterminedToken;
@property(retain, nonatomic) NSData* signingKey;
@property(assign, nonatomic) int method;
+(id)requestWithURL:(id)url cachePolicy:(unsigned)policy timeoutInterval:(double)interval;
+(id)requestWithURL:(id)url;
-(void)setValue:(id)value forHTTPHeaderFieldIfNotSet:(id)httpheaderFieldIfNotSet;
-(void)AW_addSignature;
-(void)dealloc;
-(id)initWithURL:(id)url cachePolicy:(unsigned)policy timeoutInterval:(double)interval;
-(id)initWithURL:(id)url;
-(id)initWithCoder:(id)coder;
-(id)init;
@end

