/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWMyDeviceInfoCell.h"
#import "AirWatch-Structs.h"

@class UIView;

__attribute__((visibility("hidden")))
@interface AWMyDeviceDetailInformationCell : AWMyDeviceInfoCell {
	UIView* cellContentView;
}
-(void)dealloc;
-(void)setBackgroundColor:(id)color;
-(void)setFrame:(CGRect)frame;
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

