/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>

@class UIImage, NSString;

__attribute__((visibility("hidden")))
@interface AWMyDeviceInfoCell : UITableViewCell {
	UIImage* _complianceIcon;
	NSString* _contact;
	NSString* _friendlyName;
	UIImage* _icon;
	NSString* _iOSVersion;
	UIImage* _jailbreakIcon;
	NSString* _model;
	NSString* _userName;
	UIImage* _enrollIcon;
	NSString* _enrollText;
	UIImage* _connectivityIcon;
	NSString* _complianceText;
	NSString* _connectivityText;
}
@property(copy) NSString* complianceText;
@property(copy) NSString* connectivityText;
@property(retain) UIImage* connectivityIcon;
@property(copy) NSString* enrollText;
@property(retain) UIImage* enrollIcon;
@property(copy) NSString* userName;
@property(copy) NSString* model;
@property(retain) UIImage* jailbreakIcon;
@property(copy) NSString* iOSVersion;
@property(retain) UIImage* icon;
@property(copy) NSString* friendlyName;
@property(copy) NSString* contact;
@property(retain) UIImage* complianceIcon;
-(void)dealloc;
@end

