/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UINavigationController.h>

@class UIColor;

__attribute__((visibility("hidden")))
@interface AWNavigationController : UINavigationController {
	UIColor* _titleColor;
}
@property(retain, nonatomic) UIColor* tintColor;
@property(retain, nonatomic) UIColor* titleColor;
@property(assign, nonatomic) int barStyle;
-(int)supportedInterfaceOrientations;
-(void)setViewControllers:(id)controllers;
-(void)pushViewController:(id)controller animated:(BOOL)animated;
-(id)popViewControllerAnimated:(BOOL)animated;
-(id)popToViewController:(id)viewController animated:(BOOL)animated;
-(id)popToRootViewControllerAnimated:(BOOL)rootViewControllerAnimated;
-(void)dealloc;
-(id)initWithRootViewController:(id)rootViewController;
-(id)init;
-(void)commonInit;
@end

