/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString;

@interface AWNetworkAdapter : NSObject {
	unsigned char _family;
	NSString* _name;
	NSString* _IPV4Address;
	NSString* _IPV6Address;
	NSString* _MACAddress;
	unsigned _sentBytes;
	unsigned _receivedBytes;
	unsigned _sentPackets;
	unsigned _receivedPackets;
	BOOL _isLoopback;
}
@property(assign, nonatomic) BOOL isLoopback;
@property(assign, nonatomic) unsigned receivedPackets;
@property(assign, nonatomic) unsigned sentPackets;
@property(assign, nonatomic) unsigned receivedBytes;
@property(assign, nonatomic) unsigned sentBytes;
@property(copy, nonatomic) NSString* MACAddress;
@property(copy, nonatomic) NSString* ipV6Address;
@property(copy, nonatomic) NSString* ipV4Address;
@property(copy, nonatomic) NSString* name;
@property(assign, nonatomic) unsigned char family;
-(id)info;
-(id)description;
-(void)dealloc;
@end

