/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol AWNetworkOperationDelegate <NSObject>
@optional
-(BOOL)networkOperation:(id)operation shouldAuthenticateAgainstProtectionSpace:(id)space;
-(void)networkOperationShouldRetry:(id)networkOperation;
-(void)networkOperation:(id)operation didReceiveAuthenticationChallenge:(id)challenge;
-(void)networkOperationDidFinish:(id)networkOperation;
-(void)networkOperationDidPause:(id)networkOperation;
-(void)networkOperation:(id)operation failedWithError:(id)error;
-(void)networkOperation:(id)operation receivedData:(id)data;
-(void)networkOperation:(id)operation didReceiveResponse:(id)response;
@end

