/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AirWatch-Structs.h"
#import <UIKit/UIControl.h>

@class UIImage, UIView, UILabel, UIImageView;

@interface AWOutlineThumbnailButton : UIControl {
	int _pageNumber;
	int _thumbnailFooterHeight;
	UIImage* _thumbnail;
	UILabel* _pageNumberLabel;
	UIImageView* _thumbnailImageView;
	UIView* _overlayView;
	UIImageView* _bookmarkImageView;
	UIView* _thumbnailDescription;
	CGRect _idealFrame;
}
@property(assign, nonatomic) CGRect idealFrame;
@property(retain, nonatomic) UIImageView* bookmarkImageView;
@property(readonly, assign, nonatomic) UIView* overlayView;
@property(readonly, assign, nonatomic) UIImageView* thumbnailImageView;
@property(readonly, assign, nonatomic) UILabel* pageNumberLabel;
@property(readonly, assign, nonatomic) UIView* thumbnailDescription;
@property(retain, nonatomic) UIImage* thumbnail;
@property(assign, nonatomic) int thumbnailFooterHeight;
@property(assign, nonatomic) int pageNumber;
-(void)layoutSubviews;
-(void)resetBookmark;
-(void)setBookmarkDescriptionText:(id)text withOptionalDetailText:(id)optionalDetailText;
-(void)setHighlighted:(BOOL)highlighted;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

