/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


@interface AWPasscodeHandler : NSObject {
}
+(void)setPasscodeSSODelegate:(id)delegate;
+(void)setPasscodeDelegate:(id)delegate;
+(BOOL)isDevicePassocdeCompliant;
+(BOOL)changePasscodeFromOldValue:(id)oldValue tonNew:(id)aNew;
+(BOOL)enterpriseWipe;
+(BOOL)isSSOEnabled;
+(BOOL)supportsUnlimitedPasscodeAttempts;
+(int)noOfPasscodeAttempts;
+(int)passcodeAttempsLeft;
+(void)updatePasscodeFailedAttempts:(int)attempts;
+(int)passcodeFailedAttempts;
+(void)saveSessionInfo;
+(int)passcodeMode;
+(double)getTimeOutInterval;
+(BOOL)maximumAttemptsPolicy:(id)policy;
+(void)clearPasscodeHistory;
+(BOOL)checkPasscodeHistoryisCompliant:(id)compliant;
+(BOOL)savedPasscodeIsAplhaNumeric;
+(BOOL)minimumComplexCharPolicy:(id)policy withMessage:(BOOL)message;
+(BOOL)minimumLengthPolicy:(id)policy withMessage:(BOOL)message;
+(BOOL)numericPasscodePolicy:(id)policy withMessage:(BOOL)message;
+(BOOL)alphanumericPasscodePolicy:(id)policy withMessage:(BOOL)message;
+(BOOL)simplePasscodePolicy:(id)policy withMessage:(BOOL)message;
+(BOOL)isPasscodeSet;
+(BOOL)passcodeRequired;
+(BOOL)isPasscodeRequired:(id)required;
+(void)evaluateSSOSessionWithCompletion:(id)completion;
+(void)showChangePasscodeView:(id)view;
+(void)showClearPasscodeView:(id)view;
+(void)showPasscodeLockView:(id)view;
+(void)showPasscodeLockView:(BOOL)view handler:(id)handler;
+(void)checkPassocodeAgeComplianceWithCompletion:(id)completion;
+(void)checkPasscodeComplianceWithCompletionBlock:(id)completionBlock;
+(void)removeSetPasscode;
+(BOOL)isDevicePassocdeCompliant:(BOOL)compliant;
+(id)getplainTextPasscode;
+(void)savePlainText:(id)text;
+(BOOL)checkPasscodeValidity:(id)validity;
+(BOOL)clearPasscode;
+(void)savePasscode:(id)passcode;
@end

