/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIScrollViewDelegate.h"
#import "AirWatch-Structs.h"
#import <UIKit/UIScrollView.h>

@class NSString;

@interface AWPageView : UIScrollView <UIScrollViewDelegate> {
	BOOL _isValid;
	unsigned _pageNumber;
	NSString* _highlightText;
}
@property(assign) BOOL isValid;
@property(retain, nonatomic) NSString* highlightText;
@property(readonly, assign, nonatomic) unsigned pageNumber;
-(void)dealloc;
-(id)pageRenderWithSize:(CGSize)size andScale:(float)scale;
-(id)initWithFrame:(CGRect)frame;
@end

