/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


@interface AWPasteboard : NSObject {
}
-(id)AWServer;
-(void)setAWServer:(id)server;
-(id)DSURL;
-(void)setDSURL:(id)dsurl;
-(void)dealloc;
-(id)init;
@end

