/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AirWatch-Structs.h"
#import "UIScrollViewDelegate.h"
#import "AWPageView.h"

@class UIImageView, AWDocumentContainerView, UIView, AWTiledPDFPageView, NSString;

@interface AWPDFPageView : AWPageView <UIScrollViewDelegate> {
	AWTiledPDFPageView* pdfView;
	UIView* container;
	CGPDFPageRef _pageRef;
	CGPDFDocumentRef _documentRef;
	CGRect pageRect;
	float pageScale;
	AWPDFPageView* blockSelf;
	dispatch_queue_s* queue;
	unsigned _pageNumber;
	NSString* _keyword;
	UIView* _bookmarkView;
	AWDocumentContainerView* _containerView;
	UIImageView* lowResImageView;
}
@property(readonly, assign, nonatomic) UIImageView* lowResImageView;
@property(assign, nonatomic) AWDocumentContainerView* containerView;
@property(retain, nonatomic) UIView* bookmarkView;
@property(copy, nonatomic) NSString* keyword;
@property(readonly, assign, nonatomic) unsigned pageNumber;
-(CGPDFArrayRef)destinationWithName:(const char*)name inDestsTree:(CGPDFDictionaryRef)destsTree;
-(int)annotationLinkTarget:(CGPDFDictionaryRef)target;
-(CGPDFArrayRef)findDestinationWithName:(const char*)name inDestsTree:(CGPDFDictionaryRef)destsTree;
-(id)findLinkTarget:(CGPDFDictionaryRef)target;
-(CGPoint)convertPDFPointToViewPoint:(CGPoint)viewPoint forView:(id)view;
-(void)addPDFLinksToView:(id)view;
-(CGRect)calcPageRect;
-(id)initialPageRender;
-(id)viewForZoomingInScrollView:(id)scrollView;
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
-(void)dealloc;
-(void)layoutSubviews;
-(void)applicationDidReceiveMemoryWarningNotification:(id)application;
-(id)initWithFrame:(CGRect)frame document:(CGPDFDocumentRef)document pageNumber:(unsigned)number dispatchQueue:(dispatch_queue_s*)queue;
@end

