/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString;

@interface AWPDFSearchResult : NSObject {
	BOOL _pageIsCollapsed;
	NSString* _previewText;
	int _pageNumber;
}
@property(assign, nonatomic) BOOL pageIsCollapsed;
@property(assign, nonatomic) int pageNumber;
@property(retain, nonatomic) NSString* previewText;
-(void)dealloc;
@end

