/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "AirWatch-Structs.h"
#import "NSObject.h"

@class AWDocumentTOCNode;

@interface AWPDFOutlineController : NSObject <NSObject> {
	AWDocumentTOCNode* _rootNode;
}
@property(retain, nonatomic) AWDocumentTOCNode* rootNode;
+(id)outlineEntryTarget:(CGPDFDictionaryRef)target document:(CGPDFDocumentRef)document;
+(CGPDFArrayRef)destinationWithName:(const char*)name inDestsTree:(CGPDFDictionaryRef)destsTree;
+(void)logDocumentOutlineArray:(id)array;
-(id)rootDocumentNode:(CGPDFDocumentRef)node withPassword:(id)password;
-(void)outlineItems:(CGPDFDictionaryRef)items document:(CGPDFDocumentRef)document parentEntry:(id)entry array:(id)array level:(int)level;
@end

