/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AirWatch-Structs.h"
#import <Foundation/NSObject.h>

@class NSMutableArray, AWPDFFont, AWPDFFontCollection, AWPDFSearchRenderingState, NSString, AWPDFSearchSelection, NSMutableString;
@protocol AWPDFSearcherDelegate;

@interface AWPDFSearcher : NSObject {
	CGPDFOperatorTableRef _operatorTable;
	CGPDFDocumentRef _document;
	CGPDFPageRef _page;
	int skipCharNum;
	NSMutableString* needleString;
	NSMutableString* accumulatorString;
	BOOL isAccumulatingString;
	BOOL _ignoreRenderElements;
	id<AWPDFSearcherDelegate> _delegate;
	NSString* _keyword;
	NSMutableArray* _selections;
	AWPDFSearchSelection* _currentSelection;
	AWPDFSearchRenderingState* _currentRenderingState;
	AWPDFFont* _currentFont;
	NSMutableArray* _renderingStateStack;
	AWPDFFontCollection* _fontCollection;
	NSMutableString* _previewBuffer;
	NSMutableString* _unicodeContent;
	unsigned _keywordPosition;
}
@property(assign, nonatomic) unsigned keywordPosition;
@property(retain, nonatomic) NSMutableString* unicodeContent;
@property(retain, nonatomic) NSMutableString* previewBuffer;
@property(retain, nonatomic) AWPDFFontCollection* fontCollection;
@property(readonly, assign, nonatomic) NSMutableArray* renderingStateStack;
@property(retain, nonatomic) AWPDFFont* currentFont;
@property(retain, nonatomic) AWPDFSearchRenderingState* currentRenderingState;
@property(assign, nonatomic) BOOL ignoreRenderElements;
@property(retain, nonatomic) AWPDFSearchSelection* currentSelection;
@property(retain, nonatomic) NSMutableArray* selections;
@property(copy, nonatomic) NSString* keyword;
@property(assign, nonatomic) id<AWPDFSearcherDelegate> delegate;
-(void)appendToPreview:(id)preview;
-(void)resetPreview;
-(void)stringByExpandingLigatures:(id*)ligatures font:(id)font;
-(void)resetScanState;
-(id)appendPDFString:(CGPDFStringRef)string withFont:(id)font;
-(BOOL)append:(id)append font:(id)font;
-(unsigned short)nextCharacter;
-(void)didScanSpace:(float)space;
-(void)didScanString:(CGPDFStringRef)string;
-(void)didStartMatchingString;
-(void)didFindString;
-(void)didScanCharacter:(unsigned short)character;
-(id)fontDescriptionsForPage:(CGPDFPageRef)page;
-(id)textForPage:(CGPDFPageRef)page;
-(void)scanPage:(CGPDFPageRef)page;
-(id)fontCollectionWithPage:(CGPDFPageRef)page;
-(CGPDFOperatorTableRef)operatorTable;
-(void)reset;
-(void)dealloc;
-(id)init;
-(id)initWithDocument:(CGPDFDocumentRef)document;
@end

