/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIViewController.h>
#import "AirWatch-Structs.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UISearchBarDelegate.h"
#import "AWPDFSearcherDelegate.h"

@class AWDocumentContainerView, NSMutableArray, AWPDFSearcher, UISearchBar, UIView, NSMutableDictionary, UITableView, AWPDFDocument, UIToolbar, UIActivityIndicatorView, UILabel;
@protocol AWPDFSearchViewControllerDelegate;

@interface AWPDFSearchViewController : UIViewController <UITableViewDataSource, UITableViewDelegate, UISearchBarDelegate, AWPDFSearcherDelegate> {
	UIActivityIndicatorView* _spin;
	AWPDFSearcher* _scanner;
	dispatch_queue_s* queue;
	BOOL _isSearching;
	BOOL _hasLoopBacked;
	BOOL _isCollapsed;
	BOOL _isInteruped;
	BOOL _isSortedByPage;
	BOOL _forceBackgroundSearch;
	id<AWPDFSearchViewControllerDelegate> _delegate;
	AWPDFDocument* _document;
	AWDocumentContainerView* _viewer;
	UITableView* _tableView;
	int _startPageIndex;
	UISearchBar* _searchBar;
	NSMutableArray* _results;
	int _pageProgress;
	NSMutableDictionary* _defaultSettings;
	UIView* _pageProgressView;
	UILabel* _pageProgressLabel;
	UIToolbar* _searchOptionView;
}
@property(retain, nonatomic) UILabel* pageProgressLabel;
@property(retain, nonatomic) UIView* pageProgressView;
@property(assign, nonatomic) BOOL forceBackgroundSearch;
@property(assign, nonatomic) BOOL isSortedByPage;
@property(assign, nonatomic) BOOL isInteruped;
@property(assign, nonatomic) BOOL isCollapsed;
@property(retain, nonatomic) NSMutableDictionary* defaultSettings;
@property(retain, nonatomic) UIToolbar* searchOptionView;
@property(assign, nonatomic) BOOL hasLoopBacked;
@property(assign, nonatomic) int pageProgress;
@property(retain, nonatomic) NSMutableArray* results;
@property(assign, nonatomic) BOOL isSearching;
@property(retain, nonatomic) UISearchBar* searchBar;
@property(assign, nonatomic) int startPageIndex;
@property(retain, nonatomic) UITableView* tableView;
@property(assign, nonatomic) AWDocumentContainerView* viewer;
@property(retain, nonatomic) AWPDFDocument* document;
@property(assign, nonatomic) id<AWPDFSearchViewControllerDelegate> delegate;
-(BOOL)searchComplete;
-(void)toggleReviewMode;
-(BOOL)isCollapsed:(int)collapsed;
-(int)pageNumberFromSection:(int)section;
-(int)numberOfHitFromSection:(int)section;
-(void)sortResultSet:(id)set;
-(void)insertSectionAtEnd;
-(void)arrangeByHitRankForSection:(id)section;
-(id)sectionResultForPage:(int)page inResultSet:(id)resultSet;
-(void)updateTableViewWithNewResult:(id)newResult;
-(void)updateTableView;
-(void)setIsLoading:(BOOL)loading;
-(void)completeReset;
-(void)resetDataStructure;
-(void)resumeSearch;
-(void)pauseSearch;
-(void)dismissKeyboard;
-(void)setAlphaForPopover:(float)popover;
-(void)handleTwoFingferTap:(id)tap;
-(void)toggleSortBy:(id)by;
-(void)toggleAllSection:(id)section;
-(void)toggleSection:(id)section;
-(void)setRightBarButtonTitleForStatus:(int)status;
-(void)setRightBarButtonTitle:(id)title;
-(BOOL)shouldManuallyResizePopover;
-(void)resizePopoverViewOnKeyboardDimiss:(id)dimiss;
-(void)refreshUIFrame;
-(void)setSearchBarTintColor:(id)color;
-(id)greyGradient;
-(void)scrollViewWillBeginDragging:(id)scrollView;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view viewForHeaderInSection:(int)section;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)searchBar:(id)bar textDidChange:(id)text;
-(void)searchBarSearchButtonClicked:(id)clicked;
-(void)searchBarCancelButtonClicked:(id)clicked;
-(BOOL)searchBarShouldBeginEditing:(id)searchBar;
-(void)scanner:(id)scanner didFailToScanPage:(CGPDFPageRef)scanPage;
-(void)scanner:(id)scanner didFinishScanningPage:(CGPDFPageRef)page;
-(void)scanner:(id)scanner didFindTextOnPage:(CGPDFPageRef)page;
-(void)scanDocumentForText:(id)text startingPage:(unsigned)page;
-(void)scanDocumentForText:(id)text;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidUnload;
-(void)viewDidLoad;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
-(void)didReceiveMemoryWarning;
-(void)dealloc;
-(void)reset;
@end

