/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "AirWatch-Structs.h"

@class NSString, AWPDFSearchRenderingState;

@interface AWPDFSearchSelection : NSObject {
	BOOL _pageIsCollapsed;
	AWPDFSearchRenderingState* _initialState;
	NSString* _previewText;
	unsigned _pageNumber;
	CGRect _frame;
	CGAffineTransform _transform;
}
@property(copy, nonatomic) AWPDFSearchRenderingState* initialState;
@property(assign, nonatomic) BOOL pageIsCollapsed;
@property(copy, nonatomic) NSString* previewText;
@property(assign, nonatomic) unsigned pageNumber;
@property(readonly, assign, nonatomic) CGRect frame;
@property(readonly, assign, nonatomic) CGAffineTransform transform;
-(void)finalizeWithState:(id)state;
-(void)dealloc;
-(id)initWithStartState:(id)startState;
@end

