/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "AirWatch-Structs.h"
#import "NSCopying.h"

@class AWPDFFont;

@interface AWPDFSearchRenderingState : NSObject <NSCopying> {
	float _characterSpacing;
	float _wordSpacing;
	float _leading;
	float _textRise;
	float _horizontalScaling;
	AWPDFFont* _font;
	float _fontSize;
	CGAffineTransform _lineMatrix;
	CGAffineTransform _textMatrix;
	CGAffineTransform _ctm;
}
@property(assign, nonatomic) float fontSize;
@property(retain, nonatomic) AWPDFFont* font;
@property(assign, nonatomic) float horizontalScaling;
@property(assign, nonatomic) float textRise;
@property(assign, nonatomic) float leading;
@property(assign, nonatomic) float wordSpacing;
@property(assign, nonatomic) float characterSpacing;
@property(assign, nonatomic) CGAffineTransform ctm;
@property(assign, nonatomic) CGAffineTransform textMatrix;
@property(assign, nonatomic) CGAffineTransform lineMatrix;
-(float)convertFloatToUserSpace:(float)userSpace;
-(CGSize)convertSizeToUserSpace:(CGSize)userSpace;
-(void)newLine;
-(void)newLineWithLeading:(float)leading save:(BOOL)save;
-(void)newLineWithLeading:(float)leading indent:(float)indent save:(BOOL)save;
-(void)translateTextPosition:(CGSize)position;
-(void)setTextMatrix:(CGAffineTransform)matrix replaceLineMatrix:(BOOL)matrix2;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
-(id)init;
@end

