/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "AirWatch-Structs.h"

@class NSDictionary, AWPDFCMap, AWPDFFontDescriptor, NSMutableDictionary;

@interface AWPDFFont : NSObject {
	AWPDFCMap* _cmap;
	NSMutableDictionary* _widths;
	AWPDFFontDescriptor* _fontDescriptor;
	float _minY;
	float _maxY;
	NSDictionary* _ligatures;
	float _widthOfSpace;
	NSRange _widthsRange;
}
@property(readonly, assign, nonatomic) float widthOfSpace;
@property(assign, nonatomic) NSRange widthsRange;
@property(readonly, assign, nonatomic) NSDictionary* ligatures;
@property(readonly, assign, nonatomic) float maxY;
@property(readonly, assign, nonatomic) float minY;
@property(retain, nonatomic) AWPDFFontDescriptor* fontDescriptor;
@property(retain, nonatomic) NSMutableDictionary* widths;
@property(retain, nonatomic) AWPDFCMap* cmap;
+(id)fontWithDictionary:(CGPDFDictionaryRef)dictionary;
-(void)setWidthsWithFontDictionary:(CGPDFDictionaryRef)fontDictionary;
-(void)setToUnicodeWithFontDictionary:(CGPDFDictionaryRef)fontDictionary;
-(void)setFontDescriptorWithFontDictionary:(CGPDFDictionaryRef)fontDictionary;
-(float)widthOfSpaceWithFontSize:(float)fontSize;
-(id)stringWithPDFString:(CGPDFStringRef)pdfstring;
-(id)cidWithPDFString:(CGPDFStringRef)pdfstring;
-(float)widthOfCharacter:(unsigned short)character withFontSize:(float)fontSize;
-(void)dealloc;
-(id)initWithDictionary:(CGPDFDictionaryRef)dictionary;
@end

