/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AirWatch-Structs.h"
#import <Foundation/NSObject.h>

@class NSMutableDictionary, NSMutableArray;

@interface AWPDFCMap : NSObject {
	NSMutableArray* _offsets;
	NSMutableDictionary* _characters;
}
@property(readonly, assign, nonatomic) NSMutableDictionary* characters;
@property(readonly, assign, nonatomic) NSMutableArray* offsets;
-(id)rangeWithCharacter:(unsigned short)character;
-(void)scanCMap:(id)map;
-(void)scanRanges:(id)ranges;
-(void)scanCharacters:(id)characters;
-(void)scanCodeSpaceRange:(id)range;
-(void)scanText:(id)text;
-(unsigned short)unicodeCharacter:(unsigned short)character;
-(void)dealloc;
-(id)initWithPDFStream:(CGPDFStreamRef)pdfstream;
@end

