/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AirWatch-Structs.h"
#import <Foundation/NSObject.h>

@class NSMutableDictionary, NSArray;

@interface AWPDFFontCollection : NSObject {
	NSMutableDictionary* _fonts;
	NSArray* _names;
}
@property(readonly, assign, nonatomic) NSArray* names;
@property(readonly, assign, nonatomic) NSMutableDictionary* fonts;
-(id)fontsByName;
-(id)fontNamed:(id)named;
-(void)dealloc;
-(id)initWithFontDictionary:(CGPDFDictionaryRef)fontDictionary;
@end

