/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSData, NSURL, NSString, NSURLCache;
@protocol AWProxyDelegate;

@interface AWProxy : NSObject {
	BOOL isRequestingCert;
	BOOL _isEnabled;
	BOOL _requiresAuth;
	BOOL _usePublicMAGCert;
	BOOL _shouldSignRequests;
	id<AWProxyDelegate> _delegate;
	int _type;
	NSString* _host;
	int _httpPort;
	int _httpsPort;
	NSURLCache* _sharedProxyCache;
	NSString* _username;
	NSString* _password;
	NSURL* _autoConfigURL;
	int _f5ProxyAuthType;
	NSData* _p12CertDataForF5;
	NSString* _passPhraseForF5Cert;
	NSString* _userPassProxyCredential;
	NSString* _proxyAutoConfigScript;
}
@property(copy, nonatomic) NSString* proxyAutoConfigScript;
@property(copy, nonatomic) NSString* userPassProxyCredential;
@property(copy, nonatomic) NSString* passPhraseForF5Cert;
@property(retain, nonatomic) NSData* p12CertDataForF5;
@property(assign, nonatomic) int f5ProxyAuthType;
@property(assign, nonatomic) BOOL shouldSignRequests;
@property(assign, nonatomic) BOOL usePublicMAGCert;
@property(retain, nonatomic) NSURL* autoConfigURL;
@property(copy, nonatomic) NSString* password;
@property(copy, nonatomic) NSString* username;
@property(assign, nonatomic) BOOL requiresAuth;
@property(retain, nonatomic) NSURLCache* sharedProxyCache;
@property(assign, nonatomic) int httpsPort;
@property(assign, nonatomic) int httpPort;
@property(copy, nonatomic) NSString* host;
@property(readonly, assign, nonatomic) BOOL isEnabled;
@property(assign, nonatomic) int type;
@property(assign, nonatomic) id<AWProxyDelegate> delegate;
+(id)sharedInstance;
-(id)description;
-(BOOL)checkMAGCert;
-(void)fetchMAGCertificate:(id)certificate;
-(void)stop;
-(BOOL)start:(id*)start;
-(BOOL)isF5Configured;
-(BOOL)isConfigured;
-(void)configureF5ProxyWithHost:(id)host port:(int)port authType:(int)type userName:(id)name password:(id)password certData:(id)data passPhrase:(id)phrase;
-(void)configureWithHost:(id)host httpPort:(int)port httpsPort:(int)port3 serverType:(int)type;
-(void)dealloc;
-(id)init;
-(BOOL)setProxySettingsForURL:(id)url;
-(BOOL)fetchPACFile:(id*)file;
-(id)userPassFromUser:(id)user andPass:(id)pass;
-(id)getUserPassProxyCredential;
@end

