/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "AWNetworkConnectionDelegate.h"

@class NSString;
@protocol AWProfileRetrieverDelegate;

@interface AWProfileRetriever : NSObject <AWNetworkConnectionDelegate> {
	id<AWProfileRetrieverDelegate> _delegate;
	int _configurationProfileType;
	NSString* _locationGroup;
}
@property(copy, nonatomic) NSString* locationGroup;
@property(readonly, assign, nonatomic) int configurationProfileType;
@property(assign, nonatomic) id<AWProfileRetrieverDelegate> delegate;
-(id)queryStringForSettingEndpoint;
-(void)networkConnection:(id)connection failedWithError:(id)error;
-(void)networkConnection:(id)connection receivedResponseData:(id)data;
-(void)fetchConfigurationProfile:(int)profile;
-(void)dealloc;
@end

