/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


@interface AWProxyCertService : NSObject {
}
+(BOOL)removeSigningCertificate;
+(id)signingCertificate;
+(BOOL)storeSigningCertificate:(id)certificate;
+(id)baseRequest;
+(id)extractCertFromResponseData:(id)responseData outError:(id*)error;
+(id)bodyData;
+(void)fetchAndStoreCertWithCompletion:(id)completion;
+(void)fetchCertUsingRequest:(id)request withCompletion:(id)completion;
+(void)fetchAndStoreCert:(id)cert withCompletion:(id)completion;
@end

