/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol AWProfileRetrieverDelegate <NSObject>
-(void)profileRetriever:(id)retriever succeededWithResponseData:(id)responseData;
-(void)profileRetriever:(id)retriever failedWithError:(id)error;
@end

