/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWProfilePayload.h"

@class NSNumber, NSString, NSArray;

@interface AWProxyPayload : AWProfilePayload {
	BOOL _redirectTraffic;
	BOOL _publicSSL;
	BOOL _f5Integration;
	BOOL _f5UseAuthentication;
	BOOL _standardProxyUseAuth;
	BOOL _standardProxyAutoConfig;
	BOOL _isV2;
	int _proxyType;
	NSString* _hostName;
	NSNumber* _httpPort;
	NSNumber* _httpsPort;
	NSNumber* _f5Port;
	NSString* _f5Host;
	NSNumber* _f5UserAccountType;
	NSString* _f5UserAccountName;
	NSString* _f5UserAccountPassword;
	int _f5AuthenticationMode;
	NSArray* _appTunnelDomains;
	NSString* _standardProxyUsername;
	NSString* _standardProxyPassword;
	NSString* _standardProxyAutoConfigURL;
}
@property(assign, nonatomic) BOOL isV2;
@property(readonly, assign, nonatomic) NSString* standardProxyAutoConfigURL;
@property(assign, nonatomic) BOOL standardProxyAutoConfig;
@property(readonly, assign, nonatomic) NSString* standardProxyPassword;
@property(readonly, assign, nonatomic) NSString* standardProxyUsername;
@property(assign, nonatomic) BOOL standardProxyUseAuth;
@property(readonly, assign, nonatomic) NSArray* appTunnelDomains;
@property(readonly, assign, nonatomic) int f5AuthenticationMode;
@property(readonly, assign, nonatomic) NSString* f5UserAccountPassword;
@property(readonly, assign, nonatomic) NSString* f5UserAccountName;
@property(readonly, assign, nonatomic) NSNumber* f5UserAccountType;
@property(readonly, assign, nonatomic) BOOL f5UseAuthentication;
@property(readonly, assign, nonatomic) NSString* f5Host;
@property(readonly, assign, nonatomic) NSNumber* f5Port;
@property(readonly, assign, nonatomic) BOOL f5Integration;
@property(readonly, assign, nonatomic) BOOL publicSSL;
@property(retain, nonatomic) NSNumber* httpsPort;
@property(retain, nonatomic) NSNumber* httpPort;
@property(retain, nonatomic) NSString* hostName;
@property(assign, nonatomic) BOOL redirectTraffic;
@property(assign, nonatomic) int proxyType;
+(id)payloadTypeV2;
+(id)payloadType;
-(id)initWithDictionary:(id)dictionary;
@end

