/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@protocol AWProxySetupDelegate;

@interface AWProxyHandler : NSObject {
	BOOL _isSettingUpProxy;
	id<AWProxySetupDelegate> _delegate;
	id _completionBlock;
}
@property(copy, nonatomic) id completionBlock;
@property(assign, nonatomic) id<AWProxySetupDelegate> delegate;
+(BOOL)URLRegex:(id)regex matchesRequestString:(id)string;
+(BOOL)domain:(id)domain matchesRequest:(id)request;
+(id)sharedInstance;
-(void)returnWithSuccess:(BOOL)success andError:(id)error;
-(void)setupProxy:(id)proxy withCompletion:(id)completion;
@end

