/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWProfilePayload.h"

@class NSString, NSArray;

@interface AWRestrictionsPayload : AWProfilePayload {
	BOOL _isOfflineModeAllowed;
	BOOL _isMDMEnrollmentRequired;
	BOOL _preventCopyAndCut;
	BOOL _restrictDocumentToApps;
	BOOL _printingEnabled;
	BOOL _enableDataLossPrevention;
	BOOL _enableWatermark;
	BOOL _isV2;
	int _maximumOfflineUses;
	NSArray* _offlineOverLimitActions;
	NSArray* _deviceNotEnrolledActions;
	NSArray* _restrictedApplications;
	NSArray* _allowedApplications;
	NSString* _watermarkOverlay;
	long long _maximumAllowedOfflineDuration;
}
@property(assign, nonatomic) BOOL isV2;
@property(readonly, assign, nonatomic) NSString* watermarkOverlay;
@property(readonly, assign, nonatomic) BOOL enableWatermark;
@property(readonly, assign, nonatomic) BOOL enableDataLossPrevention;
@property(readonly, assign, nonatomic) BOOL printingEnabled;
@property(readonly, assign, nonatomic) NSArray* allowedApplications;
@property(readonly, assign, nonatomic) NSArray* restrictedApplications;
@property(readonly, assign, nonatomic) BOOL restrictDocumentToApps;
@property(readonly, assign, nonatomic) BOOL preventCopyAndCut;
@property(readonly, assign, nonatomic) NSArray* deviceNotEnrolledActions;
@property(readonly, assign, nonatomic) BOOL isMDMEnrollmentRequired;
@property(readonly, assign, nonatomic) NSArray* offlineOverLimitActions;
@property(readonly, assign, nonatomic) int maximumOfflineUses;
@property(readonly, assign, nonatomic) long long maximumAllowedOfflineDuration;
@property(readonly, assign, nonatomic) BOOL isOfflineModeAllowed;
+(id)payloadTypeV2;
+(id)payloadType;
-(id)parseActions:(id)actions;
-(id)initWithDictionary:(id)dictionary;
@end

