/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@protocol remoteViewTransmitterDelegate;

@interface AWRemoteViewTransmitter : NSObject {
	BOOL _isTransmitting;
	id<remoteViewTransmitterDelegate> _delegate;
}
@property(assign, nonatomic) id<remoteViewTransmitterDelegate> delegate;
@property(readonly, assign, nonatomic) BOOL isTransmitting;
-(void)connectionDidFinishLoading:(id)connection;
-(void)connection:(id)connection didFailWithError:(id)error;
-(void)transmitImage:(id)image;
-(void)dealloc;
@end

