/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString;

@interface AWRepositoryQuotaInfo : NSObject {
	NSString* _userName;
	int _userID;
	NSString* _locationGroupName;
	int _repositoryID;
	long long _totalContentCapacity;
	long long _allowedOverage;
	long long _maximumFileSize;
	long long _usedBytes;
}
@property(assign, nonatomic) long long usedBytes;
@property(assign, nonatomic) long long maximumFileSize;
@property(assign, nonatomic) long long allowedOverage;
@property(assign, nonatomic) long long totalContentCapacity;
@property(assign, nonatomic) int repositoryID;
@property(copy, nonatomic) NSString* locationGroupName;
@property(assign, nonatomic) int userID;
@property(copy, nonatomic) NSString* userName;
-(void)dealloc;
@end

