/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWDataSamplerPayload.h"

@class NSString;

@interface AWReadyMessagePayload : AWDataSamplerPayload {
	int _platform;
	NSString* _udid;
}
@property(copy, nonatomic) NSString* udid;
@property(assign, nonatomic) int platform;
-(id)data;
-(void)dealloc;
-(id)initWithData:(id)data;
-(id)initWithPlatform:(int)platform UDID:(id)udid;
@end

