/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class AWBeacon;

@interface AWSampleHandler : NSObject {
	BOOL _isStarted;
	BOOL _firstBeaconSent;
	AWBeacon* _beacon;
}
@property(retain, nonatomic) AWBeacon* beacon;
+(id)sharedInstance;
-(BOOL)isFirstBeaconSent;
-(void)beaconSentSuccessfully:(id)successfully;
-(void)beaconSendFailed:(id)failed;
-(void)refresh;
-(void)sendBeacon;
-(void)configureBeacon;
-(void)stop;
-(void)start;
@end

