/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString;
@protocol AWSchemeResolverDelegate;

@interface AWSchemeResolver : NSObject {
	NSString* _host;
	int _currentScheme;
	id<AWSchemeResolverDelegate> _delegate;
}
@property(assign, nonatomic) int currentScheme;
@property(readonly, assign, nonatomic) NSString* host;
@property(assign, nonatomic) id<AWSchemeResolverDelegate> delegate;
+(id)textOfScheme:(int)scheme;
+(id)formattedURL:(id)url scheme:(id)scheme;
-(void)connection:(id)connection didReceiveResponse:(id)response;
-(void)connection:(id)connection didFailWithError:(id)error;
-(void)resolveHost:(id)host;
-(void)dealloc;
@end

