/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWCommand.h"


@interface AWScreenCaptureCommand : AWCommand {
	int _captureCount;
	double _capturePauseInterval;
}
@property(readonly, assign, nonatomic) double capturePauseInterval;
@property(readonly, assign, nonatomic) int captureCount;
-(id)initWithDictionary:(id)dictionary;
@end

