/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWNetworkConnectionDelegate.h"
#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface AWSDKProfileRetriever : NSObject <AWNetworkConnectionDelegate> {
	id _completionBlock;
}
@property(retain, nonatomic) id completionBlock;
-(void)dealloc;
-(void)networkConnection:(id)connection failedWithError:(id)error;
-(void)networkConnection:(id)connection receivedResponseData:(id)data;
-(void)fetchSDKProfile:(id)profile withCompletionBlock:(id)completionBlock;
@end

