/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWProfileRetrieverDelegate.h"
#import <Foundation/NSObject.h>

@class NSString;

@interface AWSDKAppProfileRetriever : NSObject <AWProfileRetrieverDelegate> {
	id profilefetchHandler;
	NSString* appUrlScheme;
}
@property(copy, nonatomic) id profilefetchHandler;
@property(retain, nonatomic) NSString* appUrlScheme;
-(void)SDKSettingsChangeNotification:(id)notification;
-(void)profileRetriever:(id)retriever failedWithError:(id)error;
-(void)profileRetriever:(id)retriever succeededWithResponseData:(id)responseData;
-(void)fetchProfiles;
-(void)setUpMode;
-(void)dealloc;
-(id)init;
@end

