/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AirWatch-Structs.h"
#import "AWInitialView.h"

@class UITextField;

@interface AWServerPathView : AWInitialView {
	UITextField* _serverPathTextField;
}
@property(readonly, assign, nonatomic) UITextField* serverPathTextField;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)setServerPathTextField:(id)field;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

