/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AirWatch-Structs.h"
#import <UIKit/UIView.h>
#import "UIPickerViewDataSource.h"
#import "UIPickerViewDelegate.h"

@class NSArray, UIPickerView, NSString;
@protocol AWSelectionViewDelegate;

__attribute__((visibility("hidden")))
@interface AWSelectionView : UIView <UIPickerViewDataSource, UIPickerViewDelegate> {
	BOOL _interchangeKeyValue;
	NSString* _selectedOptionName;
	NSArray* _ownerList;
	id<AWSelectionViewDelegate> _delegate;
	UIPickerView* _deviceDetailPicker;
	NSString* _defaultOptionName;
}
@property(retain, nonatomic) NSString* defaultOptionName;
@property(assign, nonatomic) BOOL interchangeKeyValue;
@property(retain, nonatomic) UIPickerView* deviceDetailPicker;
@property(assign, nonatomic) id<AWSelectionViewDelegate> delegate;
@property(retain, nonatomic) NSArray* ownerList;
@property(retain, nonatomic) NSString* selectedOptionName;
-(void)dealloc;
-(void)doneButtonPressed;
-(void)pickerView:(id)view didSelectRow:(int)row inComponent:(int)component;
-(id)pickerView:(id)view titleForRow:(int)row forComponent:(int)component;
-(int)pickerView:(id)view numberOfRowsInComponent:(int)component;
-(int)numberOfComponentsInPickerView:(id)pickerView;
-(void)selectDefaultOption:(id)option;
-(void)loadWithOwnershipList:(id)ownershipList;
-(id)initWithFrame:(CGRect)frame;
@end

