/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AirWatch-Structs.h"
#import "AWNetworkConnectionDelegate.h"
#import "AWServer.h"

@protocol AWSettingsEndpointDelegate;

@interface AWSettingsEndpoint : AWServer <AWNetworkConnectionDelegate> {
	id<AWSettingsEndpointDelegate> _delegate;
}
@property(assign, nonatomic) id<AWSettingsEndpointDelegate> delegate;
-(void)networkConnection:(id)connection failedWithError:(id)error;
-(void)networkConnection:(id)connection receivedResponseData:(id)data;
-(void)fetchConfiguration:(int)configuration;
-(void)dealloc;
-(id)initWithDeviceServicesURL:(id)deviceServicesURL;
@end

