/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol AWSessionDelegate <NSObject>
-(void)AWSession:(id)session failedToInvalidateTokenWithError:(id)error;
-(void)AWSessionDidInvalidate:(id)awsession;
-(void)AWSession:(id)session didFailWithError:(id)error;
-(void)AWSession:(id)session didRecieveToken:(id)token;
@end

