/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWRedirectValidatorDelegate.h"
#import "UITextFieldDelegate.h"
#import "AirWatch-Structs.h"
#import <UIKit/UIViewController.h>
#import "AWSchemeResolverDelegate.h"
#import "AWPingerDelegate.h"
#import "AWProfileRetrieverDelegate.h"

@class NSMutableArray, UILabel, AWSDK, UITextField, NSString, AWURLRedirectValidator, AWPinger;
@protocol AWServerSetupControllerDelegate;

@interface AWServerSetupController : UIViewController <AWProfileRetrieverDelegate, UITextFieldDelegate, AWSchemeResolverDelegate, AWRedirectValidatorDelegate, AWPingerDelegate> {
	AWURLRedirectValidator* validator;
	AWPinger* pinger;
	BOOL _isUrlTextPresent;
	bool _redirectComplete;
	id<AWServerSetupControllerDelegate> _delegate;
	UITextField* _urlTextField;
	UITextField* _groupIDTextField;
	NSString* _storedServerUrl;
	NSString* _locationGroup;
	NSString* _redirectURL;
	UILabel* _urlLabel;
	UILabel* _groupIDLabel;
	NSMutableArray* _fetchingProfiles;
	int _userAgent;
	AWSDK* _awsdk;
}
@property(retain, nonatomic) AWSDK* awsdk;
@property(retain, nonatomic) NSMutableArray* fetchingProfiles;
@property(assign, nonatomic) BOOL isUrlTextPresent;
@property(assign, nonatomic) bool redirectComplete;
@property(assign, nonatomic) int userAgent;
@property(retain, nonatomic) NSString* redirectURL;
@property(retain, nonatomic) NSString* locationGroup;
@property(retain, nonatomic) NSString* storedServerUrl;
@property(retain, nonatomic) UILabel* groupIDLabel;
@property(retain, nonatomic) UILabel* urlLabel;
@property(retain, nonatomic) UITextField* groupIDTextField;
@property(retain, nonatomic) UITextField* urlTextField;
@property(retain, nonatomic) id<AWServerSetupControllerDelegate> delegate;
-(void)returnFailedRetrieveSettingError:(id)error;
-(void)returnSuccessfulRetrievedSetting:(id)setting;
-(void)completeProfilesFetching;
-(void)removeCurrentFetchingProfiles:(int)profiles;
-(void)enableUserInteraction;
-(id)formattedHostName;
-(void)resizeViewOnKeyboardNotification:(id)notification visible:(BOOL)visible;
-(BOOL)textFieldShouldReturn:(id)textField;
-(void)validator:(id)validator urlRedirectResult:(int)result;
-(void)proceed;
-(void)pingSuccessful:(id)successful withHost:(id)host withScheme:(int)scheme;
-(void)pingFailed:(id)failed withHost:(id)host withScheme:(int)scheme withError:(id)error;
-(void)resolver:(id)resolver failedToResolve:(id)resolve;
-(void)resolver:(id)resolver resolvedScheme:(id)scheme;
-(void)networkConnection:(id)connection receivedResponseData:(id)data;
-(void)networkConnection:(id)connection failedWithError:(id)error;
-(void)profileRetriever:(id)retriever succeededWithResponseData:(id)responseData;
-(void)profileRetriever:(id)retriever failedWithError:(id)error;
-(id)currentFetchingProfiles;
-(void)fetchProfiles;
-(void)dismissKeyboard:(id)keyboard;
-(void)keyboardWillHideNotification:(id)keyboard;
-(void)keyboardWillShowNotification:(id)keyboard;
-(void)fetchServerReleaseVersionStringWithCompletion:(id)completion;
-(void)selectFirstResponder;
-(void)resignFromActive;
-(void)setFont:(id)font;
-(id)handleDeviceServices;
-(void)resolveURLRedirects;
-(void)validateServerURL;
-(id)locationGroupId;
-(id)dsServerUrl;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewDidUnload;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidLoad;
-(void)dealloc;
-(void)didReceiveMemoryWarning;
-(id)initWithNibName:(id)nibName bundle:(id)bundle userAgent:(int)agent;
@end

