/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "AWProfileRetrieverDelegate.h"

@class AWProfile, AWProfileRetriever, NSMutableArray;
@protocol AWProfileStoreProtocol;

@interface AWSettingsHandler : NSObject <AWProfileRetrieverDelegate> {
	id _callback;
	AWProfileRetriever* _profileRetriever;
	AWProfile* _sdkProfile;
	NSMutableArray* _profiles;
	NSMutableArray* _settingsQueue;
	BOOL _isFetching;
	BOOL _profilesFetched;
	id<AWProfileStoreProtocol> _profileStore;
}
@property(retain, nonatomic) id<AWProfileStoreProtocol> profileStore;
+(id)stringFromType:(int)type;
+(int)typeForSetting:(id)setting;
-(void)loadFromStore;
-(id)sdkProfile;
-(id)profiles;
-(void)reset;
-(void)updateProfile:(id)profile;
-(void)returnWithSuccess:(BOOL)success error:(id)error;
-(void)beaconDidFail:(id)beacon;
-(void)beaconDidSend:(id)beacon;
-(void)profileRetriever:(id)retriever succeededWithResponseData:(id)responseData;
-(void)profileRetriever:(id)retriever failedWithError:(id)error;
-(void)fetchNext;
-(void)fetchSettings:(id)settings withCompletion:(id)completion;
-(void)fetchSettingsWithCompletion:(id)completion;
-(id)init;
-(void)dealloc;
@end

