/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


@interface AWSettingsController : NSObject {
}
+(id)sharedSettings;
-(void)deleteValueForKey:(id)key level:(int)level;
-(id)allSettingsForLevel:(int)level;
-(id)topLevelValueForKey:(id)key;
-(void)setInteger:(int)integer forKey:(id)key level:(int)level;
-(int)integerForKey:(id)key level:(int)level;
-(void)setDouble:(double)aDouble forKey:(id)key level:(int)level;
-(double)doubleForKey:(id)key level:(int)level;
-(void)setBool:(BOOL)aBool forKey:(id)key level:(int)level;
-(BOOL)boolForKey:(id)key level:(int)level;
-(BOOL)setValue:(id)value forKey:(id)key level:(int)level;
-(id)valueForKey:(id)key level:(int)level;
-(id)init;
@end

