/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "NSCoding.h"
#import "AirWatch-Structs.h"

@class NSString, NSURL;

@interface AWServer : NSObject <NSCoding> {
	XXStruct_ASrbpA consoleVer;
	BOOL _canReachDeviceServices;
	NSURL* _deviceServicesURL;
	NSString* _servicePath;
	NSString* _beaconPath;
	NSString* _assetManagementPath;
	NSString* _oldAssetManagementPath;
	NSString* _commandProcessorPath;
	NSString* _commandProcessorNewPath;
	NSString* _contentHandlerPath;
	NSString* _deviceInfoPath;
	NSString* _interrogatorHTTPPath;
	NSString* _dataSamplerHTTPPath;
	unsigned _interrogatorPort;
	unsigned _dataSamplerPort;
	NSString* _keystorePath;
	NSString* _loggingPath;
	NSString* _openEnrollmentPath;
	NSString* _screenCapturePath;
	NSString* _settingsPath;
	NSString* _secureChannelConnectionPath;
	NSString* _contentRepositoryPath;
	NSString* _authenticationPath;
	SCNetworkReachabilityRef _reachabilityRef;
	NSString* _healthPath;
	NSString* _syncProfilesPath;
}
@property(assign, nonatomic) SCNetworkReachabilityRef reachabilityRef;
@property(readonly, assign, nonatomic) BOOL canReachDeviceServices;
@property(copy, nonatomic) NSString* syncProfilesPath;
@property(copy, nonatomic) NSString* healthPath;
@property(copy, nonatomic) NSString* authenticationPath;
@property(copy, nonatomic) NSString* secureChannelConnectionPath;
@property(copy, nonatomic) NSString* settingsPath;
@property(copy, nonatomic) NSString* screenCapturePath;
@property(copy, nonatomic) NSString* openEnrollmentPath;
@property(copy, nonatomic) NSString* loggingPath;
@property(copy, nonatomic) NSString* keystorePath;
@property(assign, nonatomic) unsigned dataSamplerPort;
@property(assign, nonatomic) unsigned interrogatorPort;
@property(copy, nonatomic) NSString* dataSamplerHTTPPath;
@property(copy, nonatomic) NSString* interrogatorHTTPPath;
@property(copy, nonatomic) NSString* deviceInfoPath;
@property(copy, nonatomic) NSString* contentRepositoryPath;
@property(copy, nonatomic) NSString* contentHandlerPath;
@property(copy, nonatomic) NSString* commandProcessorNewPath;
@property(copy, nonatomic) NSString* commandProcessorPath;
@property(copy, nonatomic) NSString* beaconPath;
@property(copy, nonatomic) NSString* oldAssetManagementPath;
@property(copy, nonatomic) NSString* assetManagementPath;
@property(copy, nonatomic) NSString* servicePath;
@property(copy, nonatomic) NSURL* deviceServicesURL;
+(BOOL)consoleIsSixFiveOrHigher;
+(BOOL)consoleIsSixFourOrHigher;
+(BOOL)doesConsoleSupportSSO;
+(BOOL)doesConsoleSupportV2Profile;
+(BOOL)doesConsoleSupportHmacAuthentication;
+(id)sharedInstance;
-(void)stopReachabilityNotifier;
-(BOOL)startReachabilityNotifier;
-(BOOL)isCompatibleWithMajor:(int)major minor:(int)minor;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(void)setDeviceServicesURL:(id)url completion:(id)completion;
-(XXStruct_ASrbpA)consoleVersion;
-(void)dealloc;
-(id)init;
-(void)setConsoleVersion:(id)version;
-(void)setConsoleVersionWithResponse:(id)response;
@end

