/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWNetworkConnection.h"

@class AWSecureChannelWrapper, NSMutableData, NSURL, AWMutableURLRequest, NSString, NSURLConnection;

@interface AWSecureRequestWrapper : AWNetworkConnection {
	NSMutableData* _responsePayload;
	NSString* _type;
	AWMutableURLRequest* _request;
	NSURLConnection* _urlConnectionRequestWrapper;
	NSURL* _url;
	AWSecureChannelWrapper* _secureChannelWrapper;
	NSString* _identifier;
}
@property(copy, nonatomic) NSString* identifier;
@property(assign, nonatomic) NSString* type;
+(void)setChannelIdentityDelegate:(id)delegate;
-(id)connection:(id)connection willCacheResponse:(id)response;
-(void)cancel;
-(id)identifierForURL:(id)url;
-(void)connectionDidFinishLoading:(id)connection;
-(void)connection:(id)connection didReceiveData:(id)data;
-(void)connection:(id)connection didReceiveResponse:(id)response;
-(void)connection:(id)connection didFailWithError:(id)error;
-(void)waitForCheckin;
-(void)checkinDone:(id)done;
-(void)loadRequest;
-(void)loadURL:(id)url;
-(void)dealloc;
-(id)initWithRequest:(id)request;
-(id)init;
@end

