/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "AWSharedCommandProtocol.h"


@interface AWSharedCommandHandler : NSObject <AWSharedCommandProtocol> {
}
+(id)sharedIntance;
-(BOOL)clearPasscodeWithTime:(id)time;
-(BOOL)lockCommandWithTime:(id)time;
@end

