/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol AWSharedCommandProtocol <NSObject>
-(BOOL)clearPasscodeWithTime:(id)time;
-(BOOL)lockCommandWithTime:(id)time;
@end

