/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AirWatch-Structs.h"
#import "AWSimpleCellView.h"

@class UITextField;

@interface AWSimpleTextCellView : AWSimpleCellView {
	UITextField* _textField;
}
@property(readonly, assign, nonatomic) UITextField* textField;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

