/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol AWSOAPControllerDelegate <NSObject>
-(void)soapController:(id)controller didReceieveResponseInfo:(id)info;
-(void)soapController:(id)controller failedWithError:(id)error;
@end

