/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSSOManager.h"

@class AWStoreManager, NSData;

@interface AWSSOManagerAnchor : AWSSOManager {
	AWStoreManager* _containerStoreManager;
}
@property(retain, nonatomic) AWStoreManager* containerStoreManager;
@property(readonly, assign, nonatomic) NSData* masterKey;
+(id)sharedInstance;
-(void)syncCertificateToApplicationUsingPin:(id)applicationUsingPin handler:(id)handler;
-(void)checkAndApplyProfile:(id)profile;
-(void)sendErrorResponseForURL:(id)url;
-(void)sendResponse:(id)response forURL:(id)url;
-(id)requestFromURL:(id)url;
-(id)init;
@end

