/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


@interface AWSSOSessionHelper : NSObject {
}
+(void)invokeBrokerAppForScheme:(id)scheme;
+(void)invokeBrokerAppWithScheme:(id)scheme forCallbackScheme:(id)callbackScheme;
+(id)establishSSOSessionURLWith:(id)with forCallbackScheme:(id)callbackScheme;
+(id)securityHelper;
+(id)brokerAppScheme;
+(void)updateLastSucceededAuthAttemptTimestamp:(id)timestamp;
+(id)lastSucceededAuthAttemptTimestamp;
+(void)setSSOSessionToken:(id)token;
+(id)SSOSessionToken;
@end

