/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSSOManager.h"


@interface AWSSOManagerClient : AWSSOManager {
}
+(id)sharedInstance;
-(void)executeClearPasscodeWithTimeStamp:(id)timeStamp;
-(void)checkPasscodeCompliance;
-(void)executeLockWithTimeStamp:(id)timeStamp;
-(id)requestForType:(int)type;
-(BOOL)isSSOResponseURL:(id)url;
-(void)sendRenewHMACRequest;
-(void)sendRenewSessionRequest;
-(void)sendPinRequest;
-(void)sendAppRegisterRequest;
-(id)init;
@end

