/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSData, AWEnrollmentAccount, NSString, AWHMAC, AWSSOSessionInfo, AWSSOHMACCredential;

@interface AWSSOResponse : NSObject {
	BOOL _ssoEnabled;
	AWSSOHMACCredential* _ssoHMACCredential;
	AWSSOSessionInfo* _sessionInfo;
	AWHMAC* _hmac;
	NSString* _ssoPin;
	NSString* _serverURL;
	AWEnrollmentAccount* _account;
	NSString* _targetScheme;
	NSString* _name;
	NSData* _encryptionKey;
	NSString* _deviceIdentifier;
	int _errorCode;
}
@property(assign, nonatomic) int errorCode;
@property(retain, nonatomic) NSString* deviceIdentifier;
@property(retain, nonatomic) NSData* encryptionKey;
@property(retain, nonatomic) NSString* name;
@property(retain, nonatomic) NSString* targetScheme;
@property(assign, nonatomic) BOOL ssoEnabled;
@property(retain, nonatomic) AWEnrollmentAccount* account;
@property(retain, nonatomic) NSString* serverURL;
@property(retain, nonatomic) NSString* ssoPin;
@property(retain, nonatomic) AWHMAC* hmac;
@property(retain, nonatomic) AWSSOSessionInfo* sessionInfo;
@property(retain, nonatomic) AWSSOHMACCredential* ssoHMACCredential;
-(void)dealloc;
@end

