/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class AWSSOResponse, NSString, AWSSORequest, AWSSOSecurityHelper;

@interface AWSSOCommunication : NSObject {
	NSString* _scheme;
	AWSSOSecurityHelper* _securityHelper;
	AWSSORequest* _request;
	AWSSOResponse* _response;
}
@property(readonly, assign, nonatomic) AWSSOResponse* response;
@property(readonly, assign, nonatomic) AWSSORequest* request;
+(id)splitQuery:(id)query;
+(id)queryFromDictionary:(id)dictionary;
+(id)nameFromURL:(id)url;
-(id)requestFromURL:(id)url;
-(id)urlForRequest:(id)request;
-(id)responseFromURL:(id)url;
-(id)urlFromResponse:(id)response;
-(id)queryFromRequest:(id)request;
-(id)queryFromCredential:(id)credential;
-(id)init;
@end

