/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITabBarController.h>

@class AWNavigationController;

__attribute__((visibility("hidden")))
@interface AWTabController : UITabBarController {
	AWNavigationController* _connectNavigationController;
	AWNavigationController* _supportNavigationController;
	AWNavigationController* _aboutNavigationController;
	AWNavigationController* _messageNavigationController;
}
@property(readonly, assign, nonatomic) AWNavigationController* messageNavigationController;
@property(readonly, assign, nonatomic) AWNavigationController* aboutNavigationController;
@property(readonly, assign, nonatomic) AWNavigationController* supportNavigationController;
@property(readonly, assign, nonatomic) AWNavigationController* connectNavigationController;
-(BOOL)tabBarController:(id)controller shouldSelectViewController:(id)controller2;
-(void)showTabController;
-(void)reloadBranding;
-(void)configureTabBarBranding;
-(void)initTabItems;
-(void)dealloc;
-(void)viewDidLoad;
-(id)init;
@end

