/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AirWatch-Structs.h"
#import <UIKit/UIControl.h>

@class UILabel, UIColor, UIFont, UIButton, UIImage, UIImageView, AWTabBarItem;

@interface AWTabView : UIControl {
	BOOL _selected;
	BOOL _useNewTabs;
	BOOL _useBrandingColors;
	AWTabBarItem* _item;
	UIButton* _closeButton;
	unsigned _tabDirection;
	UIColor* _activeTabColor;
	UIColor* _inactiveTabColor;
	UIColor* _tabLabelColor;
	UIFont* _tabLabelFont;
	UILabel* _titleLabel;
	UIImageView* _bgImageView;
	UIImage* _closeButtonImage;
	UIImage* _tabImage;
	UIImage* _selectedTabImage;
	float _tabOverlap;
	unsigned _tabCloseSide;
}
@property(retain, nonatomic) UIImage* selectedTabImage;
@property(retain, nonatomic) UIImage* tabImage;
@property(retain, nonatomic) UIImage* closeButtonImage;
@property(retain, nonatomic) UIImageView* bgImageView;
@property(retain, nonatomic) UILabel* titleLabel;
@property(assign, nonatomic) unsigned tabCloseSide;
@property(assign, nonatomic) float tabOverlap;
@property(retain, nonatomic) UIFont* tabLabelFont;
@property(retain, nonatomic) UIColor* tabLabelColor;
@property(retain, nonatomic) UIColor* inactiveTabColor;
@property(retain, nonatomic) UIColor* activeTabColor;
@property(assign, nonatomic) BOOL useBrandingColors;
@property(assign, nonatomic) BOOL useNewTabs;
@property(assign, nonatomic) unsigned tabDirection;
@property(assign, nonatomic, getter=isSelected) BOOL selected;
@property(readonly, assign, nonatomic) UIButton* closeButton;
@property(retain, nonatomic) AWTabBarItem* item;
-(void)createTextShadow;
-(void)createTabShadow;
-(id)darkenColorFromColor:(id)color;
-(id)lightenColorFromColor:(id)color;
-(void)setTabTitle:(id)title;
-(void)layoutSubviews;
-(void)reloadTabImages;
-(id)tintedTabImageWithColor:(id)color;
-(void)reloadTabBranding;
-(id)initWithFrame:(CGRect)frame andTabDirection:(unsigned)direction;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
@end

