/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "AirWatch-Structs.h"

@protocol AWTcpIpConnectivityCheckerDelegate;

@interface AWTcpIpConnectivityChecker : NSObject {
	CFReadStreamRef theReadStream;
	CFWriteStreamRef theWriteStream;
	id<AWTcpIpConnectivityCheckerDelegate> _delegate;
}
@property(assign, nonatomic) id<AWTcpIpConnectivityCheckerDelegate> delegate;
-(void)dealloc;
-(void)close;
-(id)errorFromCFStreamError:(XXStruct_K5nmsA)cfstreamError;
-(id)getStreamError;
-(BOOL)connectToHost:(id)host onPort:(unsigned short)port error:(id*)error;
@end

