/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>

@class UIImageView, UILabel, UIProgressView;

__attribute__((visibility("hidden")))
@interface AWTelecomProgressCell : UITableViewCell {
	UIImageView* _iconImageView;
	UILabel* _nameLabel;
	UIProgressView* _progressBarView;
	UILabel* _statusLabel;
}
@property(readonly, assign, nonatomic) UILabel* statusLabel;
@property(readonly, assign, nonatomic) UIProgressView* progressBarView;
@property(readonly, assign, nonatomic) UILabel* nameLabel;
@property(readonly, assign, nonatomic) UIImageView* iconImageView;
-(void)layoutSubviews;
-(void)setHighlighted:(BOOL)highlighted animated:(BOOL)animated;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

