/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


@interface AWTermsOfUse : NSObject {
}
+(void)fetchAcceptedTermsOfUse:(id)use;
+(void)fetchAcceptedTermsOfUseWithContentId:(int)contentId andHandler:(id)handler;
+(void)userActionTermsOfUseForContentId:(int)contentId andEndPoint:(id)point andHandler:(id)handler;
+(void)rejectTermsOfUseForContentId:(int)contentId andHandler:(id)handler;
+(void)acceptTermsOfUseForContentId:(int)contentId andHandler:(id)handler;
+(void)fetchTermsOfUse:(id)use;
+(void)checkTermsOfUse:(id)use;
+(void)parseFetchedTermsOfUseWith:(id)with andError:(id)error andHandler:(id)handler;
+(void)fetchResponseFromEndPoint:(id)endPoint httpMethod:(id)method andJsonObject:(id)object andCompletionHanlder:(id)hanlder;
+(void)fetchResponseFromGETEndPoint:(id)getendPoint andCompletionHanlder:(id)hanlder;
@end

