/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITableViewDelegate.h"
#import "AirWatch-Structs.h"
#import <UIKit/UITableViewController.h>
#import "UITableViewDataSource.h"

@class AWTelecomConfigurationSettingsViewController, AWNavigationController, UIBarButtonItem;

__attribute__((visibility("hidden")))
@interface AWTelecomConfigurationViewController : UITableViewController <UITableViewDataSource, UITableViewDelegate> {
	UIBarButtonItem* configButton;
	AWTelecomConfigurationSettingsViewController* telecomConfigViewController;
	AWNavigationController* navigationController;
}
-(void)refresh:(id)refresh;
-(float)getUsageLeft;
-(float)getUsageInfo;
-(void)configButtonPressed;
-(void)setupProgressBar:(id)bar withProgress:(float)progress;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view titleForHeaderInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)dealloc;
-(void)didReceiveMemoryWarning;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(id)initWithStyle:(int)style;
@end

