/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSOperation.h>

@class UIImageView;
@protocol AWDocumentScrubViewDataSource;

@interface AWThumbnailOperation : NSOperation {
	BOOL _isFinished;
	BOOL _isExecuting;
	id<AWDocumentScrubViewDataSource> _dataSource;
	unsigned _pageNumber;
	UIImageView* _imageView;
}
@property(retain, nonatomic) UIImageView* imageView;
@property(assign, nonatomic) unsigned pageNumber;
@property(assign, nonatomic) id<AWDocumentScrubViewDataSource> dataSource;
-(BOOL)isFinished;
-(BOOL)isExecuting;
-(BOOL)isConcurrent;
-(void)start;
-(void)dealloc;
@end

