/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AirWatch-Structs.h"
#import <UIKit/UIView.h>

@class NSString, AWPDFSearcher, NSArray;

@interface AWTiledPDFPageView : UIView {
	CGPDFPageRef _pageRef;
	float pageScale;
	NSArray* _searchSelections;
	NSString* _keyword;
	AWPDFSearcher* _searcher;
}
@property(readonly, assign, nonatomic) AWPDFSearcher* searcher;
@property(copy, nonatomic) NSString* keyword;
@property(retain, nonatomic) NSArray* searchSelections;
@property(assign, nonatomic) float pageScale;
+(Class)layerClass;
-(CGPDFPageRef)page;
-(void)setPage:(CGPDFPageRef)page;
-(void)drawRect:(CGRect)rect;
-(void)drawLayer:(id)layer inContext:(CGContextRef)context;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

