/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AirWatch-Structs.h"
#import <UIKit/UIToolbar.h>

@class NSString;

@interface AWTitleToolbar : UIToolbar {
	NSString* _title;
}
@property(copy, nonatomic) NSString* title;
-(void)drawRect:(CGRect)rect;
-(void)dealloc;
@end

