/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWToCTableCellDelegate.h"
#import "AirWatch-Structs.h"
#import <UIKit/UIView.h>
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, AWDocumentTOCNode, UITableView;
@protocol AWToCViewDelegate;

@interface AWToCView : UIView <UITableViewDataSource, UITableViewDelegate, AWToCTableCellDelegate> {
	AWDocumentTOCNode* root;
	NSMutableArray* flattenedList;
	UITableView* tocTableView;
	UITableView* _tocTableView;
	id<AWToCViewDelegate> _delegate;
}
@property(assign, nonatomic) UITableView* tocTableView;
@property(assign) id<AWToCViewDelegate> delegate;
@property(retain, nonatomic) AWDocumentTOCNode* root;
-(void)cell:(id)cell didPressExpandWithNode:(id)node;
-(unsigned)indentationLevelFromNode:(id)node;
-(id)flattenNode:(id)node;
-(id)expandNode:(id)node;
-(id)tableView:(id)view titleForHeaderInSection:(int)section;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)numberOfSectionsInTableView:(id)tableView;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)dealloc;
-(void)updateFrame:(CGRect)frame;
-(id)initWithFrame:(CGRect)frame;
@end

