/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol AWToCViewDelegate <NSObject>
-(void)TocView:(id)view didSelectHyperLink:(id)link;
-(void)TocView:(id)view didSelectPageNumber:(id)number;
@end

