/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>

@class AWDocumentTOCNode, UILabel, UIButton;
@protocol AWToCTableCellDelegate;

@interface AWToCTableCell : UITableViewCell {
	UILabel* titleLabel;
	UILabel* pageLabel;
	UILabel* dotLabel;
	UIButton* expandButton;
	BOOL _isExpanded;
	id<AWToCTableCellDelegate> _delegate;
	AWDocumentTOCNode* _node;
}
@property(assign) id<AWToCTableCellDelegate> delegate;
@property(assign) BOOL isExpanded;
@property(retain, nonatomic) AWDocumentTOCNode* node;
-(void)touch;
-(id)lotsOfDots;
-(void)dealloc;
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;
-(void)layoutSubviews;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

