/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class AWEnrollmentAccount, NSData;

@interface AWURLCredentialStorage : NSObject {
	AWEnrollmentAccount* _enrollmentAccount;
	NSData* _encryptionKey;
}
@property(retain, nonatomic) NSData* encryptionKey;
@property(readonly, assign, nonatomic) AWEnrollmentAccount* enrollmentAccount;
+(BOOL)removeAllCredentialStorageAccounts:(id*)accounts;
-(void)updateKeychainWithCredentials:(id)credentials;
-(id)persistedCredentials;
-(id)supplementaryCredentialsMatchingAuthenticationRealm:(id)realm;
-(id)credentialsForProtectionSpace:(id)protectionSpace;
-(void)removeAllCredentials;
-(void)removeCredentialsForProtectionSpace:(id)protectionSpace;
-(void)setCredentials:(id)credentials forProtectionSpace:(id)protectionSpace;
-(id)init;
-(id)initWithEnrollmentAccount:(id)enrollmentAccount encryptionKey:(id)key;
-(id)initWithEnrollmentAccount:(id)enrollmentAccount;
-(void)dealloc;
@end

