/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "NSURLConnectionDataDelegate.h"

@class NSURLRequest, NSMutableData, NSHTTPURLResponse, NSURLConnection;
@protocol AWURLConnectionDelegate;

@interface AWURLConnection : NSObject <NSURLConnectionDataDelegate> {
	id _completionBlock;
	id<AWURLConnectionDelegate> _delegate;
	NSURLRequest* _awCurrentRequest;
	NSURLConnection* _awCurrentConnection;
	NSMutableData* _responseDataBuffer;
	NSHTTPURLResponse* _URLResponse;
}
@property(retain, nonatomic) NSHTTPURLResponse* URLResponse;
@property(retain, nonatomic) NSMutableData* responseDataBuffer;
@property(retain, nonatomic) NSURLConnection* awCurrentConnection;
@property(retain, nonatomic) NSURLRequest* awCurrentRequest;
@property(assign, nonatomic) id<AWURLConnectionDelegate> delegate;
+(id)modifiedRequestWithRequest:(id)request;
+(void)sendAsynchronousRequest:(id)request completionBlock:(id)block;
+(void)sendAsynchronousRequest:(id)request queue:(id)queue completionHandler:(id)handler;
+(id)sendSynchronousRequest:(id)request returningResponse:(id*)response error:(id*)error;
+(id)connectionWithURLRequest:(id)urlrequest delegate:(id)delegate;
-(void)connection:(id)connection didSendBodyData:(int)data totalBytesWritten:(int)written totalBytesExpectedToWrite:(int)write;
-(id)connection:(id)connection needNewBodyStream:(id)stream;
-(id)connection:(id)connection willCacheResponse:(id)response;
-(BOOL)connection:(id)connection canAuthenticateAgainstProtectionSpace:(id)space;
-(void)connection:(id)connection didReceiveAuthenticationChallenge:(id)challenge;
-(void)connection:(id)connection didReceiveResponse:(id)response;
-(void)connectionDidFinishLoading:(id)connection;
-(void)connection:(id)connection didFailWithError:(id)error;
-(void)connection:(id)connection didReceiveData:(id)data;
-(id)connection:(id)connection willSendRequest:(id)request redirectResponse:(id)response;
-(id)aw_currentRequest;
-(void)sendAsynchronousRequest:(id)request completionBlock:(id)block;
-(id)initWithURLRequest:(id)urlrequest delegate:(id)delegate startImmediately:(BOOL)immediately;
-(id)initWithURLRequest:(id)urlrequest delegate:(id)delegate;
-(void)cancel;
-(void)unscheduleConnectionFromRunLoop:(id)runLoop forMode:(id)mode;
-(void)scheduleConnectionInRunLoop:(id)runLoop forMode:(id)mode;
-(void)start;
-(void)initialiseURLConnection;
-(void)dealloc;
@end

