/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol AWURLConnectionDelegate <NSObject>
@optional
-(BOOL)URLConnection:(id)connection canAuthenticateAgainstProtectionSpace:(id)space;
-(void)URLConnection:(id)connection didReceiveAuthenticationChallenge:(id)challenge;
-(void)URLConnection:(id)connection didSendBodyData:(int)data totalBytesWritten:(int)written totalBytesExpectedToWrite:(int)write;
-(id)URLConnection:(id)connection needNewBodyStream:(id)stream;
-(void)URLConnection:(id)connection didFailWithError:(id)error;
-(void)URLConnectionDidFinishLoading:(id)urlconnection;
-(void)URLConnection:(id)connection didReceiveData:(id)data;
-(void)URLConnection:(id)connection didReceiveResponse:(id)response;
-(id)URLConnection:(id)connection willSendRequest:(id)request redirectResponse:(id)response;
@end

