/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>
#import "AirWatch-Structs.h"
#import "UITextFieldDelegate.h"

@class UIButton, UIImageView, UITextField;

__attribute__((visibility("hidden")))
@interface AWUsernamePasswordGroupIDView : UIView <UITextFieldDelegate> {
	BOOL _shouldShowGroupID;
	UITextField* _usernameTextField;
	UITextField* _passwordTextField;
	UITextField* _groupIDTextField;
	id _returnKeyTappedBlock;
	UIImageView* _bgImageView;
	UIButton* _loginButton;
	id _loginButtonTappedBlock;
	id _scrolltextView;
}
@property(copy, nonatomic) id scrolltextView;
@property(copy, nonatomic) id loginButtonTappedBlock;
@property(copy, nonatomic) id returnKeyTappedBlock;
@property(retain, nonatomic) UIButton* loginButton;
@property(retain, nonatomic) UIImageView* bgImageView;
@property(assign, nonatomic) BOOL shouldShowGroupID;
@property(retain, nonatomic) UITextField* groupIDTextField;
@property(retain, nonatomic) UITextField* passwordTextField;
@property(retain, nonatomic) UITextField* usernameTextField;
-(void)setIconImageToTextField:(id)textField withIconImage:(id)iconImage;
-(id)setTextFieldWithPlaceHolder:(id)placeHolder withTextFieldKeyPathObserver:(id)textFieldKeyPathObserver withTag:(int)tag;
-(BOOL)allFieldsFilledOut;
-(BOOL)textFieldShouldReturn:(id)textField;
-(BOOL)textFieldShouldBeginEditing:(id)textField;
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
-(void)goPressed:(id)pressed;
-(void)resignFromActive;
-(void)loginKeyboardTapped;
-(void)layoutSubviews;
-(void)loginButtonTapped:(id)tapped;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

