/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSNumber, NSDate, NSString;

__attribute__((visibility("hidden")))
@interface AWUserAccount : NSObject {
	BOOL _isActive;
	NSString* _userName;
	NSString* _locationGroup;
	NSString* _accountType;
	NSDate* _fetchedDate;
	NSNumber* _userId;
}
@property(copy, nonatomic) NSNumber* userId;
@property(retain, nonatomic) NSDate* fetchedDate;
@property(copy, nonatomic) NSString* accountType;
@property(assign, nonatomic) BOOL isActive;
@property(copy, nonatomic) NSString* locationGroup;
@property(copy, nonatomic) NSString* userName;
-(void)dealloc;
-(id)initWithDictionary:(id)dictionary;
@end

