/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSURLConnection.h>


@interface AWWCFConnection : NSURLConnection {
}
+(void)sendAsynchronousRequest:(id)request completionBlock:(id)block;
@end

