/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString, NSURL;

@interface AWWCFService : NSObject {
	NSURL* _host;
	NSString* _path;
	NSString* _action;
}
@property(copy, nonatomic) NSString* action;
@property(copy, nonatomic) NSString* path;
@property(retain, nonatomic) NSURL* host;
-(id)URL;
-(void)dealloc;
-(id)initWithHost:(id)host path:(id)path action:(id)action;
@end

