/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AirWatch-Structs.h"
#import "CompositeFont.h"


@interface CIDType2Font : CompositeFont {
	BOOL identity;
}
@property(assign, nonatomic, getter=isIdentity) BOOL identity;
-(id)stringWithPDFString:(CGPDFStringRef)pdfstring;
-(id)initWithDictionary:(CGPDFDictionaryRef)dictionary;
-(void)setCIDSystemInfoWithDictionary:(CGPDFDictionaryRef)dictionary;
-(void)setCIDToGIDMapWithDictionary:(CGPDFDictionaryRef)dictionary;
@end

