/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AirWatch-Structs.h"
#import "AWPDFFont.h"


@interface CompositeFont : AWPDFFont {
	float defaultWidth;
}
@property(assign, nonatomic) float defaultWidth;
-(float)widthOfCharacter:(unsigned short)character withFontSize:(float)fontSize;
-(void)setWidthsWithFontDictionary:(CGPDFDictionaryRef)fontDictionary;
@end

