/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewController.h>

@class NSArray, AWHUDView, AWCompliancePolicyRetriver;

__attribute__((visibility("hidden")))
@interface ComplianceViewController : UITableViewController {
	BOOL _isRetrieving;
	NSArray* _allCompliancePolicies;
	AWCompliancePolicyRetriver* compliancePolicyRetriver;
	AWHUDView* _retrievingView;
}
@property(retain, nonatomic) AWHUDView* retrievingView;
-(void)viewDidDisappear:(BOOL)view;
-(void)dealloc;
-(void)reload:(id)reload;
-(void)allPolicyRulesReceived:(id)received;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view titleForHeaderInSection:(int)section;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidUnload;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(id)initWithStyle:(int)style;
@end

