/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITextFieldDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import <UIKit/UITableViewController.h>
#import "AWBottomViewDelegate.h"
#import "AirWatch-Structs.h"

@class UIColor, UITextField, NSString, AWBottomView, UIGestureRecognizer;

__attribute__((visibility("hidden")))
@interface ConfirmUserInformationViewController : UITableViewController <UITextFieldDelegate, UIGestureRecognizerDelegate, AWBottomViewDelegate> {
	UITextField* emailUsername;
	UITextField* emailAddress;
	AWBottomView* buttonView;
	UIGestureRecognizer* tapRecognizer;
	UIColor* backGroundColor;
	NSString* _username;
	NSString* _emailAddressString;
	NSString* _emailUsernameString;
}
@property(retain, nonatomic) NSString* emailUsernameString;
@property(retain, nonatomic) NSString* emailAddressString;
@property(retain, nonatomic) NSString* username;
-(void)changeFrameBasedOnOrientation;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(unsigned)supportedInterfaceOrientations;
-(void)sendRequest;
-(void)backPressed:(id)pressed;
-(void)tappedOutside:(id)outside;
-(BOOL)textFieldShouldReturn:(id)textField;
-(void)keyboardWillHide:(id)keyboard;
-(void)keyboardWillShow:(id)keyboard;
-(void)bottomView:(id)view didSelectBotton:(int)botton;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(BOOL)textFieldShouldBeginEditing:(id)textField;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)didReceiveMemoryWarning;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)dealloc;
-(id)initWithStyle:(int)style;
@end

