/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWBottomViewDelegate.h"
#import "AWPingerDelegate.h"
#import <UIKit/UITableViewController.h>

@class UIColor, AWBottomView, AWPinger, AWHUDView;

__attribute__((visibility("hidden")))
@interface ConnectivityWarningViewController : UITableViewController <AWBottomViewDelegate, AWPingerDelegate> {
	AWBottomView* buttonView;
	UIColor* backGroundColor;
	AWHUDView* _loadingView;
	AWPinger* _internetPinger;
}
-(void)changeFrameBasedOnOrientation;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(unsigned)supportedInterfaceOrientations;
-(void)statusUnchanged:(id)unchanged;
-(void)connectivityChanged:(id)changed;
-(void)pingFailed:(id)failed withHost:(id)host withScheme:(int)scheme withError:(id)error;
-(void)pingSuccessful:(id)successful withHost:(id)host withScheme:(int)scheme;
-(void)bottomView:(id)view didSelectBotton:(int)botton;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)didReceiveMemoryWarning;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)dealloc;
-(id)initWithStyle:(int)style;
@end

