/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "AirWatch-Structs.h"
#import "MKAnnotation.h"

@class NSString, NSDate;

__attribute__((visibility("hidden")))
@interface CustomAnnotation : NSObject <MKAnnotation> {
	XXStruct_zYrK5D coordinate;
	NSString* title;
	NSString* subtitle;
	NSDate* timeStamp;
}
@property(readonly, assign, nonatomic) XXStruct_zYrK5D coordinate;
@property(copy, nonatomic) NSDate* timeStamp;
@property(readonly, assign, nonatomic) NSString* subtitle;
@property(readonly, assign, nonatomic) NSString* title;
-(void)setCoordinate:(XXStruct_zYrK5D)coordinate;
-(void)dealloc;
@end

