/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol DataUpdaterViewControllerDelegate <NSObject>
-(void)dataUpdater:(id)updater didCompleteWithInfo:(id)info;
-(void)dataUpdater:(id)updater failedWithError:(id)error;
@end

