/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIViewController.h>
#import "AWDeviceInfoNetworkControllerDelegate.h"

@class NSString, AWHUDView, AWDeviceInfoNetworkController;
@protocol DataUpdaterViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface DataUpdaterViewController : UIViewController <AWDeviceInfoNetworkControllerDelegate> {
	AWDeviceInfoNetworkController* _networkController;
	AWHUDView* _hudView;
	id<DataUpdaterViewControllerDelegate> _delegate;
	BOOL _isConfigured;
	NSString* _titleName;
}
@property(retain, nonatomic) NSString* titleName;
@property(assign, nonatomic) id<DataUpdaterViewControllerDelegate> delegate;
-(void)fetchSupportInfo;
-(void)fetchDeviceStatus;
-(void)saveSupportPhone:(id)phone email:(id)email;
-(void)saveDeviceInfoEnrolled:(BOOL)enrolled checkedIn:(BOOL)anIn;
-(void)networkController:(id)controller didReceiveData:(id)data;
-(void)networkController:(id)controller didFailWithError:(id)error;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewDidUnload;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
@end

