/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>

@class UITextField;

__attribute__((visibility("hidden")))
@interface DCTextFieldDynamicSizeCell : UITableViewCell {
	UITextField* _textField;
}
@property(readonly, assign, nonatomic) UITextField* textField;
-(void)dealloc;
-(void)setHighlighted:(BOOL)highlighted animated:(BOOL)animated;
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;
-(void)layoutSubviews;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

