/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIActionSheetDelegate.h"
#import "AirWatch-Structs.h"
#import "MFMailComposeViewControllerDelegate.h"
#import "UITableViewDataSource.h"
#import "UIScrollViewDelegate.h"
#import <UIKit/UIViewController.h>
#import "UITableViewDelegate.h"

@class NSDateFormatter, NSMutableArray, UITableView, UIToolbar, UISegmentedControl;

__attribute__((visibility("hidden")))
@interface DeviceLogListViewController : UIViewController <UIActionSheetDelegate, MFMailComposeViewControllerDelegate, UITableViewDelegate, UITableViewDataSource, UIScrollViewDelegate> {
	NSMutableArray* _deviceLogs;
	NSMutableArray* _agentLogs;
	NSDateFormatter* _dateFormatter;
	BOOL _isConfigured;
	int _selectedLogSegmentType;
	int _selectedClearType;
	UISegmentedControl* _logSegmentControl;
	UITableView* _logTableView;
	UIToolbar* _toolBar;
	unsigned _current20logSectionOfAgent;
	unsigned _current20logSectionOfDevice;
	unsigned _totalCountOfAgentLog;
	unsigned _totalCountOfDeviceLog;
}
-(void)setupBranding;
-(void)loadLogData;
-(void)mailComposeController:(id)controller didFinishWithResult:(int)result error:(id)error;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)logPostOption;
-(void)sendMailWithData:(id)data withFileName:(id)fileName;
-(void)postXmlWithData:(id)data withFileName:(id)fileName;
-(void)segmentControlValueChange:(id)change;
-(void)refreshLog:(id)log;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)addSegmentControlToolBar;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidUnload;
-(void)viewDidLoad;
-(void)dealloc;
-(void)didReceiveMemoryWarning;
-(id)init;
@end

