/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITextFieldDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "AWBottomViewDelegate.h"
#import "AWSelectionViewDelegate.h"
#import "AirWatch-Structs.h"
#import "UIPopoverControllerDelegate.h"
#import <UIKit/UITableViewController.h>
#import "SelectionPopoverDelegate.h"

@class UITapGestureRecognizer, UIColor, UIPopoverController, NSMutableDictionary, AWBottomView, NSString, AWSelectionView, UITextField;

__attribute__((visibility("hidden")))
@interface DeviceDetailsViewController : UITableViewController <UITextFieldDelegate, AWBottomViewDelegate, UIGestureRecognizerDelegate, AWSelectionViewDelegate, UIPopoverControllerDelegate, SelectionPopoverDelegate> {
	NSString* _deviceDetailString;
	NSString* _deviceAssetTag;
	BOOL _showDeviceOwnershipRequiredMessage;
	BOOL _showingSelectionView;
	UITapGestureRecognizer* tapRecognizer;
	UIColor* backGroundColor;
	UIPopoverController* deviceDetailsPopOver;
	BOOL _showAssetTag;
	BOOL _showDeviceDetails;
	AWBottomView* _bottomView;
	UITextField* _assetNumber;
	NSMutableDictionary* _ownerList;
	AWSelectionView* _selector;
	id _defaultOwnership;
}
@property(retain, nonatomic) id defaultOwnership;
@property(assign, nonatomic) BOOL showDeviceDetails;
@property(retain, nonatomic) AWSelectionView* selector;
@property(retain, nonatomic) NSMutableDictionary* ownerList;
@property(retain, nonatomic) UITextField* assetNumber;
@property(assign, nonatomic) BOOL showAssetTag;
@property(retain, nonatomic) AWBottomView* bottomView;
-(void)dealloc;
-(void)changeFrameBasedOnOrientation;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(unsigned)supportedInterfaceOrientations;
-(void)cancelPressed;
-(void)selectionViewDidSelectButton:(id)selectionView;
-(void)sendRequest;
-(void)backPressed;
-(void)bottomView:(id)view didSelectBotton:(int)botton;
-(void)willHideKeyboard:(id)keyboard;
-(void)willShowKeyboard:(id)keyboard;
-(void)tappedOutside:(id)outside;
-(void)textFieldDidBeginEditing:(id)textField;
-(BOOL)textFieldShouldReturn:(id)textField;
-(void)buttonPressed:(id)pressed;
-(void)didSelectOptionWith:(id)with andtag:(int)andtag;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForFooterInSection:(int)section;
-(id)tableView:(id)view viewForFooterInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)numberOfSectionsInTableView:(id)tableView;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(void)didReceiveMemoryWarning;
-(void)orientationChanged:(id)changed;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

