/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWSessionDelegate.h"
#import <UIKit/UITableViewController.h>
#import "AWBottomViewDelegate.h"

@class AWHUDView, UILabel, UIColor, UIImageView, NSInvocationOperation, AWBottomView;
@protocol EnrollmentCompleteDelegate;

__attribute__((visibility("hidden")))
@interface EnrollmentCompleteViewController : UITableViewController <AWBottomViewDelegate, AWSessionDelegate> {
	AWHUDView* loadingView;
	UIColor* backgroundColor;
	UIImageView* successImage;
	UILabel* successLabel;
	NSInvocationOperation* _appDismissVCOperation;
	int _yCorrection;
	BOOL _enrollmentInProgress;
	BOOL _enrollmentSuccessfull;
	AWBottomView* _bottomView;
	id<EnrollmentCompleteDelegate> _delegate;
}
@property(assign, nonatomic) id<EnrollmentCompleteDelegate> delegate;
@property(assign, nonatomic) BOOL enrollmentSuccessfull;
@property(assign, nonatomic) BOOL enrollmentInProgress;
@property(retain, nonatomic) AWBottomView* bottomView;
-(void)setAfterSessionResponse;
-(void)checkTocreateOperationAndExecute;
-(void)dispatchOperation;
-(void)changeFrameBasedOnOrientation;
-(unsigned)supportedInterfaceOrientations;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)AWSession:(id)session failedToInvalidateTokenWithError:(id)error;
-(void)AWSessionDidInvalidate:(id)awsession;
-(void)AWSession:(id)session didFailWithError:(id)error;
-(void)AWSession:(id)session didRecieveToken:(id)token;
-(void)getPostEnrollmentHmacToken;
-(void)bottomView:(id)view didSelectBotton:(int)botton;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)didReceiveMemoryWarning;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)dealloc;
-(id)initWithStyle:(int)style;
@end

