/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AirWatch-Structs.h"
#import <Foundation/NSObject.h>

@class NSString;

@interface KeyWrapper : NSObject {
	NSString* _name;
	SecKey* _publicKey;
	SecKey* _privateKey;
}
+(id)certificateInformationFromCertificate:(id)certificate password:(id)password error:(id*)error;
-(id)decrypt:(id)decrypt error:(id*)error;
-(id)encrypt:(id)encrypt withKey:(id)key error:(id*)error;
-(id)publicKeyData:(id*)data;
-(SecKey*)publicKeyRef;
-(SecKey*)privateKeyRef;
-(BOOL)generateKeyPair:(unsigned)pair error:(id*)error;
-(id)tempKeyAttributes;
-(id)publicKeyAttributes;
-(id)privatKeyAttributes;
-(id)publicIdentifier;
-(id)tempIdentifier;
-(id)privateIdentifier;
-(void)clear;
-(id)initWithName:(id)name error:(id*)error;
@end

