/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AirWatch-Structs.h"
#import <UIKit/UILabel.h>

@class UIColor;

__attribute__((visibility("hidden")))
@interface LabelGradientView : UILabel {
	CGGradientRef _gradient;
	UIColor* _topColor;
	UIColor* _bottomColor;
}
@property(retain, nonatomic) UIColor* bottomColor;
@property(retain, nonatomic) UIColor* topColor;
-(void)drawRect:(CGRect)rect;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

