/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AirWatch-Structs.h"
#import <Foundation/NSObject.h>

@class UIView;

@interface LayerDelegate : NSObject {
	UIView* _view;
}
-(void)drawLayer:(id)layer inContext:(CGContextRef)context;
-(id)initWithView:(id)view;
@end

