/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>
#import "AirWatch-Structs.h"
#import "UITextFieldDelegate.h"

@class UIImageView, UITextField;

@interface LoginTextField : UIView <UITextFieldDelegate> {
	UITextField* _textField;
	UIImageView* _imageView;
}
@property(retain, nonatomic) UIImageView* imageView;
@property(retain, nonatomic) UITextField* textField;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame andImage:(id)image;
@end

