/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewController.h>

@class NSArray, NSMutableArray;

__attribute__((visibility("hidden")))
@interface NetworkDeviceInfoViewController : UITableViewController {
	NSArray* _networkAdapters;
	NSMutableArray* _otherAdapters;
	BOOL _isConfigured;
}
-(id)getCarrierName;
-(id)getSSIDInfo;
-(void)applicationWillEnterForegroundNotification:(id)application;
-(void)reachabilityChanged:(id)changed;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(id)tableView:(id)view titleForHeaderInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(id)otherAdapters;
-(id)networkAdapters;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidUnload;
-(void)viewDidLoad;
-(void)didReceiveMemoryWarning;
-(void)dealloc;
-(id)initWithStyle:(int)style;
@end

