/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSDate.h>


@interface NSDate (AirWatch)
+(id)gmtDateFormatter;
+(id)AW_gmtDate;
+(id)AW_shortDateTimeStyleFormat;
+(id)AW_shortDateStyleFormat;
+(id)AW_defaultDateFormat;
@end

