/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSData.h>


@interface NSData (reallyMapped)
+(id)dataWithContentsOfReallyMappedFile:(id)reallyMappedFile;
@end

@interface NSData (Base64)
+(id)AW_base64DecodedData:(id)data;
-(id)AW_base64EncodedString;
@end

@interface NSData (Compression)
-(id)AW_gzipCompress;
@end

@interface NSData (Crypto)
+(id)AW_AESDecryptedData:(id)data key:(id)key initializationVector:(id)vector error:(id*)error;
+(id)AW_AESEncryptedData:(id)data key:(id)key initializationVector:(id)vector error:(id*)error;
+(id)AW_AESDecryptedData:(id)data key:(id)key error:(id*)error;
+(id)AW_AESEncryptedData:(id)data key:(id)key error:(id*)error;
+(id)AW_cipher:(id)cipher operation:(unsigned)operation key:(id)key initializationVector:(id)vector options:(unsigned)options error:(id*)error;
+(id)AW_cipher:(id)cipher operation:(unsigned)operation key:(id)key initializationVector:(id)vector error:(id*)error;
+(id)AW_cipher:(id)cipher operation:(unsigned)operation key:(id)key error:(id*)error;
+(id)AW_randomBytes:(unsigned long)bytes;
-(id)AW_MD5;
-(id)AW_SHA1;
-(id)AW_SHA512;
-(id)AW_SHA256;
@end

@interface NSData (Conversion)
-(id)AW_hexadecimalString;
@end

@interface NSData (AES256)
-(id)AES256DecryptWithKey:(id)key;
-(id)AES256EncryptWithKey:(id)key;
@end

