/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSInputStream.h>


@interface NSInputStream (AWData)
-(BOOL)_AWGetData:(id*)data maxLength:(unsigned)length error:(id*)error;
@end

