/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSString.h>
#import "AirWatch-Structs.h"


@interface NSString (StartAndEnd)
-(BOOL)endsWithString:(id)string options:(unsigned)options range:(NSRange)range locale:(id)locale;
-(BOOL)endsWithString:(id)string options:(unsigned)options range:(NSRange)range;
-(BOOL)endsWithString:(id)string options:(unsigned)options;
-(BOOL)endsWithString:(id)string;
-(BOOL)startsWithString:(id)string options:(unsigned)options range:(NSRange)range locale:(id)locale;
-(BOOL)startsWithString:(id)string options:(unsigned)options range:(NSRange)range;
-(BOOL)startsWithString:(id)string options:(unsigned)options;
-(BOOL)startsWithString:(id)string;
@end

@interface NSString (StartAndEnd)
-(BOOL)endsWithString:(id)string options:(unsigned)options range:(NSRange)range locale:(id)locale;
-(BOOL)endsWithString:(id)string options:(unsigned)options range:(NSRange)range;
-(BOOL)endsWithString:(id)string options:(unsigned)options;
-(BOOL)endsWithString:(id)string;
-(BOOL)startsWithString:(id)string options:(unsigned)options range:(NSRange)range locale:(id)locale;
-(BOOL)startsWithString:(id)string options:(unsigned)options range:(NSRange)range;
-(BOOL)startsWithString:(id)string options:(unsigned)options;
-(BOOL)startsWithString:(id)string;
@end

@interface NSString (HMAC)
-(id)AW_hmacSHA256WithKey:(id)key;
-(id)AW_hmacSHA1WithKey:(id)key;
@end

@interface NSString (MD5)
-(id)AW_MD5;
@end

@interface NSString (Extension)
+(BOOL)isRightToleftCharacter:(unsigned)character;
-(BOOL)containRightToLeftCharacter;
-(id)reversedString;
-(id)stringByAppendingDuplicateIndexCount:(int)count;
-(id)stringByTrimmingTrailingWhitespaceAndNewlineCharacters;
-(id)stringByTrimmingTrailingCharactersInSet:(id)set;
-(id)stringByTrimmingLeadingWhitespaceAndNewlineCharacters;
-(id)stringByTrimmingLeadingCharactersInSet:(id)set;
-(id)stringByTrimmingLeadingAndTrailingWhitespaceAndNewlineCharacters;
-(id)stringByTrimmingLeadingAndTrailingCharactersInSet:(id)set;
-(id)stringByUnescapingFromURLQuery;
-(id)stringByEscapingForURLQuery;
-(unsigned)hexIntValue;
-(id)jsonEscapedString;
-(id)xmlEscapedString;
-(BOOL)AW_boolValue;
@end

@interface NSString (Passcode)
-(int)AW_complexCharacterCount;
-(BOOL)AW_containsLetters;
@end

