/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSURLRequest.h>
#import "AirWatch-Structs.h"


@interface NSURLRequest (HTTPMessage)
-(id)getCookieDict;
-(CFDataRef)createHTTPMessageSerial;
-(CFHTTPMessageRef)createHTTPMessage;
@end

