/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol NSURLAuthenticationChallengeSender <NSObject>
-(void)cancelAuthenticationChallenge:(id)challenge;
-(void)continueWithoutCredentialForAuthenticationChallenge:(id)authenticationChallenge;
-(void)useCredential:(id)credential forAuthenticationChallenge:(id)authenticationChallenge;
@optional
-(void)rejectProtectionSpaceAndContinueWithChallenge:(id)challenge;
-(void)performDefaultHandlingForAuthenticationChallenge:(id)authenticationChallenge;
@end

