/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSURL.h>


@interface NSURL (Parsing)
+(id)urlByEscapingQueryParameters:(id)parameters;
+(id)jsonFormattedQueryFromDictionary:(id)dictionary;
+(id)queryFromDictionary:(id)dictionary;
-(id)parameters;
-(id)urlByTrimmingTrailingPathComponent;
-(id)jsonFormattedQuery;
-(id)queryDictionary;
@end

