/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>
#import "AirWatch-Structs.h"

@class UILabel, PasscodeValidationView, UIImageView;

@interface PasscodeValidationPage : UIView {
	UIImageView* workspaceImage;
	PasscodeValidationView* loginView;
	UILabel* _textLabelView;
	id _loginPressed;
	CGRect _keyboardRect;
}
@property(assign, nonatomic) CGRect keyboardRect;
@property(copy, nonatomic) id loginPressed;
-(void)showLogin;
-(void)showMessage:(id)message;
-(void)layoutSubviews;
-(void)loginPressed:(id)pressed;
-(void)dismissKeyboard;
-(void)scrollViewToTextField:(id)textField;
-(void)keyboardShowNotification:(id)notification;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

