/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITextFieldDelegate.h"
#import "AirWatch-Structs.h"
#import <UIKit/UIView.h>

@class UILabel, UIButton, UIToolbar, LoginTextField;

@interface PasscodeValidationView : UIView <UITextFieldDelegate> {
	UIToolbar* dismissBar;
	UIButton* loginButton;
	UILabel* textLabel;
	id loginTarget;
	SEL loginAction;
	LoginTextField* _passcodeField;
	UIView* _loginButtonView;
	id _textFieldBeganEditingBlock;
	id _keyboardDismissed;
}
@property(copy, nonatomic) id keyboardDismissed;
@property(copy, nonatomic) id textFieldBeganEditingBlock;
@property(retain, nonatomic) UIView* loginButtonView;
@property(assign, nonatomic) LoginTextField* passcodeField;
-(void)dismissPressed;
-(id)textFieldBeingEdited;
-(void)textFieldDidBeginEditing:(id)textField;
-(void)textFieldDidEndEditing:(id)textField;
-(BOOL)textFieldShouldReturn:(id)textField;
-(void)loginPressed:(id)pressed;
-(void)addTarget:(id)target action:(SEL)action forControlEvents:(unsigned)controlEvents;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

