/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWTableViewController.h"

@class AWDocumentTOCNode, NSArray, NSMutableArray;

@interface PDFDocumentToCView : AWTableViewController {
	AWDocumentTOCNode* root;
	NSMutableArray* flattenedList;
	NSArray* _bookmarks;
}
@property(retain, nonatomic) AWDocumentTOCNode* root;
@property(retain, nonatomic) NSArray* bookmarks;
-(unsigned)indentationLevelFromNode:(id)node;
-(void)flattenNode:(id)node;
-(void)tableView:(id)view accessoryButtonTappedForRowWithIndexPath:(id)indexPath;
-(id)tableView:(id)view titleForHeaderInSection:(int)section;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)numberOfSectionsInTableView:(id)tableView;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewDidLoad;
-(void)dealloc;
-(id)init;
@end

