/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AirWatch-Structs.h"
#import <UIKit/UITableViewController.h>

@class NSArray;
@protocol SelectionPopoverDelegate;

__attribute__((visibility("hidden")))
@interface SelectionPopoverViewController : UITableViewController {
	NSArray* _selectionList;
	id<SelectionPopoverDelegate> _delegate;
	int _tag;
	CGRect _frameSize;
}
@property(assign, nonatomic) int tag;
@property(assign, nonatomic) id<SelectionPopoverDelegate> delegate;
@property(assign, nonatomic) CGRect frameSize;
@property(retain, nonatomic) NSArray* selectionList;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)setDefaultSelection:(id)selection;
-(void)viewDidLoad;
-(id)initWithStyle:(int)style;
@end

