/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AirWatch-Structs.h"
#import "AWPDFFont.h"


@interface SimpleFont : AWPDFFont {
	unsigned encoding;
}
@property(assign, nonatomic) unsigned encoding;
-(id)stringWithCharacters:(const char*)characters;
-(void)setEncodingWithEncodingObject:(CGPDFObject*)encodingObject;
-(id)stringWithPDFString:(CGPDFStringRef)pdfstring;
-(void)setEncodingWithFontDictionary:(CGPDFDictionaryRef)fontDictionary;
-(void)setWidthsWithFontDictionary:(CGPDFDictionaryRef)fontDictionary;
-(id)initWithDictionary:(CGPDFDictionaryRef)dictionary;
@end

