/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWBottomViewDelegate.h"
#import "AirWatch-Structs.h"
#import "UITextFieldDelegate.h"
#import <UIKit/UITableViewController.h>
#import "UIGestureRecognizerDelegate.h"

@class UIColor, AWBottomView, UIGestureRecognizer, UITextField;

__attribute__((visibility("hidden")))
@interface StagingDeviceOwnerViewController : UITableViewController <UITextFieldDelegate, AWBottomViewDelegate, UIGestureRecognizerDelegate> {
	UITextField* usernameField;
	AWBottomView* buttonView;
	UIGestureRecognizer* tapRecognizer;
	BOOL _showUsernameRequired;
	UIColor* backGroundColor;
}
-(void)changeFrameBasedOnOrientation;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(unsigned)supportedInterfaceOrientations;
-(void)backPressed:(id)pressed;
-(void)sendRequest;
-(void)tappedOutside:(id)outside;
-(void)keyboardWillHide:(id)keyboard;
-(void)keyboardWillShow:(id)keyboard;
-(void)textFieldDidBeginEditing:(id)textField;
-(BOOL)textFieldShouldReturn:(id)textField;
-(void)bottomView:(id)view didSelectBotton:(int)botton;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForFooterInSection:(int)section;
-(id)tableView:(id)view viewForFooterInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)didReceiveMemoryWarning;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)dealloc;
-(id)initWithStyle:(int)style;
@end

