/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewController.h>
#import "UIAlertViewDelegate.h"

@class AWHUDView, NSTimer, AWAgentAuthTokenHandler;

__attribute__((visibility("hidden")))
@interface StatusViewController : UITableViewController <UIAlertViewDelegate> {
	BOOL _isEnrolled;
	BOOL _hasToken;
	BOOL _showSync;
	BOOL _showAccount;
	BOOL _showCompliance;
	BOOL _accountStatusActive;
	NSTimer* tokenFetchTimer;
	AWHUDView* _loadingView;
	AWAgentAuthTokenHandler* _authTokenHandler;
}
@property(retain, nonatomic) AWAgentAuthTokenHandler* authTokenHandler;
@property(retain, nonatomic) AWHUDView* loadingView;
-(void)fetchTokenFromAPNS;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)showPushNotificationAlert;
-(void)viewComplianceAlert;
-(void)updateMDMStatus:(id)status;
-(void)PresentPasscodeView;
-(void)hmacReceivedAction;
-(void)sendData;
-(void)updateFlags;
-(void)refresh:(id)refresh;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view titleForHeaderInSection:(int)section;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidUnload;
-(void)viewDidLoad;
-(void)dealloc;
-(id)initWithStyle:(int)style;
@end

