/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MFMailComposeViewControllerDelegate.h"
#import <UIKit/UITableViewController.h>


__attribute__((visibility("hidden")))
@interface SupportViewController : UITableViewController <MFMailComposeViewControllerDelegate> {
	BOOL _showCancelButton;
}
@property(assign, nonatomic) BOOL showCancelButton;
-(void)dismiss:(id)dismiss;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)mailComposeController:(id)controller didFinishWithResult:(int)result error:(id)error;
-(void)showCallConfirmationAlert;
-(id)configureCell:(id)cell atIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
@end

