/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString;

@interface TouchDownPolicy : NSObject {
	NSString* PolicyName;
	NSString* PolicyValue;
	BOOL OnlyOnce;
}
@property(assign) BOOL OnlyOnce;
@property(retain) NSString* PolicyValue;
@property(retain) NSString* PolicyName;
-(void).cxx_destruct;
-(id)initSetting:(id)setting withValue:(id)value onceOnly:(BOOL)only;
-(id)initPolicy:(id)policy withValue:(id)value;
@end

