/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString, NSMutableArray;

@interface TouchDownMDM : NSObject {
	NSString* UserID;
	NSString* Email;
	NSString* Domain;
	NSString* Password;
	NSString* Server;
	BOOL UseSSL;
	BOOL AllowUntrustedServer;
	NSString* CertBase64;
	NSMutableArray* Policies;
	NSString* CorrelationID;
	NSString* DeviceID;
	NSString* DeviceType;
	NSMutableArray* UserPreferences;
	NSString* CertKey;
	NSString* MDMID;
	NSString* MDMName;
	NSString* DeveloperKey;
}
@property(retain) NSMutableArray* UserPreferences;
@property(retain) NSMutableArray* Policies;
@property(retain) NSString* DeveloperKey;
@property(retain) NSString* MDMName;
@property(retain) NSString* MDMID;
@property(retain) NSString* CorrelationID;
@property(retain) NSString* CertBase64;
@property(retain) NSString* CertKey;
@property(assign) BOOL AllowUntrustedServer;
@property(assign) BOOL UseSSL;
@property(retain) NSString* DeviceType;
@property(retain) NSString* DeviceID;
@property(retain) NSString* Server;
@property(retain) NSString* Password;
@property(retain) NSString* Domain;
@property(retain) NSString* Email;
@property(retain) NSString* UserID;
+(id)convertToBase64:(id)base64;
+(id)encryptString:(id)string;
+(BOOL)depositData:(id)data startNow:(BOOL)now;
+(BOOL)clearAllData;
-(void).cxx_destruct;
-(void)StartConfiguration:(BOOL)configuration forceReconfig:(BOOL)reconfig;
-(void)doSetPolicies:(BOOL)policies;
-(void)doWipe:(BOOL)wipe;
-(void)addUserSetting:(id)setting;
-(void)addPolicy:(id)policy;
-(id)init;
@end

