/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CompositeFont.h"
#import "AirWatch-Structs.h"

@class NSMutableArray;

@interface Type0Font : CompositeFont {
	NSMutableArray* descendantFonts;
}
@property(readonly, assign, nonatomic) NSMutableArray* descendantFonts;
-(id)description;
-(void)dealloc;
-(id)childrenFonts;
-(id)cidWithPDFString:(CGPDFStringRef)pdfstring;
-(id)stringWithPDFString:(CGPDFStringRef)pdfstring;
-(float)maxY;
-(float)minY;
-(id)fontDescriptor;
-(id)ligatures;
-(float)widthOfCharacter:(unsigned short)character withFontSize:(float)fontSize;
-(id)initWithFontDictionary:(CGPDFDictionaryRef)fontDictionary;
@end

