/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIAlertView.h>
#import "UIAlertViewDelegate.h"


@interface UIAlertView (additions) <UIAlertViewDelegate>
+(id)newAlertViewWithTitle:(id)title message:(id)message cancelButtonTitle:(id)title3 otherButtonTittles:(id)tittles onDismiss:(id)dismiss onCancel:(id)cancel;
+(void)alertView:(id)view didDismissWithButtonIndex:(int)buttonIndex;
+(id)showAlertViewWithTitle:(id)title message:(id)message cancelButtonTitle:(id)title3 otherButtonTitles:(id)titles style:(int)style onDismiss:(id)dismiss onCancel:(id)cancel;
+(id)showAlertViewWithTitle:(id)title message:(id)message cancelButtonTitle:(id)title3 otherButtonTitles:(id)titles onDismiss:(id)dismiss onCancel:(id)cancel;
+(id)getUIAlertViewIfShown;
@end

