/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIButton.h>


@interface UIBlockButton : UIButton {
	id _actionBlock;
}
-(void)dealloc;
-(void)callActionBlock:(id)block;
-(void)handleControlEvent:(unsigned)event withBlock:(id)block;
@end

