/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIColor.h>


@interface UIColor (AW_Branding)
+(id)AW_alternatingCellColor;
+(id)AW_tableSelectionGradientEndColor;
+(id)AW_tableSelectionGradientStartColor;
+(id)AW_iPadViewBackgroundColor;
+(id)AW_descriptionTextCellColor;
+(id)AW_navigationBarColor;
+(id)AW_buttonTitleColor;
@end

@interface UIColor (Format)
+(id)AW_colorFromNumber:(id)number;
-(id)AW_colorComponents;
@end

