/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIDevice.h>
#import "AirWatch-Structs.h"


@interface UIDevice (Processes)
-(id)AW_runningProcesses;
@end

@interface UIDevice (AirWatch)
-(CGAffineTransform)rotationAffineTransformForCurrentOrientation;
-(BOOL)isPortraitOrientation;
-(BOOL)isWideScreen;
-(BOOL)isIPad;
-(int)AW_deviceTypeIdentifier;
@end

@interface UIDevice (Capablities)
-(BOOL)AW_canSendEmail;
-(BOOL)AW_canPlaceCall;
@end

@interface UIDevice (Console)
+(id)getLevelFromInt:(int)int;
+(int)getIntEquivalentOfLogLevel:(id)logLevel;
-(id)getIOSDeviceLogsFilterWithRunningApp:(id)runningApp;
-(id)getIosDeviceLogs;
-(id)AW_ConsoleLogsWithApplication:(id)application;
-(id)getConsoleLogsWithApplication:(id)application NumberOfEntries:(int)entries;
-(id)getConsoleLogWithApplication:(id)application NumberOfEntries:(int)entries;
@end

@interface UIDevice (Memory)
-(int)AW_availableMemory;
-(int)AW_inactiveMemory;
-(int)AW_activeMemory;
-(int)AW_wiredMemory;
-(int)AW_totalMemory;
-(int)AW_availableVirtualMemory;
-(int)AW_totalVirtualMemory;
-(int)AW_availablePageFile;
-(int)AW_totalPageFile;
-(int)AW_availablePhysicalMemory;
-(unsigned long long)AW_totalPhysicalMemory;
@end

@interface UIDevice (Networking)
-(id)AW_networkAdapters;
@end

@interface UIDevice (Power)
-(id)batteryStateString;
-(BOOL)batteryChemistry;
-(unsigned)backupBatteryVoltage;
-(float)batteryTemperature;
-(int)batteryDischarge;
-(int)batteryAverageCurrent;
-(int)batteryCurrent;
-(unsigned)batteryVoltage;
-(unsigned)backupBatteryLifeTime;
-(BOOL)backupBatteryLifePercent;
-(unsigned short)backupBatteryStatus;
-(unsigned)batteryLifeTime;
-(BOOL)batteryLifePercent;
-(unsigned short)batteryStatus;
-(BOOL)powerLineType;
@end

@interface UIDevice (System)
-(int)AW_deviceType;
-(BOOL)AW_isCompromised;
-(id)AW_nextGenUniqueIdentifier:(id)identifier;
-(id)AW_formattedUniqueIdentifier;
-(id)AW_platform;
-(id)AW_osBuildString;
-(unsigned short)AW_osVersionBuild;
-(unsigned short)AW_osVersionMinor;
-(unsigned short)AW_osVersionMajor;
@end

@interface UIDevice (Hardware)
-(id)platformCode;
-(id)macaddress;
-(id)platformString;
-(unsigned)platformType;
-(id)freeDiskSpace;
-(id)totalDiskSpace;
-(unsigned)maxSocketBufferSize;
-(unsigned)userMemory;
-(unsigned)totalMemory;
-(unsigned)busFrequency;
-(unsigned)cpuFrequency;
-(unsigned)getSysInfo:(unsigned)info;
-(id)hwmodel;
-(id)platform;
-(id)getSysInfoByName:(char*)name;
@end

