/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIImage.h>
#import "AirWatch-Structs.h"


@interface UIImage (AWScale)
+(id)AW_scaledImage:(id)image scaledToSize:(CGSize)size;
@end

@interface UIImage (Loading)
+(id)AW_imageNamed:(id)named bundle:(id)bundle;
@end

@interface UIImage (Rotation)
-(id)rotatedImageLeft;
-(id)rotatedImageRight;
@end

@interface UIImage (AW_Scale)
+(id)AW_image:(id)image scaledToSize:(CGSize)size;
-(id)newImageByScalingAndCroppingForSize:(CGSize)size;
-(id)scaleToSize:(CGSize)size;
-(id)imageByScalingAndCroppingForSize:(CGSize)size;
@end

@interface UIImage (Tint)
+(id)AW_tintImage:(id)image withColor:(id)color;
@end

