/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIViewController.h>


@interface UIViewController (UINavigationItem)
-(id)navBarTintColor;
-(id)customTitleView;
@end

@interface UIViewController (Styling)
-(void)AW_recurisivelySetFont:(id)font forView:(id)view;
-(void)AW_setFont:(id)font;
@end

