/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AWBottomViewDelegate.h"
#import <UIKit/UITableViewController.h>

@class UIColor, AWBottomView, NSString;

__attribute__((visibility("hidden")))
@interface WelcomeMessageViewController : UITableViewController <AWBottomViewDelegate> {
	AWBottomView* buttonView;
	UIColor* backGroundColor;
	NSString* _headerMessage;
	NSString* _messageBody;
}
@property(retain, nonatomic) NSString* messageBody;
@property(retain, nonatomic) NSString* headerMessage;
-(void)changeFrameBasedOnOrientation;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(unsigned)supportedInterfaceOrientations;
-(void)backPressed:(id)pressed;
-(void)bottomView:(id)view didSelectBotton:(int)botton;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)didReceiveMemoryWarning;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(id)initWithStyle:(int)style;
@end

