/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AirWatch-Structs.h"
#import "ZBarImage.h"

@class NSInvocationOperation;

@interface ZBarCVImage : ZBarImage {
	CVBufferRef pixelBuffer;
	void* rgbBuffer;
	NSInvocationOperation* conversion;
}
@property(assign, nonatomic) CVBufferRef pixelBuffer;
@property(readonly, assign, nonatomic) void* rgbBuffer;
-(void)dealloc;
-(void)waitUntilConverted;
-(id)UIImageWithOrientation:(int)orientation;
-(void)convertCVtoRGB;
@end

