/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AirWatch-Structs.h"
#import "NSFastEnumeration.h"
#import <Foundation/NSObject.h>


@interface ZBarSymbolSet : NSObject <NSFastEnumeration> {
	zbar_symbol_set_s* set;
	BOOL filterSymbols;
}
@property(readonly, assign, nonatomic) int count;
@property(readonly, assign, nonatomic) zbar_symbol_set_s* zbarSymbolSet;
@property(assign, nonatomic) BOOL filterSymbols;
-(id)initWithSymbolSet:(const zbar_symbol_set_s*)symbolSet;
-(void)dealloc;
-(unsigned)countByEnumeratingWithState:(XXStruct_kFm5bA*)state objects:(id*)objects count:(unsigned)count;
@end

