/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AirWatch-Structs.h"
#import <UIKit/UIViewController.h>

@class ZBarReaderView, ZBarCameraSimulator, UIView, ZBarHelpController, ZBarImageScanner;
@protocol ZBarReaderDelegate;

@interface ZBarReaderViewController : UIViewController {
	ZBarImageScanner* scanner;
	id<ZBarReaderDelegate> readerDelegate;
	ZBarReaderView* readerView;
	UIView* cameraOverlayView;
	CGAffineTransform cameraViewTransform;
	CGRect scanCrop;
	unsigned supportedOrientationsMask;
	unsigned cameraDevice;
	int cameraFlashMode;
	unsigned videoQuality;
	BOOL showsZBarControls;
	BOOL tracksSymbols;
	BOOL enableCache;
	ZBarHelpController* helpController;
	UIView* controls;
	BOOL didHideStatusBar;
	BOOL rotating;
	ZBarCameraSimulator* cameraSim;
}
@property(readonly, assign, nonatomic) ZBarImageScanner* scanner;
@property(assign, nonatomic) id<ZBarReaderDelegate> readerDelegate;
@property(assign, nonatomic) BOOL showsZBarControls;
@property(assign, nonatomic) unsigned supportedOrientationsMask;
@property(assign, nonatomic) BOOL tracksSymbols;
@property(assign, nonatomic) BOOL enableCache;
@property(retain, nonatomic) UIView* cameraOverlayView;
@property(assign, nonatomic) CGAffineTransform cameraViewTransform;
@property(assign, nonatomic) unsigned cameraDevice;
@property(assign, nonatomic) int cameraFlashMode;
@property(assign, nonatomic) unsigned videoQuality;
@property(readonly, assign, nonatomic) ZBarReaderView* readerView;
@property(assign, nonatomic) CGRect scanCrop;
@property(assign, nonatomic) unsigned sourceType;
@property(assign, nonatomic) BOOL allowsEditing;
@property(assign, nonatomic) BOOL allowsImageEditing;
@property(assign, nonatomic) BOOL showsCameraControls;
@property(assign, nonatomic) BOOL showsHelpOnFail;
@property(assign, nonatomic) int cameraMode;
@property(assign, nonatomic) BOOL takesPicture;
@property(assign, nonatomic) int maxScanDimension;
@property(assign, nonatomic) unsigned cameraCaptureMode;
+(BOOL)isSourceTypeAvailable:(unsigned)available;
+(BOOL)isCameraDeviceAvailable:(unsigned)available;
+(BOOL)isFlashAvailableForCameraDevice:(unsigned)cameraDevice;
+(id)availableCaptureModesForCameraDevice:(unsigned)cameraDevice;
-(void)_init;
-(id)init;
-(id)initWithCoder:(id)coder;
-(void)cleanup;
-(void)dealloc;
-(void)initControls;
-(void)initVideoQuality;
-(void)loadView;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(void)viewWillAppear:(BOOL)view;
-(void)dismissModalViewControllerAnimated:(BOOL)animated;
-(void)viewWillDisappear:(BOOL)view;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)cancel;
-(void)info;
-(void)showHelpWithReason:(id)reason;
-(void)takePicture;
-(void)helpControllerDidFinish:(id)helpController;
-(void)removeHelp:(id)help done:(id)done context:(void*)context;
-(void)readerView:(id)view didReadSymbols:(id)symbols fromImage:(id)image;
@end

