/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "AirWatch-Structs.h"

@class ZBarSymbolSet;

@interface ZBarImageScanner : NSObject {
	zbar_image_scanner_s* scanner;
}
@property(assign, nonatomic) BOOL enableCache;
@property(readonly, assign, nonatomic) ZBarSymbolSet* results;
-(id)init;
-(void)dealloc;
-(void)parseConfig:(id)config;
-(void)setSymbology:(int)symbology config:(int)config to:(int)to;
-(int)scanImage:(id)image;
@end

