/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "UIPopoverControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "UIImagePickerControllerDelegate.h"

@class ZBarReaderView, UIImagePickerController, UIViewController, UIPopoverController;

@interface ZBarCameraSimulator : NSObject <UINavigationControllerDelegate, UIImagePickerControllerDelegate, UIPopoverControllerDelegate> {
	UIViewController* viewController;
	ZBarReaderView* readerView;
	UIImagePickerController* picker;
	UIPopoverController* pickerPopover;
}
@property(assign, nonatomic) ZBarReaderView* readerView;
-(id)initWithViewController:(id)viewController;
-(void)dealloc;
-(void)didLongPress:(id)press;
-(void)takePicture;
-(void)imagePickerController:(id)controller didFinishPickingMediaWithInfo:(id)info;
-(void)imagePickerControllerDidCancel:(id)imagePickerController;
@end

