/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ZBarReaderView.h"
#import "AirWatch-Structs.h"

@class AVCaptureSession, AVCaptureDevice, AVCaptureInput;

@interface ZBarReaderViewImpl : ZBarReaderView {
	AVCaptureSession* session;
	AVCaptureDevice* device;
	AVCaptureInput* input;
}
@property(retain, nonatomic) AVCaptureDevice* device;
@property(readonly, assign, nonatomic) AVCaptureSession* session;
-(void)_initWithImageScanner:(id)imageScanner;
-(void)initSubviews;
-(void)dealloc;
-(void)updateCrop;
-(id)scanner;
-(BOOL)enableCache;
-(void)setEnableCache:(BOOL)cache;
-(void)setTorchMode:(int)mode;
-(void)setShowsFPS:(BOOL)fps;
-(void)start;
-(void)stop;
-(void)flushCache;
-(void)onVideoStart:(id)start;
-(void)onVideoStop:(id)stop;
-(void)onVideoError:(id)error;
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
-(void)captureReader:(id)reader didTrackSymbols:(id)symbols;
-(void)captureReader:(id)reader didReadNewSymbolsFromImage:(id)image;
@end

