/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AirWatch-Structs.h"
#import <Foundation/NSObject.h>

@class ZBarCVImage, ZBarImage, AVCaptureVideoDataOutput, ZBarImageScanner, AVCaptureOutput;
@protocol ZBarCaptureDelegate;

@interface ZBarCaptureReader : NSObject {
	AVCaptureVideoDataOutput* captureOutput;
	id<ZBarCaptureDelegate> captureDelegate;
	ZBarImageScanner* scanner;
	CGRect scanCrop;
	CGSize size;
	float framesPerSecond;
	BOOL enableCache;
	dispatch_queue_s* queue;
	ZBarImage* image;
	ZBarCVImage* result;
	unsigned state;
	int framecnt;
	unsigned width;
	unsigned height;
	unsigned long long t_frame;
	unsigned long long t_fps;
	unsigned long long t_scan;
	float dt_frame;
}
@property(readonly, assign, nonatomic) AVCaptureOutput* captureOutput;
@property(assign, nonatomic) id<ZBarCaptureDelegate> captureDelegate;
@property(readonly, assign, nonatomic) ZBarImageScanner* scanner;
@property(assign, nonatomic) CGRect scanCrop;
@property(readonly, assign, nonatomic) CGSize size;
@property(readonly, assign, nonatomic) float framesPerSecond;
@property(assign, nonatomic) BOOL enableCache;
@property(assign, nonatomic) BOOL enableReader;
-(void)initResult;
-(id)initWithImageScanner:(id)imageScanner;
-(id)init;
-(void)dealloc;
-(void)willStartRunning;
-(void)willStopRunning;
-(void)flushCache;
-(void)captureFrame;
-(void)cropUpdate;
-(void)didTrackSymbols:(id)symbols;
-(void)didReadNewSymbolsFromImage:(id)image;
-(void)setFramesPerSecond:(float)second;
-(void)updateFPS:(id)fps;
-(void)setSize:(CGSize)size;
-(void)updateSize:(CFDictionaryRef)size;
-(void)captureOutput:(id)output didOutputSampleBuffer:(opaqueCMSampleBuffer*)buffer fromConnection:(id)connection;
@end

