/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIImagePickerControllerDelegate.h"


@protocol ZBarReaderDelegate <UIImagePickerControllerDelegate>
@optional
-(void)readerControllerDidFailToRead:(id)readerController withRetry:(BOOL)retry;
@end

